//! Workflow history analyzer and linter.
//!
//! Provides rules and an engine to analyze workflow execution histories for
//! anti-patterns, performance bottlenecks, and suspicious behavior.

use crate::event::WorkflowEvent;
use std::collections::HashMap;

/// A warning generated by a history analyzer rule.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnalyzerWarning {
    /// The name of the rule that generated the warning.
    pub rule_name: String,
    /// A human-readable description of the warning.
    pub message: String,
}

/// A rule that analyzes a workflow history and generates warnings.
pub trait AnalyzerRule: Send + Sync {
    /// The name of this rule.
    fn name(&self) -> &'static str;

    /// Analyze the given history and return any warnings.
    fn analyze(&self, history: &[WorkflowEvent]) -> Vec<AnalyzerWarning>;
}

/// The main entry point for analyzing workflow histories.
pub struct HistoryAnalyzer {
    rules: Vec<Box<dyn AnalyzerRule>>,
}

impl HistoryAnalyzer {
    /// Create a new analyzer with the default set of rules.
    #[must_use]
    pub fn new() -> Self {
        Self { rules: Vec::new() }
    }

    /// Add a rule to the analyzer.
    #[must_use]
    pub fn with_rule(mut self, rule: impl AnalyzerRule + 'static) -> Self {
        self.rules.push(Box::new(rule));
        self
    }

    /// Analyze the given history against all registered rules.
    #[must_use]
    pub fn analyze(&self, history: &[WorkflowEvent]) -> Vec<AnalyzerWarning> {
        self.rules
            .iter()
            .flat_map(|rule| rule.analyze(history))
            .collect()
    }
}

impl Default for HistoryAnalyzer {
    fn default() -> Self {
        Self::new()
    }
}

// ── Rules ──────────────────────────────────────────────────────────────────

/// Flags activities that have failed more than `threshold` times.
pub struct ExcessiveRetriesRule {
    threshold: u32,
}

impl ExcessiveRetriesRule {
    /// Create a new `ExcessiveRetriesRule` with the given threshold.
    #[must_use]
    pub const fn new(threshold: u32) -> Self {
        Self { threshold }
    }
}

impl AnalyzerRule for ExcessiveRetriesRule {
    fn name(&self) -> &'static str {
        "ExcessiveRetries"
    }

    fn analyze(&self, history: &[WorkflowEvent]) -> Vec<AnalyzerWarning> {
        let mut warnings = Vec::new();
        let mut activity_names = HashMap::new();

        for event in history {
            match event {
                WorkflowEvent::ActivityScheduled {
                    activity_id, name, ..
                } => {
                    activity_names.insert(*activity_id, name.clone());
                }
                WorkflowEvent::ActivityFailed {
                    activity_id,
                    attempt,
                    ..
                } => {
                    if *attempt > self.threshold {
                        let name = activity_names
                            .get(activity_id)
                            .map_or("Unknown", |n| n.as_str());
                        warnings.push(AnalyzerWarning {
                            rule_name: self.name().to_string(),
                            message: format!(
                                "Activity '{}' failed {} times (threshold: {})",
                                name, attempt, self.threshold
                            ),
                        });
                    }
                }
                _ => {}
            }
        }

        warnings
    }
}

/// Flags timers with a duration of 0 seconds.
/// Zero duration timers are often an anti-pattern; consider yields or side effects.
pub struct SuspiciousTimerRule;

impl SuspiciousTimerRule {
    /// Create a new `SuspiciousTimerRule`.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl Default for SuspiciousTimerRule {
    fn default() -> Self {
        Self::new()
    }
}

impl AnalyzerRule for SuspiciousTimerRule {
    fn name(&self) -> &'static str {
        "SuspiciousTimer"
    }

    fn analyze(&self, history: &[WorkflowEvent]) -> Vec<AnalyzerWarning> {
        let mut warnings = Vec::new();

        for event in history {
            if let WorkflowEvent::TimerStarted { duration_secs, .. } = event {
                if *duration_secs == 0 {
                    warnings.push(AnalyzerWarning {
                        rule_name: self.name().to_string(),
                        message: "Suspicious 0-second timer detected. Consider using a side-effect or yield instead.".to_string(),
                    });
                }
            }
        }

        warnings
    }
}

/// Flags JSON payloads in events that exceed a specified byte threshold.
/// Large payloads can bloat the database and impact history replay performance.
pub struct LargePayloadRule {
    max_bytes: usize,
}

impl LargePayloadRule {
    /// Create a new `LargePayloadRule` with the given byte threshold.
    #[must_use]
    pub const fn new(max_bytes: usize) -> Self {
        Self { max_bytes }
    }
}

impl AnalyzerRule for LargePayloadRule {
    fn name(&self) -> &'static str {
        "LargePayload"
    }

    fn analyze(&self, history: &[WorkflowEvent]) -> Vec<AnalyzerWarning> {
        let mut warnings = Vec::new();

        for event in history {
            let (payload, context) = match event {
                WorkflowEvent::WorkflowStarted { input, .. } => {
                    (Some(input), "Workflow Started input")
                }
                WorkflowEvent::WorkflowCompleted { output, .. } => {
                    (Some(output), "Workflow Completed output")
                }
                WorkflowEvent::ActivityScheduled { input, .. } => {
                    (Some(input), "Activity Scheduled input")
                }
                WorkflowEvent::ActivityCompleted { output, .. } => {
                    (Some(output), "Activity Completed output")
                }
                WorkflowEvent::SignalReceived { payload, .. } => {
                    (Some(payload), "Signal Received payload")
                }
                WorkflowEvent::ChildWorkflowStarted { input, .. } => {
                    (Some(input), "Child Workflow Started input")
                }
                WorkflowEvent::ChildWorkflowCompleted { output, .. } => {
                    (Some(output), "Child Workflow Completed output")
                }
                WorkflowEvent::MarkerRecorded { details, .. } => {
                    (Some(details), "Marker Recorded details")
                }
                _ => (None, ""),
            };

            if let Some(p) = payload {
                // Calculate roughly the size in bytes when serialized to a string
                let size = p.to_string().len();
                if size > self.max_bytes {
                    warnings.push(AnalyzerWarning {
                        rule_name: self.name().to_string(),
                        message: format!(
                            "Large payload detected in {} ({} bytes, threshold: {})",
                            context, size, self.max_bytes
                        ),
                    });
                }
            }
        }

        warnings
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{ActivityExecId, TimerId};
    use chrono::Utc;

    #[test]
    fn excessive_retries_flags_activities_over_threshold() {
        let rule = ExcessiveRetriesRule::new(2);
        let id1 = ActivityExecId::new();
        let id2 = ActivityExecId::new();

        let history = vec![
            WorkflowEvent::ActivityScheduled {
                activity_id: id1,
                name: "EmailTask".to_string(),
                input: serde_json::Value::Null,
                queue: "default".to_string(),
            },
            WorkflowEvent::ActivityScheduled {
                activity_id: id2,
                name: "BillingTask".to_string(),
                input: serde_json::Value::Null,
                queue: "default".to_string(),
            },
            // Failed once, below threshold
            WorkflowEvent::ActivityFailed {
                activity_id: id1,
                error: "Timeout".to_string(),
                attempt: 1,
            },
            // Failed 3 times, above threshold of 2
            WorkflowEvent::ActivityFailed {
                activity_id: id2,
                error: "Card Declined".to_string(),
                attempt: 3,
            },
        ];

        let warnings = rule.analyze(&history);
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0].rule_name, "ExcessiveRetries");
        assert!(warnings[0].message.contains("BillingTask"));
        assert!(warnings[0].message.contains("failed 3 times"));
    }

    #[test]
    fn suspicious_timer_flags_zero_duration() {
        let rule = SuspiciousTimerRule::new();
        let history = vec![
            WorkflowEvent::TimerStarted {
                timer_id: TimerId::new("valid-timer"),
                duration_secs: 10,
            },
            WorkflowEvent::TimerStarted {
                timer_id: TimerId::new("zero-timer"),
                duration_secs: 0,
            },
        ];

        let warnings = rule.analyze(&history);
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0].rule_name, "SuspiciousTimer");
        assert!(warnings[0].message.contains("0-second timer"));
    }

    #[test]
    fn large_payload_flags_events_over_threshold() {
        let rule = LargePayloadRule::new(50); // 50 bytes max

        let small_json = serde_json::json!({"id": 1});
        // 51 chars/bytes
        let large_json = serde_json::json!({"data": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"});

        let history = vec![
            WorkflowEvent::WorkflowStarted {
                input: small_json,
                timestamp: Utc::now(),
            },
            WorkflowEvent::ActivityCompleted {
                activity_id: ActivityExecId::new(),
                output: large_json,
            },
        ];

        let warnings = rule.analyze(&history);
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0].rule_name, "LargePayload");
        assert!(warnings[0].message.contains("Activity Completed output"));
        assert!(warnings[0].message.contains("threshold: 50"));
    }

    #[test]
    fn history_analyzer_engine_runs_all_rules() {
        let analyzer = HistoryAnalyzer::new()
            .with_rule(SuspiciousTimerRule::new())
            .with_rule(ExcessiveRetriesRule::new(1));

        let history = vec![
            WorkflowEvent::TimerStarted {
                timer_id: TimerId::new("zero"),
                duration_secs: 0,
            },
            WorkflowEvent::ActivityScheduled {
                activity_id: ActivityExecId::new(),
                name: "FailTask".to_string(),
                input: serde_json::Value::Null,
                queue: "default".to_string(),
            },
            WorkflowEvent::ActivityFailed {
                activity_id: ActivityExecId::new(), // Technically mismatch ID but rule checks just the event for simplicity/demo
                error: "Err".to_string(),
                attempt: 2,
            },
        ];

        let warnings = analyzer.analyze(&history);
        assert_eq!(
            warnings.len(),
            2,
            "Should trigger both timer and retry warnings"
        );
    }
}
