//! DAG configuration analyzer and linter.
//!
//! Provides rules and an engine to statically analyze workflow `DagDefinition`s
//! for anti-patterns, missing resilience configurations, and suspicious topologies
//! before they are executed.

use crate::dag::DagDefinition;

/// A warning generated by a DAG analyzer rule.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DagWarning {
    /// The name of the rule that generated the warning.
    pub rule_name: String,
    /// A human-readable description of the warning.
    pub message: String,
}

/// A rule that statically analyzes a DAG definition and generates warnings.
pub trait DagRule: Send + Sync {
    /// The name of this rule.
    fn name(&self) -> &'static str;

    /// Analyze the given DAG definition and return any warnings.
    fn analyze(
        &self,
        dag: &DagDefinition,
        activities: &std::collections::HashMap<String, crate::info::ActivityInfo>,
    ) -> Vec<DagWarning>;
}

/// The main entry point for statically analyzing DAG definitions.
pub struct DagLinter {
    rules: Vec<Box<dyn DagRule>>,
}

impl DagLinter {
    /// Create a new linter with no rules.
    #[must_use]
    pub fn new() -> Self {
        Self { rules: Vec::new() }
    }

    /// Add a rule to the linter.
    #[must_use]
    pub fn with_rule(mut self, rule: impl DagRule + 'static) -> Self {
        self.rules.push(Box::new(rule));
        self
    }

    /// Analyze the DAG definition using all registered rules.
    #[must_use]
    pub fn analyze(
        &self,
        dag: &DagDefinition,
        activities: &std::collections::HashMap<String, crate::info::ActivityInfo>,
    ) -> Vec<DagWarning> {
        self.rules
            .iter()
            .flat_map(|rule| rule.analyze(dag, activities))
            .collect()
    }
}

impl Default for DagLinter {
    fn default() -> Self {
        Self::new()
    }
}

// ── Rules ──────────────────────────────────────────────────────────────────

/// Flags tasks that do not have a configured `RetryPolicy`.
///
/// In distributed systems, transient failures are common. Tasks without
/// retry policies are brittle.
pub struct MissingRetryPolicyRule;

impl MissingRetryPolicyRule {
    /// Create a new `MissingRetryPolicyRule`.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl Default for MissingRetryPolicyRule {
    fn default() -> Self {
        Self::new()
    }
}

impl DagRule for MissingRetryPolicyRule {
    fn name(&self) -> &'static str {
        "MissingRetryPolicy"
    }

    fn analyze(
        &self,
        dag: &DagDefinition,
        activities: &std::collections::HashMap<String, crate::info::ActivityInfo>,
    ) -> Vec<DagWarning> {
        let mut warnings = Vec::new();

        for task in dag.tasks() {
            let has_retry = task.retry_policy.is_some()
                || activities
                    .get(&task.activity_name)
                    .is_some_and(|info| info.default_retry_policy.is_some());
            if !has_retry {
                warnings.push(DagWarning {
                    rule_name: self.name().to_string(),
                    message: format!(
                        "Task '{}' has no retry policy configured. Transient failures will cause the workflow to fail immediately.",
                        task.activity_name
                    ),
                });
            }
        }

        warnings
    }
}

/// Flags tasks that do not have a configured `start_to_close` timeout.
///
/// Tasks without timeouts can hang indefinitely if the worker crashes or the
/// activity gets stuck.
pub struct MissingTimeoutRule;

impl MissingTimeoutRule {
    /// Create a new `MissingTimeoutRule`.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl Default for MissingTimeoutRule {
    fn default() -> Self {
        Self::new()
    }
}

impl DagRule for MissingTimeoutRule {
    fn name(&self) -> &'static str {
        "MissingTimeout"
    }

    fn analyze(
        &self,
        dag: &DagDefinition,
        activities: &std::collections::HashMap<String, crate::info::ActivityInfo>,
    ) -> Vec<DagWarning> {
        let mut warnings = Vec::new();

        for task in dag.tasks() {
            let has_timeout = task.start_to_close.is_some()
                || activities
                    .get(&task.activity_name)
                    .is_some_and(|info| info.default_start_to_close.is_some());
            if !has_timeout {
                warnings.push(DagWarning {
                    rule_name: self.name().to_string(),
                    message: format!(
                        "Task '{}' has no start_to_close timeout configured. If the activity hangs, the workflow will stall indefinitely.",
                        task.activity_name
                    ),
                });
            }
        }

        warnings
    }
}

/// Flags DAG levels that have an unusually high number of concurrent tasks.
///
/// Massive parallelism can overwhelm database connection pools or worker resources.
pub struct ExcessiveParallelismRule {
    threshold: usize,
}

impl ExcessiveParallelismRule {
    /// Create a new `ExcessiveParallelismRule` with the given threshold.
    #[must_use]
    pub const fn new(threshold: usize) -> Self {
        Self { threshold }
    }
}

impl DagRule for ExcessiveParallelismRule {
    fn name(&self) -> &'static str {
        "ExcessiveParallelism"
    }

    fn analyze(
        &self,
        dag: &DagDefinition,
        _activities: &std::collections::HashMap<String, crate::info::ActivityInfo>,
    ) -> Vec<DagWarning> {
        let mut warnings = Vec::new();

        for (level_idx, level) in dag.execution_levels().iter().enumerate() {
            if level.len() > self.threshold {
                warnings.push(DagWarning {
                    rule_name: self.name().to_string(),
                    message: format!(
                        "Execution level {} has {} concurrent tasks (threshold: {}). This may cause resource exhaustion or pool starvation.",
                        level_idx,
                        level.len(),
                        self.threshold
                    ),
                });
            }
        }

        warnings
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dag::DagBuilder;
    use crate::info::ActivityInfo;
    use crate::policy::RetryPolicy;
    use std::time::Duration;

    #[test]
    fn missing_retry_policy_flags_unconfigured_tasks() {
        let rule = MissingRetryPolicyRule::new();

        let mut builder = DagBuilder::new();
        let _t1 = builder.activity(|| Ok::<(), ()>(())); // No retry
        let _t2 = builder
            .activity(|| Ok::<(), ()>(()))
            .retry(RetryPolicy::exponential(3, Duration::from_secs(1)));
        let dag = builder.build().unwrap();

        let warnings = rule.analyze(&dag, &std::collections::HashMap::new());
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0].rule_name, "MissingRetryPolicy");
        assert!(warnings[0].message.contains("has no retry policy"));
    }

    #[test]
    fn missing_timeout_flags_unconfigured_tasks() {
        let rule = MissingTimeoutRule::new();

        let mut builder = DagBuilder::new();
        let _t1 = builder.activity(|| Ok::<(), ()>(())); // No timeout
        let _t2 = builder
            .activity(|| Ok::<(), ()>(()))
            .start_to_close(Duration::from_secs(300));
        let dag = builder.build().unwrap();

        let warnings = rule.analyze(&dag, &std::collections::HashMap::new());
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0].rule_name, "MissingTimeout");
        assert!(
            warnings[0]
                .message
                .contains("has no start_to_close timeout")
        );
    }

    #[test]
    fn excessive_parallelism_flags_wide_levels() {
        let rule = ExcessiveParallelismRule::new(2);

        let mut builder = DagBuilder::new();
        let _t1 = builder.activity(|| Ok::<(), ()>(()));
        let _t2 = builder.activity(|| Ok::<(), ()>(()));
        let _t3 = builder.activity(|| Ok::<(), ()>(()));

        // All tasks are level 0 (3 concurrent, threshold 2)
        let dag = builder.build().unwrap();

        let warnings = rule.analyze(&dag, &std::collections::HashMap::new());
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0].rule_name, "ExcessiveParallelism");
        assert!(warnings[0].message.contains("3 concurrent tasks"));
    }

    #[test]
    fn dag_linter_runs_all_rules() {
        let linter = DagLinter::new()
            .with_rule(MissingRetryPolicyRule::new())
            .with_rule(MissingTimeoutRule::new())
            .with_rule(ExcessiveParallelismRule::new(1));

        let mut builder = DagBuilder::new();
        let _t1 = builder.activity(|| Ok::<(), ()>(()));
        let _t2 = builder.activity(|| Ok::<(), ()>(()));
        let dag = builder.build().unwrap();

        let warnings = linter.analyze(&dag, &std::collections::HashMap::new());
        // t1 & t2 missing retry (2)
        // t1 & t2 missing timeout (2)
        // level 0 has 2 tasks, threshold 1 (1)
        assert_eq!(warnings.len(), 5);
    }

    fn my_test_activity() {}

    fn dummy_handler(
        _ctx: &crate::context::ActivityContext,
        _val: serde_json::Value,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Result<serde_json::Value, String>> + Send + '_>,
    > {
        Box::pin(async { Ok(serde_json::Value::Null) })
    }

    #[test]
    fn dag_linter_respects_activity_defaults() {
        let linter = DagLinter::new()
            .with_rule(MissingRetryPolicyRule::new())
            .with_rule(MissingTimeoutRule::new());

        let mut builder = DagBuilder::new();
        let _t1 = builder.activity(my_test_activity); // Has no explicit config, but we will provide default
        let dag = builder.build().unwrap();

        let mut activities = std::collections::HashMap::new();
        activities.insert(
            "my_test_activity".to_string(),
            ActivityInfo {
                name: "my_test_activity",
                module: "test",
                default_retry_policy: Some(RetryPolicy::exponential(3, Duration::from_secs(1))),
                default_start_to_close: Some(Duration::from_secs(300)),
                default_heartbeat_timeout: None,
                default_schedule_to_start: None,
                default_queue: None,
                max_concurrent: None,
                concurrency_key: None,
                is_local: false,
                max_input_bytes: None,
                max_result_bytes: None,
                handler: dummy_handler,
            },
        );

        let warnings = linter.analyze(&dag, &activities);
        assert_eq!(warnings.len(), 0);
    }
}
