//! DAG Chaos Simulator.
//!
//! Provides a test bed for evaluating DAG reliability under random faults,
//! helping identify critical points of failure in a DAG topology.

use crate::dag::DagDefinition;
use crate::dag_simulator::DagSimulator;
use crate::policy::TaskStatus;
use rand::Rng;
use std::collections::HashMap;
use std::fmt::Write;

/// A report generated by the DAG chaos simulator.
#[derive(Debug, Clone)]
pub struct DagChaosReport {
    /// Total iterations run.
    pub total_iterations: usize,
    /// Total successful task executions.
    pub task_successes: Vec<usize>,
    /// Total failed task executions.
    pub task_failures: Vec<usize>,
    /// Total skipped task executions.
    pub task_skips: Vec<usize>,
    /// Task names, corresponding to the vectors.
    pub task_names: Vec<String>,
}

impl DagChaosReport {
    /// Render the chaos report as a Markdown string.
    #[must_use]
    #[allow(clippy::cast_precision_loss)]
    pub fn to_markdown(&self) -> String {
        let mut out = String::new();
        out.push_str("# DAG Chaos Report\n\n");
        let _ = writeln!(out, "**Total Iterations:** {}", self.total_iterations);
        out.push_str("\n## Node Reliability\n\n");
        out.push_str("| Node | Success Rate | Failures | Skips |\n");
        out.push_str("|---|---|---|---|\n");

        for i in 0..self.task_names.len() {
            let successes = self.task_successes[i];
            let failures = self.task_failures[i];
            let skips = self.task_skips[i];

            let success_rate = if self.total_iterations > 0 {
                (successes as f64 / self.total_iterations as f64) * 100.0
            } else {
                0.0
            };

            let _ = writeln!(
                out,
                "| {} | {:.2}% | {} | {} |",
                self.task_names[i], success_rate, failures, skips
            );
        }

        out
    }
}

/// A discrete-event simulator to profile DAG reliability under random failure.
pub struct DagChaosSimulator {
    dag: DagDefinition,
    failure_probabilities: HashMap<String, f64>,
    default_failure_probability: f64,
    iterations: usize,
}

impl DagChaosSimulator {
    /// Create a new chaos simulator.
    #[must_use]
    pub fn new(dag: DagDefinition) -> Self {
        Self {
            dag,
            failure_probabilities: HashMap::new(),
            default_failure_probability: 0.1,
            iterations: 100,
        }
    }

    /// Set a default failure probability for activities (0.0 to 1.0).
    #[must_use]
    pub const fn with_default_failure_probability(mut self, prob: f64) -> Self {
        self.default_failure_probability = prob;
        self
    }

    /// Set the number of iterations to run.
    #[must_use]
    pub const fn with_iterations(mut self, iterations: usize) -> Self {
        self.iterations = iterations;
        self
    }

    /// Mock the failure probability of a specific activity by name (0.0 to 1.0).
    #[must_use]
    pub fn mock_failure_probability(mut self, name: &str, prob: f64) -> Self {
        self.failure_probabilities.insert(name.to_string(), prob);
        self
    }

    /// Run the simulation.
    #[must_use]
    pub fn simulate(&self) -> DagChaosReport {
        let tasks = self.dag.tasks();
        let mut task_successes = vec![0; tasks.len()];
        let mut task_failures = vec![0; tasks.len()];
        let mut task_skips = vec![0; tasks.len()];
        let task_names: Vec<String> = tasks.iter().map(|t| t.activity_name.clone()).collect();

        if tasks.is_empty() {
            return DagChaosReport {
                total_iterations: self.iterations,
                task_successes,
                task_failures,
                task_skips,
                task_names,
            };
        }

        for _ in 0..self.iterations {
            let mut sim = DagSimulator::new(self.dag.clone());

            for task in tasks {
                let prob = self
                    .failure_probabilities
                    .get(&task.activity_name)
                    .copied()
                    .unwrap_or(self.default_failure_probability);

                let name_clone = task.activity_name.clone();
                sim = sim.mock_activity(&name_clone, move || {
                    let mut rng = rand::thread_rng();
                    if rng.gen_bool(prob) {
                        Err("Chaos failure".into())
                    } else {
                        Ok(())
                    }
                });
            }

            let result = sim.run();

            for (i, status) in result.task_states.iter().enumerate() {
                match status {
                    TaskStatus::Succeeded => task_successes[i] += 1,
                    TaskStatus::Failed => task_failures[i] += 1,
                    TaskStatus::Skipped => task_skips[i] += 1,
                }
            }
        }

        DagChaosReport {
            total_iterations: self.iterations,
            task_successes,
            task_failures,
            task_skips,
            task_names,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dag::DagBuilder;
    use crate::policy::TriggerRule;

    fn activity_a() {}
    fn activity_b() {}
    fn activity_c() {}
    fn activity_d() {}

    #[test]
    fn test_chaos_zero_failure() {
        let mut builder = DagBuilder::new();
        let a = builder.activity(activity_a);
        let _b = builder.activity(activity_b).upstream(&a);
        let dag = builder.build().unwrap();

        let sim = DagChaosSimulator::new(dag)
            .with_iterations(10)
            .with_default_failure_probability(0.0);

        let report = sim.simulate();
        assert_eq!(report.task_successes, vec![10, 10]);
        assert_eq!(report.task_failures, vec![0, 0]);
        assert_eq!(report.task_skips, vec![0, 0]);

        let md = report.to_markdown();
        assert!(md.contains("100.00%"));
    }

    #[test]
    fn test_chaos_total_failure() {
        let mut builder = DagBuilder::new();
        let a = builder.activity(activity_a);
        let _b = builder.activity(activity_b).upstream(&a);
        let dag = builder.build().unwrap();

        let sim = DagChaosSimulator::new(dag)
            .with_iterations(10)
            .with_default_failure_probability(1.0);

        let report = sim.simulate();
        // A fails, B skips
        assert_eq!(report.task_failures[0], 10);
        assert_eq!(report.task_skips[1], 10);
        assert_eq!(report.task_successes, vec![0, 0]);
    }

    #[test]
    fn test_chaos_one_success_trigger() {
        let mut builder = DagBuilder::new();
        let start = builder.activity(activity_a);
        let branch1 = builder.activity(activity_b).upstream(&start);
        let branch2 = builder.activity(activity_c).upstream(&start);
        let _end = builder
            .activity(activity_d)
            .upstream(&branch1)
            .upstream(&branch2)
            .trigger_rule(TriggerRule::OneSuccess);
        let dag = builder.build().unwrap();

        let sim = DagChaosSimulator::new(dag)
            .with_iterations(10)
            .mock_failure_probability("activity_a", 0.0) // Start always succeeds
            .mock_failure_probability("activity_b", 1.0) // branch1 always fails
            .mock_failure_probability("activity_c", 0.0) // branch2 always succeeds
            .mock_failure_probability("activity_d", 0.0); // End always succeeds if it runs

        let report = sim.simulate();
        // End task should always succeed because branch2 succeeds, satisfying OneSuccess
        assert_eq!(report.task_successes[3], 10);
    }
}
