//! Chrome Trace Format exporter for DAG execution profiles.
//!
//! Provides utilities to export the timeline data generated by `DagProfiler`
//! into the JSON format expected by Chrome's `chrome://tracing` tool and
//! modern alternatives like Perfetto.

use crate::dag_profiler::{DagProfile, ProfilerEventKind};
use serde_json::json;
use std::collections::HashMap;

/// Exports a `DagProfile` timeline to Chrome Trace Format JSON.
///
/// This generates an array of trace events representing the start and end
/// of each activity in the DAG. It can be saved to a `.json` file and opened
/// in tools like Perfetto or `chrome://tracing` to visually inspect concurrency,
/// critical paths, and bottlenecks.
///
/// # Examples
///
/// ```rust
/// use autumn_harvest::dag::DagBuilder;
/// use autumn_harvest::dag_profiler::DagProfiler;
/// use autumn_harvest::dag_trace::export_trace_json;
/// use std::time::Duration;
///
/// fn my_activity() {}
///
/// let mut builder = DagBuilder::new();
/// let _a = builder.activity(my_activity);
/// let dag = builder.build().unwrap();
///
/// let profile = DagProfiler::new(dag).profile();
/// let json = export_trace_json(&profile);
/// assert!(json.contains("my_activity"));
/// assert!(json.contains("ph")); // Phase indicator
/// ```
#[must_use]
pub fn export_trace_json(profile: &DagProfile) -> String {
    let mut events = Vec::new();

    // Map task indices to their assigned concurrency lanes to keep the
    // timeline visualization stable and readable.
    let mut active_lanes: Vec<bool> = Vec::new();
    let mut task_to_lane: HashMap<usize, usize> = HashMap::new();

    for event in &profile.timeline {
        // Chrome trace format uses microseconds
        #[allow(clippy::cast_possible_truncation)]
        let ts_micros = event.time.as_micros() as i64;

        match &event.kind {
            ProfilerEventKind::TaskStarted(idx, name) => {
                // Find a free lane (tid)
                let mut assigned_lane = 0;
                for (lane, is_active) in active_lanes.iter_mut().enumerate() {
                    if !*is_active {
                        *is_active = true;
                        assigned_lane = lane + 1; // 1-based indexing for lanes
                        break;
                    }
                }

                if assigned_lane == 0 {
                    // All existing lanes are busy, add a new one
                    active_lanes.push(true);
                    assigned_lane = active_lanes.len();
                }

                task_to_lane.insert(*idx, assigned_lane);

                events.push(json!({
                    "name": name,
                    "cat": "activity",
                    "ph": "B", // Begin
                    "ts": ts_micros,
                    "pid": 1,
                    "tid": assigned_lane,
                }));
            }
            ProfilerEventKind::TaskCompleted(idx, name) => {
                let lane = task_to_lane.remove(idx).unwrap_or(1);
                if lane > 0 && lane <= active_lanes.len() {
                    active_lanes[lane - 1] = false;
                }

                events.push(json!({
                    "name": name,
                    "cat": "activity",
                    "ph": "E", // End
                    "ts": ts_micros,
                    "pid": 1,
                    "tid": lane,
                }));
            }
        }
    }

    // Wrap the array of events as Chrome tools expect
    json!(events).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dag::DagBuilder;
    use crate::dag_profiler::DagProfiler;
    use std::time::Duration;

    fn activity_a() {}
    fn activity_b() {}

    #[test]
    fn test_export_trace_json_empty() {
        let builder = DagBuilder::new();
        let dag = builder.build().unwrap();
        let profile = DagProfiler::new(dag).profile();

        let trace = export_trace_json(&profile);
        assert_eq!(trace, "[]");
    }

    #[test]
    fn test_export_trace_json_simple() {
        let mut builder = DagBuilder::new();
        let _a = builder.activity(activity_a);
        let dag = builder.build().unwrap();

        let profile = DagProfiler::new(dag)
            .mock_duration("activity_a", Duration::from_micros(1500))
            .profile();

        let trace = export_trace_json(&profile);
        let parsed: serde_json::Value = serde_json::from_str(&trace).unwrap();
        let array = parsed.as_array().unwrap();

        assert_eq!(array.len(), 2);

        // Start event
        assert_eq!(array[0]["name"], "activity_a");
        assert_eq!(array[0]["ph"], "B");
        assert_eq!(array[0]["ts"], 0);
        assert_eq!(array[0]["tid"], 1);

        // End event
        assert_eq!(array[1]["name"], "activity_a");
        assert_eq!(array[1]["ph"], "E");
        assert_eq!(array[1]["ts"], 1500);
        assert_eq!(array[1]["tid"], 1);
    }

    #[test]
    fn test_export_trace_json_parallel() {
        let mut builder = DagBuilder::new();
        let a = builder.activity(activity_a);
        let _b1 = builder.activity(activity_b).upstream(&a);
        let _b2 = builder.activity(activity_b).upstream(&a);
        let dag = builder.build().unwrap();

        let profile = DagProfiler::new(dag)
            .mock_duration("activity_a", Duration::from_micros(1000))
            .mock_duration("activity_b", Duration::from_micros(2000))
            .profile();

        let trace = export_trace_json(&profile);
        let parsed: serde_json::Value = serde_json::from_str(&trace).unwrap();
        let array = parsed.as_array().unwrap();

        // 3 tasks = 6 events
        assert_eq!(array.len(), 6);

        // We expect tid 1 and tid 2 to be used for the parallel tasks
        let tids: Vec<i64> = array.iter().map(|v| v["tid"].as_i64().unwrap()).collect();
        assert!(tids.contains(&1));
        assert!(tids.contains(&2));
    }
}
