//! Monte Carlo DAG Simulator for probabilistic execution forecasting.
//!
//! Evaluates the behavior of a DAG under stochastic conditions, where tasks
//! have configurable failure probabilities and variable durations.

use std::collections::HashMap;
use std::time::Duration;

use rand::Rng;

use crate::dag::DagDefinition;
use crate::policy::TaskStatus;

/// Stochastic configuration for an activity.
#[derive(Debug, Clone, Copy)]
pub struct StochasticConfig {
    /// Probability of failure between 0.0 (never fails) and 1.0 (always fails).
    pub failure_probability: f64,
    /// Minimum possible duration.
    pub min_duration: Duration,
    /// Maximum possible duration.
    pub max_duration: Duration,
}

impl Default for StochasticConfig {
    fn default() -> Self {
        Self {
            failure_probability: 0.0,
            min_duration: Duration::from_secs(1),
            max_duration: Duration::from_secs(1),
        }
    }
}

/// Report generated by the Monte Carlo simulator.
#[derive(Debug, Clone, PartialEq)]
pub struct MonteCarloReport {
    /// Number of simulated iterations.
    pub total_iterations: usize,
    /// Number of iterations where no task failed.
    pub fully_successful_iterations: usize,
    /// Success rate (0.0 to 1.0).
    pub success_rate: f64,
    /// Average total duration across all iterations.
    pub average_duration: Duration,
    /// Minimum total duration observed.
    pub min_duration: Duration,
    /// Maximum total duration observed.
    pub max_duration: Duration,
}

/// Simulator for running Monte Carlo experiments on DAGs.
pub struct DagMonteCarlo {
    dag: DagDefinition,
    configs: HashMap<String, StochasticConfig>,
    default_config: StochasticConfig,
}

impl DagMonteCarlo {
    /// Create a new Monte Carlo simulator.
    #[must_use]
    pub fn new(dag: DagDefinition) -> Self {
        Self {
            dag,
            configs: HashMap::new(),
            default_config: StochasticConfig::default(),
        }
    }

    /// Set the default stochastic configuration for unconfigured activities.
    #[must_use]
    pub const fn with_default_config(mut self, config: StochasticConfig) -> Self {
        self.default_config = config;
        self
    }

    /// Set the stochastic configuration for a specific activity.
    #[must_use]
    pub fn mock_activity(mut self, name: &str, config: StochasticConfig) -> Self {
        self.configs.insert(name.to_string(), config);
        self
    }

    /// Run the Monte Carlo simulation for `iterations`.
    #[must_use]
    pub fn run(&self, iterations: usize) -> MonteCarloReport {
        if iterations == 0 || self.dag.tasks().is_empty() {
            return MonteCarloReport {
                total_iterations: iterations,
                fully_successful_iterations: 0,
                success_rate: 0.0,
                average_duration: Duration::ZERO,
                min_duration: Duration::ZERO,
                max_duration: Duration::ZERO,
            };
        }

        let mut rng = rand::thread_rng();
        let tasks = self.dag.tasks();
        let levels = self.dag.execution_levels();

        let mut fully_successful_iterations = 0;
        let mut total_duration_sum = Duration::ZERO;
        let mut min_duration = Duration::MAX;
        let mut max_duration = Duration::ZERO;

        for _ in 0..iterations {
            let mut task_states = vec![TaskStatus::Skipped; tasks.len()];
            let mut task_end_times = vec![Duration::ZERO; tasks.len()];
            let mut iteration_failed = false;

            for level in levels {
                for &task_index in level {
                    let task = &tasks[task_index];

                    let upstream_statuses: Vec<TaskStatus> = task
                        .upstreams
                        .iter()
                        .map(|&up_idx| task_states[up_idx])
                        .collect();

                    if task.trigger_rule.should_run(&upstream_statuses) {
                        let config = self
                            .configs
                            .get(&task.activity_name)
                            .unwrap_or(&self.default_config);

                        let failed = rng.gen_bool(config.failure_probability);

                        let duration = if config.min_duration >= config.max_duration {
                            config.min_duration
                        } else {
                            rng.gen_range(config.min_duration..=config.max_duration)
                        };

                        let mut start_time = Duration::ZERO;
                        for &up_idx in &task.upstreams {
                            start_time = start_time.max(task_end_times[up_idx]);
                        }

                        task_end_times[task_index] = start_time + duration;

                        if failed {
                            task_states[task_index] = TaskStatus::Failed;
                            iteration_failed = true;
                        } else {
                            task_states[task_index] = TaskStatus::Succeeded;
                        }
                    } else {
                        task_states[task_index] = TaskStatus::Skipped;
                        // For skipped tasks, end time is the max of upstream end times
                        let mut start_time = Duration::ZERO;
                        for &up_idx in &task.upstreams {
                            start_time = start_time.max(task_end_times[up_idx]);
                        }
                        task_end_times[task_index] = start_time;
                    }
                }
            }

            if !iteration_failed {
                fully_successful_iterations += 1;
            }

            let iter_duration = task_end_times.into_iter().max().unwrap_or(Duration::ZERO);
            total_duration_sum += iter_duration;
            min_duration = min_duration.min(iter_duration);
            max_duration = max_duration.max(iter_duration);
        }

        #[allow(clippy::cast_precision_loss, clippy::cast_possible_truncation)]
        let success_rate = fully_successful_iterations as f64 / iterations as f64;
        #[allow(clippy::cast_possible_truncation)]
        let iter_u32 = iterations as u32;

        MonteCarloReport {
            total_iterations: iterations,
            fully_successful_iterations,
            success_rate,
            average_duration: total_duration_sum / iter_u32,
            min_duration,
            max_duration,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dag::DagBuilder;

    fn activity_a() {}
    fn activity_b() {}

    #[test]
    fn test_monte_carlo_always_succeeds() {
        let mut builder = DagBuilder::new();
        let a = builder.activity(activity_a);
        let _b = builder.activity(activity_b).upstream(&a);
        let dag = builder.build().unwrap();

        let mc = DagMonteCarlo::new(dag).with_default_config(StochasticConfig {
            failure_probability: 0.0,
            min_duration: Duration::from_secs(1),
            max_duration: Duration::from_secs(1),
        });

        let report = mc.run(100);
        assert_eq!(report.total_iterations, 100);
        assert_eq!(report.fully_successful_iterations, 100);
        assert!((report.success_rate - 1.0).abs() < f64::EPSILON);
        assert_eq!(report.average_duration, Duration::from_secs(2));
        assert_eq!(report.min_duration, Duration::from_secs(2));
        assert_eq!(report.max_duration, Duration::from_secs(2));
    }

    #[test]
    fn test_monte_carlo_always_fails() {
        let mut builder = DagBuilder::new();
        let a = builder.activity(activity_a);
        let _b = builder.activity(activity_b).upstream(&a);
        let dag = builder.build().unwrap();

        let mc = DagMonteCarlo::new(dag).with_default_config(StochasticConfig {
            failure_probability: 1.0,
            min_duration: Duration::from_secs(1),
            max_duration: Duration::from_secs(1),
        });

        let report = mc.run(100);
        assert_eq!(report.total_iterations, 100);
        assert_eq!(report.fully_successful_iterations, 0);
        assert!((report.success_rate - 0.0).abs() < f64::EPSILON);
    }
}
