//! Registration types returned by macro-generated companion functions.
//!
//! `#[workflow]` generates `__autumn_workflow_info_*() -> WorkflowInfo`.
//! `#[activity]` generates `__autumn_activity_info_*() -> ActivityInfo`.
//! `#[query]` generates `__autumn_query_handler_info_*() -> QueryHandlerInfo`.
//! `#[update]` generates `__autumn_update_handler_info_*() -> UpdateHandlerInfo`.
//! These are collected by `workflows![]`, `activities![]`, `queries![]`, `updates![]`.

use std::future::Future;
use std::pin::Pin;
use std::time::Duration;

use crate::dag::{DagBuildError, DagBuilder, DagDefinition};
use crate::policy::{RetryPolicy, Schedule, WorkflowSchedule};

/// Type-erased workflow handler.
///
/// Takes a `WorkflowContext` reference and serialized JSON input;
/// returns serialized JSON output (or an error string).
///
/// The macro wraps the user's typed function to handle
/// serialization/deserialization at the boundary.
pub type WorkflowHandlerFn =
    fn(
        &crate::context::WorkflowContext,
        serde_json::Value,
    ) -> Pin<Box<dyn Future<Output = Result<serde_json::Value, String>> + Send + '_>>;

/// Type-erased activity handler.
pub type ActivityHandlerFn =
    fn(
        &crate::context::ActivityContext,
        serde_json::Value,
    ) -> Pin<Box<dyn Future<Output = Result<serde_json::Value, String>> + Send + '_>>;

/// Type-erased synchronous query handler for declarative `#[query]` functions.
///
/// Takes a `WorkflowContext` reference for shared-state access and the
/// serialised JSON input; returns serialised JSON output or an error string.
/// Query handlers are synchronous — they inspect state without performing I/O.
pub type QueryHandlerFn =
    fn(&crate::context::WorkflowContext, serde_json::Value) -> Result<serde_json::Value, String>;

/// Type-erased async update handler for declarative `#[update]` functions.
///
/// Takes an `Arc<WorkflowContext>` (owned, `'static`) so the returned future
/// can capture the context by value and remain `Send + 'static`. The dispatch
/// wrapper generated by `#[update]` dereferences the Arc to `&WorkflowContext`
/// when calling the user function.
pub type UpdateHandlerFn =
    fn(
        std::sync::Arc<crate::context::WorkflowContext>,
        serde_json::Value,
    ) -> Pin<Box<dyn Future<Output = Result<serde_json::Value, String>> + Send>>;

/// Type-erased synchronous update validator for declarative `#[update]` functions.
///
/// Runs before the update is admitted to history. Returns `Ok(())` to admit or
/// `Err(reason)` to reject without writing any event.
pub type UpdateValidatorFn = fn(&serde_json::Value) -> Result<(), String>;

/// Metadata for a declarative query handler, generated by `#[query(workflow = "…")]`.
///
/// Collected by the `queries![…]` bang macro and registered on
/// [`HarvestBuilder`](crate::builder::HarvestBuilder) via `.queries(…)`.
#[derive(Clone)]
pub struct QueryHandlerInfo {
    /// The query name (the function name), used as the key in the query registry.
    pub name: &'static str,
    /// Workflow name this handler is associated with (value of `workflow = "…"`).
    pub workflow: &'static str,
    /// `module_path!()` at the declaration site.
    pub module: &'static str,
    /// Best-effort Rust type name for the input (e.g., `"StatusRequest"` or `"()"`).
    pub input_type_hint: &'static str,
    /// Best-effort Rust type name for the `Ok` return type (e.g., `"StatusResponse"`).
    pub output_type_hint: &'static str,
    /// Type-erased dispatch function.
    pub handler: QueryHandlerFn,
}

/// Metadata for a declarative update handler, generated by `#[update(workflow = "…")]`.
///
/// Collected by the `updates![…]` bang macro and registered on
/// [`HarvestBuilder`](crate::builder::HarvestBuilder) via `.updates(…)`.
#[derive(Clone)]
pub struct UpdateHandlerInfo {
    /// The update name (the function name), used as the key in the update registry.
    pub name: &'static str,
    /// Workflow name this handler is associated with (value of `workflow = "…"`).
    pub workflow: &'static str,
    /// `module_path!()` at the declaration site.
    pub module: &'static str,
    /// Best-effort Rust type name for the input (e.g., `"ApproveRequest"`).
    pub input_type_hint: &'static str,
    /// Best-effort Rust type name for the `Ok` return type (e.g., `"bool"`).
    pub output_type_hint: &'static str,
    /// Whether a validator was supplied via `validator = path::to::fn`.
    pub has_validator: bool,
    /// Type-erased async dispatch function.
    pub handler: UpdateHandlerFn,
    /// Optional type-erased synchronous validator. `None` when `validator` was omitted.
    pub validator: Option<UpdateValidatorFn>,
}

/// A single violation returned by [`WorkflowInfo::validate_input`].
#[derive(Debug, Clone, serde::Serialize)]
pub struct SchemaViolation {
    /// Human-readable description of what failed.
    pub message: String,
    /// JSON Pointer (RFC 6901) to the field that failed, e.g. `"/name"`.
    /// `None` when the error applies to the root of the document.
    pub field_path: Option<String>,
}

/// Serialisable record returned by `GET /workflows/registered` and
/// `GET /workflows/registered/{name}/schema` (issue #373).
#[derive(Debug, Clone, serde::Serialize)]
pub struct RegisteredWorkflowRecord {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub input_schema: Option<serde_json::Value>,
    pub output_schema: Option<serde_json::Value>,
    pub error_schema: Option<serde_json::Value>,
}

impl RegisteredWorkflowRecord {
    /// Build a record from a `WorkflowInfo`, materialising any schema functions.
    #[must_use]
    pub fn from_info(info: &WorkflowInfo) -> Self {
        Self {
            name: info.name.to_string(),
            description: info.description.map(ToString::to_string),
            input_schema: info.input_schema.map(|f| f()),
            output_schema: info.output_schema.map(|f| f()),
            error_schema: info.error_schema.map(|f| f()),
        }
    }
}

/// Metadata for a registered workflow, generated by `#[workflow]`.
pub struct WorkflowInfo {
    /// Snake-case function name (e.g., `"onboarding_workflow"`).
    pub name: &'static str,
    /// `module_path!()` value from the macro call site.
    pub module: &'static str,
    /// Type-erased dispatch function.
    pub handler: WorkflowHandlerFn,
    /// Default maximum wall-clock lifetime for executions of this workflow type
    /// (issue #243). `None` means no deadline enforced unless overridden at the
    /// `start_workflow` call site. Per-call overrides always win over this default.
    pub execution_timeout: Option<Duration>,
    /// Optional per-key concurrency constraint declared via
    /// `#[workflow(concurrency(key = "input.tenant_id", limit = 10))]`.
    ///
    /// `None` = no per-key cap; only the worker-level semaphore applies.
    pub concurrency: Option<crate::concurrency::ConcurrencyPolicy>,
    /// Per-workflow-type override for the workflow-input size cap (issue #252).
    ///
    /// When set, this raises (never lowers) the global `max_workflow_input_bytes`
    /// configured on [`HarvestBuilder`](crate::builder::HarvestBuilder) for this
    /// specific workflow type. Declared via
    /// `#[workflow(max_input_bytes = "8MiB")]`.
    ///
    /// `None` means the global cap applies.
    pub max_input_bytes: Option<u64>,
    /// Team owner metadata (issue #372).
    pub owner: Option<&'static str>,
    /// Linked runbook URL metadata (issue #372).
    pub runbook_url: Option<&'static str>,
    /// Severity level metadata (issue #372).
    pub severity: Option<&'static str>,
    /// Optional human-readable description of this workflow's purpose.
    ///
    /// Set via `#[workflow(description = "…")]` or the [`with_description`](Self::with_description)
    /// builder method. Surfaced by `GET /workflows/registered` (issue #373).
    pub description: Option<&'static str>,
    /// Optional JSON Schema (as a generator function) describing the workflow's
    /// input type (issue #373). `None` means no schema is published; the start
    /// endpoint accepts any JSON value without validation.
    ///
    /// Set via [`with_input_schema_fn`](Self::with_input_schema_fn) or the
    /// `schema` feature's [`with_schemas`](Self::with_schemas) method.
    pub input_schema: Option<fn() -> serde_json::Value>,
    /// Optional JSON Schema describing the workflow's success output type.
    pub output_schema: Option<fn() -> serde_json::Value>,
    /// Optional JSON Schema describing the workflow's error type.
    pub error_schema: Option<fn() -> serde_json::Value>,
}

impl WorkflowInfo {
    /// Attach a human-readable description to this workflow.
    ///
    /// Fluent builder method — call after the companion function:
    /// ```rust,ignore
    /// .workflows(vec![onboarding_info().with_description("Handles new-user onboarding")])
    /// ```
    #[must_use]
    pub const fn with_description(mut self, desc: &'static str) -> Self {
        self.description = Some(desc);
        self
    }

    /// Attach a raw input-schema generator function.
    ///
    /// The function is called once per request to `GET /workflows/registered`
    /// and `GET /workflows/registered/{name}/schema`, and once per
    /// `POST /workflows/{name}/start` for input validation.
    #[must_use]
    pub const fn with_input_schema_fn(mut self, f: fn() -> serde_json::Value) -> Self {
        self.input_schema = Some(f);
        self
    }

    /// Attach a raw output-schema generator function.
    #[must_use]
    pub const fn with_output_schema_fn(mut self, f: fn() -> serde_json::Value) -> Self {
        self.output_schema = Some(f);
        self
    }

    /// Attach a raw error-schema generator function.
    #[must_use]
    pub const fn with_error_schema_fn(mut self, f: fn() -> serde_json::Value) -> Self {
        self.error_schema = Some(f);
        self
    }

    /// Validate a JSON value against this workflow's `input_schema` (if any).
    ///
    /// Returns `Ok(())` when:
    /// - no `input_schema` is set (opt-in: workflows without a schema are unconstrained), or
    /// - the input passes all schema constraints.
    ///
    /// Returns `Err(violations)` with at least one [`SchemaViolation`] when the
    /// input violates the schema. The `field_path` is a JSON Pointer (RFC 6901)
    /// to the offending field.
    ///
    /// Used by `POST /api/harvest/workflows/{name}/start` to reject bad inputs
    /// before they reach the worker (issue #373).
    ///
    /// # Errors
    ///
    /// Returns `Err(Vec<SchemaViolation>)` when the input fails schema validation.
    pub fn validate_input(&self, input: &serde_json::Value) -> Result<(), Vec<SchemaViolation>> {
        let Some(schema_fn) = self.input_schema else {
            return Ok(());
        };
        let schema = schema_fn();
        validate_against_schema(&schema, input)
    }

    /// Convenience method (enabled with the `schema` feature) that attaches
    /// JSON Schemas for `I` and `O` using [`schemars`].
    ///
    /// The error schema is always published as `{"type": "string"}` because the
    /// workflow runtime stringifies every `Err(e)` value before recording it in
    /// `WorkflowFailed`. Publishing the structured schema of `E` would mislead
    /// discovery clients into expecting a payload that can never be returned.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// use autumn_harvest::prelude::*;
    /// use schemars::JsonSchema;
    ///
    /// #[derive(serde::Deserialize, serde::Serialize, JsonSchema)]
    /// struct OnboardInput { user_id: i64 }
    ///
    /// #[workflow(description = "New-user onboarding flow")]
    /// async fn onboarding(ctx: &WorkflowContext, input: OnboardInput) -> Result<(), String> {
    ///     Ok(())
    /// }
    ///
    /// // In the builder:
    /// .workflows(vec![
    ///     onboarding_info().with_schemas::<OnboardInput, ()>(),
    /// ])
    /// ```
    #[cfg(feature = "schema")]
    #[must_use]
    pub fn with_schemas<I, O>(self) -> Self
    where
        I: schemars::JsonSchema,
        O: schemars::JsonSchema,
    {
        fn schema_for<T: schemars::JsonSchema>() -> serde_json::Value {
            serde_json::to_value(schemars::schema_for!(T)).unwrap_or_default()
        }
        fn string_schema() -> serde_json::Value {
            serde_json::json!({"type": "string"})
        }
        self.with_input_schema_fn(schema_for::<I>)
            .with_output_schema_fn(schema_for::<O>)
            .with_error_schema_fn(string_schema)
    }
}

/// Validate `input` against a JSON Schema value.
///
/// Returns `Ok(())` on success or `Err(Vec<SchemaViolation>)` with at least one
/// entry on failure. Uses a simple structural walker so the core crate has no
/// mandatory dependency on a JSON Schema validator library.
///
/// # Errors
///
/// Returns `Err(Vec<SchemaViolation>)` when `input` violates the schema.
pub fn validate_against_schema(
    schema: &serde_json::Value,
    input: &serde_json::Value,
) -> Result<(), Vec<SchemaViolation>> {
    let mut violations: Vec<SchemaViolation> = Vec::new();
    validate_node(schema, schema, input, "", &mut violations);
    if violations.is_empty() {
        Ok(())
    } else {
        Err(violations)
    }
}

/// Recursive schema walker — validates `value` against `schema` at path `ptr`.
///
/// `root` is the top-level schema document, used to resolve `$ref` pointers.
#[allow(clippy::too_many_lines)]
fn validate_node(
    root: &serde_json::Value,
    schema: &serde_json::Value,
    value: &serde_json::Value,
    ptr: &str,
    out: &mut Vec<SchemaViolation>,
) {
    // Resolve $ref (local JSON Pointer only, e.g. "#/definitions/Foo").
    let mut schema = schema;
    let mut visited = std::collections::HashSet::new();
    while let Some(ref_str) = schema.get("$ref").and_then(|v| v.as_str()) {
        if !visited.insert(ref_str) {
            break; // cycle guard
        }
        if let Some(stripped) = ref_str.strip_prefix('#') {
            if let Some(resolved) = root.pointer(stripped) {
                schema = resolved;
            } else {
                break;
            }
        } else {
            break; // external refs not supported — skip
        }
    }

    let Some(schema_obj) = schema.as_object() else {
        return;
    };

    // field_path helper: returns None for the root, Some(ptr) otherwise.
    let path = || {
        if ptr.is_empty() {
            None
        } else {
            Some(ptr.to_string())
        }
    };

    // type check — handles both scalar "type": "string" and multi-type "type": ["string","null"]
    if let Some(type_node) = schema_obj.get("type") {
        let type_ok = type_node.as_str().map_or_else(
            || {
                type_node.as_array().is_none_or(|arr| {
                    arr.iter()
                        .filter_map(|v| v.as_str())
                        .any(|t| type_matches(t, value))
                })
            },
            |single| type_matches(single, value),
        );
        if !type_ok {
            let expected = type_node.to_string();
            out.push(SchemaViolation {
                message: format!("expected type {expected}, got '{}'", json_type_name(value)),
                field_path: path(),
            });
            return;
        }
    }

    // required fields
    if let (Some(required), Some(obj)) = (
        schema_obj.get("required").and_then(|v| v.as_array()),
        value.as_object(),
    ) {
        for req in required {
            if let Some(field) = req.as_str()
                && !obj.contains_key(field)
            {
                // Escape field name per RFC 6901: ~ → ~0, / → ~1.
                let escaped = field.replace('~', "~0").replace('/', "~1");
                out.push(SchemaViolation {
                    message: format!("missing required field '{field}'"),
                    field_path: Some(format!("{ptr}/{escaped}")),
                });
            }
        }
    }

    // properties — recurse
    if let (Some(properties), Some(obj)) = (
        schema_obj.get("properties").and_then(|v| v.as_object()),
        value.as_object(),
    ) {
        for (prop_name, prop_schema) in properties {
            if let Some(prop_value) = obj.get(prop_name) {
                // Escape property name per RFC 6901: ~ → ~0, / → ~1.
                let escaped_name = prop_name.replace('~', "~0").replace('/', "~1");
                let child_ptr = format!("{ptr}/{escaped_name}");
                validate_node(root, prop_schema, prop_value, &child_ptr, out);
            }
        }
    }

    // enum check
    if let Some(enum_vals) = schema_obj.get("enum").and_then(|v| v.as_array())
        && !enum_vals.contains(value)
    {
        out.push(SchemaViolation {
            message: "value is not one of the allowed enum values".to_string(),
            field_path: path(),
        });
    }

    // array items — recurse into each element
    if let (Some(items_schema), Some(arr)) = (schema_obj.get("items"), value.as_array()) {
        for (i, elem) in arr.iter().enumerate() {
            let child_ptr = format!("{ptr}/{i}");
            validate_node(root, items_schema, elem, &child_ptr, out);
        }
    }

    // minLength / maxLength for strings
    if let Some(s) = value.as_str() {
        let char_count = s.chars().count() as u64;
        if let Some(min) = schema_obj
            .get("minLength")
            .and_then(serde_json::Value::as_u64)
            && char_count < min
        {
            out.push(SchemaViolation {
                message: format!("string is shorter than minLength {min}"),
                field_path: path(),
            });
        }
        if let Some(max) = schema_obj
            .get("maxLength")
            .and_then(serde_json::Value::as_u64)
            && char_count > max
        {
            out.push(SchemaViolation {
                message: format!("string is longer than maxLength {max}"),
                field_path: path(),
            });
        }
    }

    // minimum / maximum for numbers
    if let Some(n) = value.as_f64() {
        if let Some(min) = schema_obj
            .get("minimum")
            .and_then(serde_json::Value::as_f64)
            && n < min
        {
            out.push(SchemaViolation {
                message: format!("value {n} is less than minimum {min}"),
                field_path: path(),
            });
        }
        if let Some(max) = schema_obj
            .get("maximum")
            .and_then(serde_json::Value::as_f64)
            && n > max
        {
            out.push(SchemaViolation {
                message: format!("value {n} is greater than maximum {max}"),
                field_path: path(),
            });
        }
    }

    // additionalProperties — reject unknown keys (false) or validate them against a sub-schema
    if let (Some(add_props), Some(obj)) =
        (schema_obj.get("additionalProperties"), value.as_object())
    {
        let known_keys: std::collections::HashSet<&str> = schema_obj
            .get("properties")
            .and_then(|v| v.as_object())
            .map(|props| props.keys().map(String::as_str).collect())
            .unwrap_or_default();
        if add_props.as_bool() == Some(false) {
            // boolean false: any unknown key is forbidden
            for key in obj.keys() {
                if !known_keys.contains(key.as_str()) {
                    let escaped = key.replace('~', "~0").replace('/', "~1");
                    out.push(SchemaViolation {
                        message: format!("additional property '{key}' is not allowed"),
                        field_path: Some(format!("{ptr}/{escaped}")),
                    });
                }
            }
        } else if add_props.is_object() {
            // schema object: validate each additional (non-properties) key against it
            for (key, val) in obj {
                if !known_keys.contains(key.as_str()) {
                    let escaped = key.replace('~', "~0").replace('/', "~1");
                    let child_ptr = format!("{ptr}/{escaped}");
                    validate_node(root, add_props, val, &child_ptr, out);
                }
            }
        }
    }

    // allOf — value must satisfy every sub-schema
    if let Some(all_of) = schema_obj.get("allOf").and_then(|v| v.as_array()) {
        for sub_schema in all_of {
            let mut sub_violations = Vec::new();
            validate_node(root, sub_schema, value, ptr, &mut sub_violations);
            out.extend(sub_violations);
        }
    }

    // anyOf — value must satisfy at least one sub-schema
    if let Some(any_of) = schema_obj.get("anyOf").and_then(|v| v.as_array()) {
        let satisfied = any_of.iter().any(|sub_schema| {
            let mut sub_violations = Vec::new();
            validate_node(root, sub_schema, value, ptr, &mut sub_violations);
            sub_violations.is_empty()
        });
        if !satisfied {
            out.push(SchemaViolation {
                message: "value does not match any of the allowed schemas (anyOf)".to_string(),
                field_path: path(),
            });
        }
    }

    // oneOf — value must satisfy exactly one sub-schema
    if let Some(one_of) = schema_obj.get("oneOf").and_then(|v| v.as_array()) {
        let matched = one_of
            .iter()
            .filter(|sub_schema| {
                let mut sub_violations = Vec::new();
                validate_node(root, sub_schema, value, ptr, &mut sub_violations);
                sub_violations.is_empty()
            })
            .count();
        if matched != 1 {
            out.push(SchemaViolation {
                message: format!(
                    "value matches {matched} of the allowed schemas (oneOf requires exactly 1)"
                ),
                field_path: path(),
            });
        }
    }
}

fn type_matches(expected_type: &str, value: &serde_json::Value) -> bool {
    match expected_type {
        "object" => value.is_object(),
        "array" => value.is_array(),
        "string" => value.is_string(),
        "number" => value.is_number(),
        // JSON Schema "integer": must be a number with no fractional part.
        "integer" => {
            value.as_i64().is_some()
                || value.as_u64().is_some()
                || value.as_f64().is_some_and(|f| f.fract() == 0.0)
        }
        "boolean" => value.is_boolean(),
        "null" => value.is_null(),
        _ => true,
    }
}

#[allow(clippy::missing_const_for_fn)]
fn json_type_name(v: &serde_json::Value) -> &'static str {
    match v {
        serde_json::Value::Null => "null",
        serde_json::Value::Bool(_) => "boolean",
        serde_json::Value::Number(_) => "number",
        serde_json::Value::String(_) => "string",
        serde_json::Value::Array(_) => "array",
        serde_json::Value::Object(_) => "object",
    }
}

/// Metadata for a registered activity, generated by `#[activity]`.
pub struct ActivityInfo {
    /// Snake-case function name.
    pub name: &'static str,
    /// `module_path!()` value from the macro call site.
    pub module: &'static str,
    /// Default retry policy (overridable at call site).
    pub default_retry_policy: Option<RetryPolicy>,
    /// Default start-to-close timeout.
    pub default_start_to_close: Option<Duration>,
    /// Default heartbeat timeout (`None` = disabled).
    pub default_heartbeat_timeout: Option<Duration>,
    /// Default schedule-to-start timeout.
    pub default_schedule_to_start: Option<Duration>,
    /// Default task queue name (`None` = `"default"`).
    pub default_queue: Option<&'static str>,
    /// Cluster-wide concurrency cap. `None` = no cap (only the worker-level
    /// `max_concurrent_activities` semaphore applies).
    pub max_concurrent: Option<u32>,
    /// Concurrency group key. Multiple activities sharing a key share the
    /// `max_concurrent` budget. Defaults to the activity's own name when
    /// `max_concurrent` is set and `concurrency_key` is not specified.
    pub concurrency_key: Option<&'static str>,
    /// When `true`, the worker runs this activity inline on the workflow task
    /// (never enqueued). Local activities must not set `heartbeat_timeout`,
    /// `schedule_to_start`, or `queue` — the macro enforces this at compile time.
    pub is_local: bool,
    /// Per-activity override for the activity-input size cap (issue #252).
    ///
    /// When set, this raises (never lowers) the global `max_activity_input_bytes`
    /// for this specific activity. Declared via
    /// `#[activity(max_input_bytes = "8MiB")]`.
    ///
    /// `None` means the global cap applies.
    pub max_input_bytes: Option<u64>,
    /// Per-activity override for the activity-result size cap (issue #252).
    ///
    /// When set, this raises (never lowers) the global `max_activity_result_bytes`
    /// for this specific activity. Declared via
    /// `#[activity(max_result_bytes = "8MiB")]`.
    ///
    /// `None` means the global cap applies.
    pub max_result_bytes: Option<u64>,
    /// Cluster-wide rate limit (requests per second). `None` = no rate limit.
    pub rate_limit_rps: Option<f64>,
    /// Cluster-wide rate limit burst capacity (tokens). `None` = no burst capability or equal to `rate_limit_rps`.
    pub rate_limit_burst: Option<f64>,
    /// Rate limit bucket key. Multiple activities sharing a key share the
    /// rate limit. Defaults to the activity's own name when rate limits are set.
    pub rate_limit_key: Option<&'static str>,
    /// Optional circuit-breaker policy (issue #369). When set, the worker
    /// fast-fails dispatches of this activity with a non-retryable
    /// `"CircuitOpen"` failure while the breaker is open. `None` retains
    /// today's behaviour (no breaker; the full retry policy applies). Declared
    /// via `#[activity(circuit_breaker = CircuitBreakerPolicy::new(...))]`.
    pub circuit_breaker: Option<crate::policy::CircuitBreakerPolicy>,
    /// Type-erased dispatch function.
    pub handler: ActivityHandlerFn,
}

/// Metadata for a registered DAG, generated by `#[dag]`.
pub struct DagInfo {
    /// Snake-case function name.
    pub name: &'static str,
    /// `module_path!()` value from the macro call site.
    pub module: &'static str,
    /// Optional schedule for automatic runs.
    pub schedule: Option<Schedule>,
    /// Whether the scheduler should backfill missed intervals.
    pub catchup: bool,
    /// Maximum number of active runs allowed at once.
    pub max_active_runs: u32,
    /// Default queue applied to tasks that do not override their queue.
    pub default_queue: Option<&'static str>,
    /// Builder function that populates a [`DagBuilder`].
    pub builder: fn(&mut DagBuilder),
    /// Lowered workflow handler, populated when the `unified-dag-execution`
    /// feature is enabled (issue #256 Step 1).
    ///
    /// `None` on the classic DAG execution path; `Some` when the feature is
    /// on so the runtime can route new DAG runs through `WorkflowInfo`
    /// without needing to look up the companion by name.
    pub workflow_handler: Option<WorkflowHandlerFn>,
    /// Maximum spread window for staggering schedule fires. `Duration::ZERO`
    /// disables jitter (default — today's behaviour).
    pub jitter: Duration,
    /// What to do when a new firing collides with a still-running execution.
    /// Defaults to [`OverlapPolicy::Skip`].
    pub overlap_policy: crate::policy::OverlapPolicy,
    /// Maximum buffered slots under [`OverlapPolicy::BufferAll`]. Default 100.
    pub buffer_all_max: u32,
    /// Team owner metadata (issue #372).
    pub owner: Option<&'static str>,
    /// Linked runbook URL metadata (issue #372).
    pub runbook_url: Option<&'static str>,
    /// Severity level metadata (issue #372).
    pub severity: Option<&'static str>,
}

impl DagInfo {
    /// Build an immutable DAG definition from this metadata.
    ///
    /// # Errors
    ///
    /// Returns [`DagBuildError`] if the builder creates an invalid graph.
    pub fn build_definition(&self) -> Result<DagDefinition, DagBuildError> {
        let mut dag = self
            .default_queue
            .map_or_else(DagBuilder::new, DagBuilder::with_default_queue);
        (self.builder)(&mut dag);
        dag.build()
    }

    /// Return a [`WorkflowSchedule`] that fires this DAG on its declared cron
    /// or interval via the unified workflow execution path (issue #256 Step 2).
    ///
    /// Returns `None` when either:
    /// - `workflow_handler` is `None` (unified-dag-execution feature is off), or
    /// - `schedule` is `None` (DAG has no automatic trigger).
    #[must_use]
    pub fn as_workflow_schedule(&self) -> Option<WorkflowSchedule> {
        self.workflow_handler?;
        let schedule = self.schedule.clone()?;
        Some(WorkflowSchedule {
            workflow_name: self.name.to_string(),
            dag_name: Some(self.name.to_string()),
            schedule,
            input: serde_json::Value::Null,
            catchup: self.catchup,
            max_active_runs: self.max_active_runs,
            paused: false,
            queue_name: self.default_queue.unwrap_or("default").to_string(),
            jitter: self.jitter,
            overlap_policy: self.overlap_policy,
            buffer_all_max: self.buffer_all_max,
            execution_timeout: None,
            calendar: None,
            skip_policy: crate::policy::SkipPolicy::Skip,
            consecutive_failure_limit: None,
        })
    }

    /// Return a [`WorkflowInfo`] that executes this DAG via the unified
    /// workflow execution path (issue #256 Step 1).
    ///
    /// Returns `None` when the `unified-dag-execution` feature is disabled and
    /// `workflow_handler` was not populated by the macro.
    #[must_use]
    pub fn as_workflow_info(&self) -> Option<WorkflowInfo> {
        self.workflow_handler.map(|handler| WorkflowInfo {
            name: self.name,
            module: self.module,
            handler,
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: self.owner,
            runbook_url: self.runbook_url,
            severity: self.severity,
            description: None,
            input_schema: None,
            output_schema: None,
            error_schema: None,
        })
    }
}

impl std::fmt::Debug for WorkflowInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WorkflowInfo")
            .field("name", &self.name)
            .field("module", &self.module)
            .field("handler", &"<fn>")
            .field("execution_timeout", &self.execution_timeout)
            .field("concurrency", &self.concurrency)
            .field("max_input_bytes", &self.max_input_bytes)
            .field("owner", &self.owner)
            .field("runbook_url", &self.runbook_url)
            .field("severity", &self.severity)
            .field("description", &self.description)
            .field("input_schema", &self.input_schema.map(|_| "<fn>"))
            .field("output_schema", &self.output_schema.map(|_| "<fn>"))
            .field("error_schema", &self.error_schema.map(|_| "<fn>"))
            .finish()
    }
}

impl std::fmt::Debug for ActivityInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ActivityInfo")
            .field("name", &self.name)
            .field("module", &self.module)
            .field("default_retry_policy", &self.default_retry_policy)
            .field("default_start_to_close", &self.default_start_to_close)
            .field("default_heartbeat_timeout", &self.default_heartbeat_timeout)
            .field("default_schedule_to_start", &self.default_schedule_to_start)
            .field("default_queue", &self.default_queue)
            .field("max_concurrent", &self.max_concurrent)
            .field("concurrency_key", &self.concurrency_key)
            .field("is_local", &self.is_local)
            .field("max_input_bytes", &self.max_input_bytes)
            .field("max_result_bytes", &self.max_result_bytes)
            .field("rate_limit_rps", &self.rate_limit_rps)
            .field("rate_limit_burst", &self.rate_limit_burst)
            .field("rate_limit_key", &self.rate_limit_key)
            .field("circuit_breaker", &self.circuit_breaker)
            .field("handler", &"<fn>")
            .finish()
    }
}

impl std::fmt::Debug for DagInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DagInfo")
            .field("name", &self.name)
            .field("module", &self.module)
            .field("schedule", &self.schedule)
            .field("catchup", &self.catchup)
            .field("max_active_runs", &self.max_active_runs)
            .field("default_queue", &self.default_queue)
            .field("builder", &"<fn>")
            .field("workflow_handler", &self.workflow_handler.map(|_| "<fn>"))
            .field("jitter", &self.jitter)
            .field("overlap_policy", &self.overlap_policy)
            .field("buffer_all_max", &self.buffer_all_max)
            .field("owner", &self.owner)
            .field("runbook_url", &self.runbook_url)
            .field("severity", &self.severity)
            .finish()
    }
}

impl std::fmt::Debug for QueryHandlerInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("QueryHandlerInfo")
            .field("name", &self.name)
            .field("workflow", &self.workflow)
            .field("module", &self.module)
            .field("input_type_hint", &self.input_type_hint)
            .field("output_type_hint", &self.output_type_hint)
            .field("handler", &"<fn>")
            .finish()
    }
}

impl std::fmt::Debug for UpdateHandlerInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UpdateHandlerInfo")
            .field("name", &self.name)
            .field("workflow", &self.workflow)
            .field("module", &self.module)
            .field("input_type_hint", &self.input_type_hint)
            .field("output_type_hint", &self.output_type_hint)
            .field("has_validator", &self.has_validator)
            .field("handler", &"<fn>")
            .field("validator", &self.validator.map(|_| "<fn>"))
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::TriggerRule;

    #[test]
    fn workflow_info_fields_accessible() {
        let info = WorkflowInfo {
            name: "test_workflow",
            module: "my_app::workflows",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: None,
            input_schema: None,
            output_schema: None,
            error_schema: None,
        };
        assert_eq!(info.name, "test_workflow");
        assert!(info.execution_timeout.is_none());
        assert!(info.concurrency.is_none());
    }

    #[test]
    fn workflow_info_execution_timeout_field_is_accessible() {
        let info = WorkflowInfo {
            name: "billing_reconciliation",
            module: "my_app::workflows",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: Some(std::time::Duration::from_secs(86_400)),
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: None,
            input_schema: None,
            output_schema: None,
            error_schema: None,
        };
        assert_eq!(
            info.execution_timeout,
            Some(std::time::Duration::from_secs(86_400))
        );
    }

    // --- issue #373: schema opt-in ---

    #[test]
    fn workflow_info_description_field_accessible() {
        let info = WorkflowInfo {
            name: "schema_test",
            module: "tests",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: Some("Handles user onboarding from signup to first action"),
            input_schema: None,
            output_schema: None,
            error_schema: None,
        };
        assert_eq!(
            info.description,
            Some("Handles user onboarding from signup to first action")
        );
    }

    #[test]
    fn workflow_info_with_description_builder() {
        let base = WorkflowInfo {
            name: "schema_test",
            module: "tests",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: None,
            input_schema: None,
            output_schema: None,
            error_schema: None,
        };
        let info = base.with_description("Processes batch payments");
        assert_eq!(info.description, Some("Processes batch payments"));
    }

    #[test]
    fn workflow_info_schema_fn_roundtrip() {
        fn input_schema_fn() -> serde_json::Value {
            serde_json::json!({
                "type": "object",
                "properties": {
                    "user_id": {"type": "integer"},
                    "email": {"type": "string"}
                },
                "required": ["user_id"]
            })
        }

        fn output_schema_fn() -> serde_json::Value {
            serde_json::json!({"type": "null"})
        }

        fn error_schema_fn() -> serde_json::Value {
            serde_json::json!({"type": "string"})
        }

        let info = WorkflowInfo {
            name: "schema_test",
            module: "tests",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: None,
            input_schema: None,
            output_schema: None,
            error_schema: None,
        }
        .with_input_schema_fn(input_schema_fn)
        .with_output_schema_fn(output_schema_fn)
        .with_error_schema_fn(error_schema_fn);

        let s = (info.input_schema.unwrap())();
        assert_eq!(s["type"], "object");
        assert!(s["properties"]["user_id"].is_object());

        let s = (info.output_schema.unwrap())();
        assert_eq!(s["type"], "null");

        let s = (info.error_schema.unwrap())();
        assert_eq!(s["type"], "string");
    }

    #[test]
    fn registered_workflow_record_serialises_nulls_when_no_schema() {
        let info = WorkflowInfo {
            name: "no_schema_wf",
            module: "tests",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: None,
            input_schema: None,
            output_schema: None,
            error_schema: None,
        };
        let record = RegisteredWorkflowRecord::from_info(&info);
        let json = serde_json::to_value(&record).unwrap();
        assert_eq!(json["name"], "no_schema_wf");
        assert!(json["description"].is_null());
        assert!(json["input_schema"].is_null());
        assert!(json["output_schema"].is_null());
        assert!(json["error_schema"].is_null());
    }

    #[test]
    fn registered_workflow_record_includes_schema_when_present() {
        fn my_schema() -> serde_json::Value {
            serde_json::json!({"type": "object"})
        }
        let info = WorkflowInfo {
            name: "schema_wf",
            module: "tests",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: Some("A workflow with a schema"),
            input_schema: Some(my_schema),
            output_schema: None,
            error_schema: None,
        };
        let record = RegisteredWorkflowRecord::from_info(&info);
        assert_eq!(record.name, "schema_wf");
        assert_eq!(
            record.description.as_deref(),
            Some("A workflow with a schema")
        );
        assert!(record.input_schema.is_some());
        assert_eq!(record.input_schema.unwrap()["type"], "object");
        assert!(record.output_schema.is_none());
    }

    #[test]
    fn validate_input_against_schema_returns_ok_for_valid() {
        fn schema_fn() -> serde_json::Value {
            serde_json::json!({
                "type": "object",
                "properties": {
                    "name": {"type": "string"}
                },
                "required": ["name"]
            })
        }
        let info = WorkflowInfo {
            name: "validated_wf",
            module: "tests",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: None,
            input_schema: Some(schema_fn),
            output_schema: None,
            error_schema: None,
        };
        let valid_input = serde_json::json!({"name": "Alice"});
        assert!(info.validate_input(&valid_input).is_ok());
    }

    #[test]
    fn validate_input_against_schema_returns_err_for_invalid() {
        fn schema_fn() -> serde_json::Value {
            serde_json::json!({
                "type": "object",
                "properties": {
                    "name": {"type": "string"}
                },
                "required": ["name"]
            })
        }
        let info = WorkflowInfo {
            name: "validated_wf",
            module: "tests",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: None,
            input_schema: Some(schema_fn),
            output_schema: None,
            error_schema: None,
        };
        // Missing required "name" field
        let invalid_input = serde_json::json!({"other": "field"});
        let err = info.validate_input(&invalid_input);
        assert!(err.is_err());
        let violations = err.unwrap_err();
        assert!(!violations.is_empty());
    }

    #[test]
    fn validate_input_returns_ok_when_no_schema() {
        let info = WorkflowInfo {
            name: "no_schema_wf",
            module: "tests",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: None,
            input_schema: None,
            output_schema: None,
            error_schema: None,
        };
        // Any input passes when no schema is defined
        let any_input = serde_json::json!({"anything": true});
        assert!(info.validate_input(&any_input).is_ok());
    }

    #[test]
    fn activity_info_default_policy() {
        let info = ActivityInfo {
            name: "test_activity",
            module: "my_app::activities",
            default_retry_policy: None,
            default_start_to_close: None,
            default_heartbeat_timeout: None,
            default_schedule_to_start: None,
            default_queue: None,
            max_concurrent: None,
            concurrency_key: None,
            is_local: false,
            max_input_bytes: None,
            max_result_bytes: None,
            rate_limit_rps: None,
            rate_limit_burst: None,
            rate_limit_key: None,
            circuit_breaker: None,
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        assert!(info.default_retry_policy.is_none());
        assert_eq!(info.default_queue, None);
        assert!(info.max_concurrent.is_none());
        assert!(info.concurrency_key.is_none());
        assert!(!info.is_local);
    }

    #[test]
    fn activity_info_is_local_true() {
        let info = ActivityInfo {
            name: "compute_hash",
            module: "my_app::activities",
            default_retry_policy: None,
            default_start_to_close: Some(std::time::Duration::from_secs(10)),
            default_heartbeat_timeout: None,
            default_schedule_to_start: None,
            default_queue: None,
            max_concurrent: None,
            concurrency_key: None,
            is_local: true,
            max_input_bytes: None,
            max_result_bytes: None,
            rate_limit_rps: None,
            rate_limit_burst: None,
            rate_limit_key: None,
            circuit_breaker: None,
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        assert!(info.is_local);
        assert!(
            info.default_heartbeat_timeout.is_none(),
            "local activities must not have heartbeat_timeout"
        );
        assert!(
            info.default_schedule_to_start.is_none(),
            "local activities must not have schedule_to_start"
        );
        assert!(
            info.default_queue.is_none(),
            "local activities must not have a queue"
        );
    }

    #[test]
    fn activity_info_concurrency_fields() {
        let info = ActivityInfo {
            name: "send_email",
            module: "my_app::activities",
            default_retry_policy: None,
            default_start_to_close: None,
            default_heartbeat_timeout: None,
            default_schedule_to_start: None,
            default_queue: None,
            max_concurrent: Some(5),
            concurrency_key: Some("email"),
            is_local: false,
            max_input_bytes: None,
            max_result_bytes: None,
            rate_limit_rps: None,
            rate_limit_burst: None,
            rate_limit_key: None,
            circuit_breaker: None,
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        assert_eq!(info.max_concurrent, Some(5));
        assert_eq!(info.concurrency_key, Some("email"));
    }

    #[test]
    fn dag_info_builds_definition() {
        fn extract_users() {}
        fn load_users() {}

        fn build(dag: &mut DagBuilder) {
            let first = dag.activity(extract_users);
            let _second = dag.activity(load_users).upstream(&first);
        }

        let info = DagInfo {
            name: "daily_etl",
            module: "tests",
            schedule: Some(Schedule::Manual),
            catchup: false,
            max_active_runs: 1,
            default_queue: Some("etl-workers"),
            builder: build,
            workflow_handler: None,
            jitter: ::std::time::Duration::ZERO,
            overlap_policy: crate::policy::OverlapPolicy::Skip,
            buffer_all_max: 100,
            owner: None,
            runbook_url: None,
            severity: None,
        };

        let definition = info.build_definition().expect("dag should compile");
        assert_eq!(definition.tasks().len(), 2);
        assert_eq!(definition.execution_levels().len(), 2);
        assert_eq!(definition.tasks()[0].queue.as_deref(), Some("etl-workers"));
        assert_eq!(definition.tasks()[1].trigger_rule, TriggerRule::AllSuccess);

        assert!(
            info.as_workflow_info().is_none(),
            "as_workflow_info should return None when workflow_handler is None"
        );
    }
    #[test]
    fn info_debug_formats_correctly() {
        let workflow_info = WorkflowInfo {
            name: "test_wf",
            module: "test_mod",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
            concurrency: None,
            max_input_bytes: None,
            owner: None,
            runbook_url: None,
            severity: None,
            description: None,
            input_schema: None,
            output_schema: None,
            error_schema: None,
        };
        let debug_str = format!("{workflow_info:?}");
        assert!(debug_str.contains("WorkflowInfo"));
        assert!(debug_str.contains("test_wf"));

        let activity_info = ActivityInfo {
            name: "test_act",
            module: "test_mod",
            default_retry_policy: None,
            default_start_to_close: None,
            default_heartbeat_timeout: None,
            default_schedule_to_start: None,
            default_queue: None,
            max_concurrent: None,
            concurrency_key: None,
            is_local: false,
            max_input_bytes: None,
            max_result_bytes: None,
            rate_limit_rps: None,
            rate_limit_burst: None,
            rate_limit_key: None,
            circuit_breaker: None,
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        let debug_str = format!("{activity_info:?}");
        assert!(debug_str.contains("ActivityInfo"));
        assert!(debug_str.contains("test_act"));

        let dag_info = DagInfo {
            name: "test_dag",
            module: "test_mod",
            schedule: None,
            catchup: false,
            max_active_runs: 1,
            default_queue: None,
            builder: |_| {},
            workflow_handler: None,
            jitter: ::std::time::Duration::ZERO,
            overlap_policy: crate::policy::OverlapPolicy::Skip,
            buffer_all_max: 100,
            owner: None,
            runbook_url: None,
            severity: None,
        };
        let debug_str = format!("{dag_info:?}");
        assert!(debug_str.contains("DagInfo"));
        assert!(debug_str.contains("test_dag"));
    }
}
