//! Registration types returned by macro-generated companion functions.
//!
//! `#[workflow]` generates `__autumn_workflow_info_*() -> WorkflowInfo`.
//! `#[activity]` generates `__autumn_activity_info_*() -> ActivityInfo`.
//! `#[query]` generates `__autumn_query_handler_info_*() -> QueryHandlerInfo`.
//! `#[update]` generates `__autumn_update_handler_info_*() -> UpdateHandlerInfo`.
//! These are collected by `workflows![]`, `activities![]`, `queries![]`, `updates![]`.

use std::future::Future;
use std::pin::Pin;
use std::time::Duration;

use crate::dag::{DagBuildError, DagBuilder, DagDefinition};
use crate::policy::{RetryPolicy, Schedule, WorkflowSchedule};

/// Type-erased workflow handler.
///
/// Takes a `WorkflowContext` reference and serialized JSON input;
/// returns serialized JSON output (or an error string).
///
/// The macro wraps the user's typed function to handle
/// serialization/deserialization at the boundary.
pub type WorkflowHandlerFn =
    fn(
        &crate::context::WorkflowContext,
        serde_json::Value,
    ) -> Pin<Box<dyn Future<Output = Result<serde_json::Value, String>> + Send + '_>>;

/// Type-erased activity handler.
pub type ActivityHandlerFn =
    fn(
        &crate::context::ActivityContext,
        serde_json::Value,
    ) -> Pin<Box<dyn Future<Output = Result<serde_json::Value, String>> + Send + '_>>;

/// Type-erased synchronous query handler for declarative `#[query]` functions.
///
/// Takes a `WorkflowContext` reference for shared-state access and the
/// serialised JSON input; returns serialised JSON output or an error string.
/// Query handlers are synchronous — they inspect state without performing I/O.
pub type QueryHandlerFn =
    fn(&crate::context::WorkflowContext, serde_json::Value) -> Result<serde_json::Value, String>;

/// Type-erased async update handler for declarative `#[update]` functions.
///
/// Takes an `Arc<WorkflowContext>` (owned, `'static`) so the returned future
/// can capture the context by value and remain `Send + 'static`. The dispatch
/// wrapper generated by `#[update]` dereferences the Arc to `&WorkflowContext`
/// when calling the user function.
pub type UpdateHandlerFn =
    fn(
        std::sync::Arc<crate::context::WorkflowContext>,
        serde_json::Value,
    ) -> Pin<Box<dyn Future<Output = Result<serde_json::Value, String>> + Send>>;

/// Type-erased synchronous update validator for declarative `#[update]` functions.
///
/// Runs before the update is admitted to history. Returns `Ok(())` to admit or
/// `Err(reason)` to reject without writing any event.
pub type UpdateValidatorFn = fn(&serde_json::Value) -> Result<(), String>;

/// Metadata for a declarative query handler, generated by `#[query(workflow = "…")]`.
///
/// Collected by the `queries![…]` bang macro and registered on
/// [`HarvestBuilder`](crate::builder::HarvestBuilder) via `.queries(…)`.
pub struct QueryHandlerInfo {
    /// The query name (the function name), used as the key in the query registry.
    pub name: &'static str,
    /// Workflow name this handler is associated with (value of `workflow = "…"`).
    pub workflow: &'static str,
    /// `module_path!()` at the declaration site.
    pub module: &'static str,
    /// Best-effort Rust type name for the input (e.g., `"StatusRequest"` or `"()"`).
    pub input_type_hint: &'static str,
    /// Best-effort Rust type name for the `Ok` return type (e.g., `"StatusResponse"`).
    pub output_type_hint: &'static str,
    /// Type-erased dispatch function.
    pub handler: QueryHandlerFn,
}

/// Metadata for a declarative update handler, generated by `#[update(workflow = "…")]`.
///
/// Collected by the `updates![…]` bang macro and registered on
/// [`HarvestBuilder`](crate::builder::HarvestBuilder) via `.updates(…)`.
pub struct UpdateHandlerInfo {
    /// The update name (the function name), used as the key in the update registry.
    pub name: &'static str,
    /// Workflow name this handler is associated with (value of `workflow = "…"`).
    pub workflow: &'static str,
    /// `module_path!()` at the declaration site.
    pub module: &'static str,
    /// Best-effort Rust type name for the input (e.g., `"ApproveRequest"`).
    pub input_type_hint: &'static str,
    /// Best-effort Rust type name for the `Ok` return type (e.g., `"bool"`).
    pub output_type_hint: &'static str,
    /// Whether a validator was supplied via `validator = path::to::fn`.
    pub has_validator: bool,
    /// Type-erased async dispatch function.
    pub handler: UpdateHandlerFn,
    /// Optional type-erased synchronous validator. `None` when `validator` was omitted.
    pub validator: Option<UpdateValidatorFn>,
}

/// Metadata for a registered workflow, generated by `#[workflow]`.
pub struct WorkflowInfo {
    /// Snake-case function name (e.g., `"onboarding_workflow"`).
    pub name: &'static str,
    /// `module_path!()` value from the macro call site.
    pub module: &'static str,
    /// Type-erased dispatch function.
    pub handler: WorkflowHandlerFn,
    /// Default maximum wall-clock lifetime for executions of this workflow type
    /// (issue #243). `None` means no deadline enforced unless overridden at the
    /// `start_workflow` call site. Per-call overrides always win over this default.
    pub execution_timeout: Option<Duration>,
}

/// Metadata for a registered activity, generated by `#[activity]`.
pub struct ActivityInfo {
    /// Snake-case function name.
    pub name: &'static str,
    /// `module_path!()` value from the macro call site.
    pub module: &'static str,
    /// Default retry policy (overridable at call site).
    pub default_retry_policy: Option<RetryPolicy>,
    /// Default start-to-close timeout.
    pub default_start_to_close: Option<Duration>,
    /// Default heartbeat timeout (`None` = disabled).
    pub default_heartbeat_timeout: Option<Duration>,
    /// Default schedule-to-start timeout.
    pub default_schedule_to_start: Option<Duration>,
    /// Default task queue name (`None` = `"default"`).
    pub default_queue: Option<&'static str>,
    /// Cluster-wide concurrency cap. `None` = no cap (only the worker-level
    /// `max_concurrent_activities` semaphore applies).
    pub max_concurrent: Option<u32>,
    /// Concurrency group key. Multiple activities sharing a key share the
    /// `max_concurrent` budget. Defaults to the activity's own name when
    /// `max_concurrent` is set and `concurrency_key` is not specified.
    pub concurrency_key: Option<&'static str>,
    /// When `true`, the worker runs this activity inline on the workflow task
    /// (never enqueued). Local activities must not set `heartbeat_timeout`,
    /// `schedule_to_start`, or `queue` — the macro enforces this at compile time.
    pub is_local: bool,
    /// Type-erased dispatch function.
    pub handler: ActivityHandlerFn,
}

/// Metadata for a registered DAG, generated by `#[dag]`.
pub struct DagInfo {
    /// Snake-case function name.
    pub name: &'static str,
    /// `module_path!()` value from the macro call site.
    pub module: &'static str,
    /// Optional schedule for automatic runs.
    pub schedule: Option<Schedule>,
    /// Whether the scheduler should backfill missed intervals.
    pub catchup: bool,
    /// Maximum number of active runs allowed at once.
    pub max_active_runs: u32,
    /// Default queue applied to tasks that do not override their queue.
    pub default_queue: Option<&'static str>,
    /// Builder function that populates a [`DagBuilder`].
    pub builder: fn(&mut DagBuilder),
    /// Lowered workflow handler, populated when the `unified-dag-execution`
    /// feature is enabled (issue #256 Step 1).
    ///
    /// `None` on the classic DAG execution path; `Some` when the feature is
    /// on so the runtime can route new DAG runs through `WorkflowInfo`
    /// without needing to look up the companion by name.
    pub workflow_handler: Option<WorkflowHandlerFn>,
    /// Maximum spread window for staggering schedule fires. `Duration::ZERO`
    /// disables jitter (default — today's behaviour).
    pub jitter: Duration,
    /// What to do when a new firing collides with a still-running execution.
    /// Defaults to [`OverlapPolicy::Skip`].
    pub overlap_policy: crate::policy::OverlapPolicy,
    /// Maximum buffered slots under [`OverlapPolicy::BufferAll`]. Default 100.
    pub buffer_all_max: u32,
}

impl DagInfo {
    /// Build an immutable DAG definition from this metadata.
    ///
    /// # Errors
    ///
    /// Returns [`DagBuildError`] if the builder creates an invalid graph.
    pub fn build_definition(&self) -> Result<DagDefinition, DagBuildError> {
        let mut dag = self
            .default_queue
            .map_or_else(DagBuilder::new, DagBuilder::with_default_queue);
        (self.builder)(&mut dag);
        dag.build()
    }

    /// Return a [`WorkflowSchedule`] that fires this DAG on its declared cron
    /// or interval via the unified workflow execution path (issue #256 Step 2).
    ///
    /// Returns `None` when either:
    /// - `workflow_handler` is `None` (unified-dag-execution feature is off), or
    /// - `schedule` is `None` (DAG has no automatic trigger).
    #[must_use]
    pub fn as_workflow_schedule(&self) -> Option<WorkflowSchedule> {
        self.workflow_handler?;
        let schedule = self.schedule.clone()?;
        Some(WorkflowSchedule {
            workflow_name: self.name.to_string(),
            dag_name: Some(self.name.to_string()),
            schedule,
            input: serde_json::Value::Null,
            catchup: self.catchup,
            max_active_runs: self.max_active_runs,
            paused: false,
            queue_name: self.default_queue.unwrap_or("default").to_string(),
            jitter: self.jitter,
            overlap_policy: self.overlap_policy,
            buffer_all_max: self.buffer_all_max,
            execution_timeout: None,
        })
    }

    /// Return a [`WorkflowInfo`] that executes this DAG via the unified
    /// workflow execution path (issue #256 Step 1).
    ///
    /// Returns `None` when the `unified-dag-execution` feature is disabled and
    /// `workflow_handler` was not populated by the macro.
    #[must_use]
    pub fn as_workflow_info(&self) -> Option<WorkflowInfo> {
        self.workflow_handler.map(|handler| WorkflowInfo {
            name: self.name,
            module: self.module,
            handler,
            execution_timeout: None,
        })
    }
}

impl std::fmt::Debug for WorkflowInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WorkflowInfo")
            .field("name", &self.name)
            .field("module", &self.module)
            .field("handler", &"<fn>")
            .field("execution_timeout", &self.execution_timeout)
            .finish()
    }
}

impl std::fmt::Debug for ActivityInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ActivityInfo")
            .field("name", &self.name)
            .field("module", &self.module)
            .field("default_retry_policy", &self.default_retry_policy)
            .field("default_start_to_close", &self.default_start_to_close)
            .field("default_heartbeat_timeout", &self.default_heartbeat_timeout)
            .field("default_schedule_to_start", &self.default_schedule_to_start)
            .field("default_queue", &self.default_queue)
            .field("max_concurrent", &self.max_concurrent)
            .field("concurrency_key", &self.concurrency_key)
            .field("is_local", &self.is_local)
            .field("handler", &"<fn>")
            .finish()
    }
}

impl std::fmt::Debug for DagInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DagInfo")
            .field("name", &self.name)
            .field("module", &self.module)
            .field("schedule", &self.schedule)
            .field("catchup", &self.catchup)
            .field("max_active_runs", &self.max_active_runs)
            .field("default_queue", &self.default_queue)
            .field("builder", &"<fn>")
            .field("workflow_handler", &self.workflow_handler.map(|_| "<fn>"))
            .field("jitter", &self.jitter)
            .field("overlap_policy", &self.overlap_policy)
            .field("buffer_all_max", &self.buffer_all_max)
            .finish()
    }
}

impl std::fmt::Debug for QueryHandlerInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("QueryHandlerInfo")
            .field("name", &self.name)
            .field("workflow", &self.workflow)
            .field("module", &self.module)
            .field("input_type_hint", &self.input_type_hint)
            .field("output_type_hint", &self.output_type_hint)
            .field("handler", &"<fn>")
            .finish()
    }
}

impl std::fmt::Debug for UpdateHandlerInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UpdateHandlerInfo")
            .field("name", &self.name)
            .field("workflow", &self.workflow)
            .field("module", &self.module)
            .field("input_type_hint", &self.input_type_hint)
            .field("output_type_hint", &self.output_type_hint)
            .field("has_validator", &self.has_validator)
            .field("handler", &"<fn>")
            .field("validator", &self.validator.map(|_| "<fn>"))
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::TriggerRule;

    #[test]
    fn workflow_info_fields_accessible() {
        let info = WorkflowInfo {
            name: "test_workflow",
            module: "my_app::workflows",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
        };
        assert_eq!(info.name, "test_workflow");
        assert!(info.execution_timeout.is_none());
    }

    #[test]
    fn workflow_info_execution_timeout_field_is_accessible() {
        let info = WorkflowInfo {
            name: "billing_reconciliation",
            module: "my_app::workflows",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: Some(std::time::Duration::from_secs(86_400)),
        };
        assert_eq!(info.execution_timeout, Some(std::time::Duration::from_secs(86_400)));
    }

    #[test]
    fn activity_info_default_policy() {
        let info = ActivityInfo {
            name: "test_activity",
            module: "my_app::activities",
            default_retry_policy: None,
            default_start_to_close: None,
            default_heartbeat_timeout: None,
            default_schedule_to_start: None,
            default_queue: None,
            max_concurrent: None,
            concurrency_key: None,
            is_local: false,
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        assert!(info.default_retry_policy.is_none());
        assert_eq!(info.default_queue, None);
        assert!(info.max_concurrent.is_none());
        assert!(info.concurrency_key.is_none());
        assert!(!info.is_local);
    }

    #[test]
    fn activity_info_is_local_true() {
        let info = ActivityInfo {
            name: "compute_hash",
            module: "my_app::activities",
            default_retry_policy: None,
            default_start_to_close: Some(std::time::Duration::from_secs(10)),
            default_heartbeat_timeout: None,
            default_schedule_to_start: None,
            default_queue: None,
            max_concurrent: None,
            concurrency_key: None,
            is_local: true,
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        assert!(info.is_local);
        assert!(
            info.default_heartbeat_timeout.is_none(),
            "local activities must not have heartbeat_timeout"
        );
        assert!(
            info.default_schedule_to_start.is_none(),
            "local activities must not have schedule_to_start"
        );
        assert!(
            info.default_queue.is_none(),
            "local activities must not have a queue"
        );
    }

    #[test]
    fn activity_info_concurrency_fields() {
        let info = ActivityInfo {
            name: "send_email",
            module: "my_app::activities",
            default_retry_policy: None,
            default_start_to_close: None,
            default_heartbeat_timeout: None,
            default_schedule_to_start: None,
            default_queue: None,
            max_concurrent: Some(5),
            concurrency_key: Some("email"),
            is_local: false,
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        assert_eq!(info.max_concurrent, Some(5));
        assert_eq!(info.concurrency_key, Some("email"));
    }

    #[test]
    fn dag_info_builds_definition() {
        fn extract_users() {}
        fn load_users() {}

        fn build(dag: &mut DagBuilder) {
            let first = dag.activity(extract_users);
            let _second = dag.activity(load_users).upstream(&first);
        }

        let info = DagInfo {
            name: "daily_etl",
            module: "tests",
            schedule: Some(Schedule::Manual),
            catchup: false,
            max_active_runs: 1,
            default_queue: Some("etl-workers"),
            builder: build,
            workflow_handler: None,
            jitter: ::std::time::Duration::ZERO,
            overlap_policy: crate::policy::OverlapPolicy::Skip,
            buffer_all_max: 100,
        };

        let definition = info.build_definition().expect("dag should compile");
        assert_eq!(definition.tasks().len(), 2);
        assert_eq!(definition.execution_levels().len(), 2);
        assert_eq!(definition.tasks()[0].queue.as_deref(), Some("etl-workers"));
        assert_eq!(definition.tasks()[1].trigger_rule, TriggerRule::AllSuccess);

        assert!(
            info.as_workflow_info().is_none(),
            "as_workflow_info should return None when workflow_handler is None"
        );
    }
    #[test]
    fn info_debug_formats_correctly() {
        let workflow_info = WorkflowInfo {
            name: "test_wf",
            module: "test_mod",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
            execution_timeout: None,
        };
        let debug_str = format!("{workflow_info:?}");
        assert!(debug_str.contains("WorkflowInfo"));
        assert!(debug_str.contains("test_wf"));

        let activity_info = ActivityInfo {
            name: "test_act",
            module: "test_mod",
            default_retry_policy: None,
            default_start_to_close: None,
            default_heartbeat_timeout: None,
            default_schedule_to_start: None,
            default_queue: None,
            max_concurrent: None,
            concurrency_key: None,
            is_local: false,
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        let debug_str = format!("{activity_info:?}");
        assert!(debug_str.contains("ActivityInfo"));
        assert!(debug_str.contains("test_act"));

        let dag_info = DagInfo {
            name: "test_dag",
            module: "test_mod",
            schedule: None,
            catchup: false,
            max_active_runs: 1,
            default_queue: None,
            builder: |_| {},
            workflow_handler: None,
            jitter: ::std::time::Duration::ZERO,
            overlap_policy: crate::policy::OverlapPolicy::Skip,
            buffer_all_max: 100,
        };
        let debug_str = format!("{dag_info:?}");
        assert!(debug_str.contains("DagInfo"));
        assert!(debug_str.contains("test_dag"));
    }
}
