//! Durable workflow orchestration engine core.

/// Embedded migrations for the harvest engine schema.
///
/// Downstream crates (such as `autumn-harvest-plugin`) should consume this
/// const instead of invoking `diesel_migrations::embed_migrations!()` against
/// this crate's path. Proc-macro path arguments are resolved at the *consumer's*
/// compile-time location, which doesn't survive `cargo publish` because the
/// upstream crate's directory layout isn't available in the downstream's
/// packaged tarball. Centralising the macro invocation here keeps the path
/// resolution local to this crate, where the `migrations/` directory always
/// ships alongside.
#[cfg(feature = "db")]
#[macro_export]
macro_rules! cfg_db {
    ($($item:item)*) => {
        $($item)*
    };
}

#[cfg(not(feature = "db"))]
#[macro_export]
macro_rules! cfg_db {
    ($($item:item)*) => {};
}

/// Await a chaos injection point (statement position). See [`chaos`].
///
/// `#[allow(unused_macros)]`: every call site lives in a `#[cfg(feature =
/// "db")]` module (`queue`, `worker`, `scheduler`, ...), so a no-`db` build
/// (e.g. `--no-default-features --features testing`) compiles the macro but
/// none of its invocations — an unused-macro warning that CI's `-D warnings`
/// would fail on. Mirrors `chaos_fallible!`.
#[cfg(feature = "chaos")]
#[allow(unused_macros)]
macro_rules! chaos_point {
    ($name:ident) => {
        $crate::chaos::hit($crate::chaos::points::$name).await
    };
}

/// Await a chaos injection point (compiled out; const-checks the point name).
#[cfg(not(feature = "chaos"))]
#[allow(unused_macros)]
macro_rules! chaos_point {
    ($name:ident) => {{
        const _: $crate::chaos::points::ChaosPoint = $crate::chaos::points::$name;
    }};
}

/// Await a fallible chaos injection point at a `?` site; propagates an injected
/// error via `From` into the enclosing function's error type. See [`chaos`].
#[cfg(feature = "chaos")]
#[allow(unused_macros)]
macro_rules! chaos_fallible {
    ($name:ident) => {
        $crate::chaos::hit_fallible($crate::chaos::points::$name).await?
    };
}

/// Fallible chaos injection point (compiled out; const-checks the point name).
#[cfg(not(feature = "chaos"))]
#[allow(unused_macros)]
macro_rules! chaos_fallible {
    ($name:ident) => {{
        const _: $crate::chaos::points::ChaosPoint = $crate::chaos::points::$name;
    }};
}

/// Ask a `LISTEN`/`NOTIFY` send site whether its wake should be dropped
/// (expression position, evaluates to `bool`). Synchronous — no `.await`. See
/// [`chaos`].
#[cfg(feature = "chaos")]
#[allow(unused_macros)]
macro_rules! chaos_drop_notify {
    ($name:ident) => {
        $crate::chaos::should_drop_notify($crate::chaos::points::$name)
    };
}

/// Drop-notify query (compiled out; const-checks the point name, always
/// `false`). The `false` is a compile-time constant, so the guarded `NOTIFY`
/// branch is dead-code-eliminated in a non-chaos build — zero hot-path cost.
#[cfg(not(feature = "chaos"))]
#[allow(unused_macros)]
macro_rules! chaos_drop_notify {
    ($name:ident) => {{
        const _: $crate::chaos::points::ChaosPoint = $crate::chaos::points::$name;
        false
    }};
}

// Re-export the crate-internal chaos macros by path so injection sites can call
// `crate::chaos_point!(NAME)` regardless of module-declaration order (a plain
// `macro_rules!` is only visible by bare name to code textually after it). Each
// `use` resolves to whichever cfg arm compiled, so it is config-agnostic. Not
// `#[macro_export]`: these are test-harness internals, never public API.
#[allow(unused_imports)]
pub(crate) use {chaos_drop_notify, chaos_fallible, chaos_point};

#[cfg(feature = "db")]
pub const MIGRATIONS: diesel_migrations::EmbeddedMigrations =
    diesel_migrations::embed_migrations!();

// Consume the env var emitted by build.rs so that Cargo recompiles this
// crate (and re-runs embed_migrations!()) whenever a migration is added or
// removed — even when only the migrations/ directory changed and no Rust
// source file was edited.
#[cfg(feature = "db")]
const _MIGRATIONS_LIST: &str = env!("HARVEST_MIGRATIONS_LIST");

/// The complete set of Harvest migrations, concatenated in timestamp order,
/// as one SQL string ready to apply to a fresh Postgres.
///
/// This is the **paved path** for testcontainers-backed integration tests: use
/// it as the `with_init_sql` payload instead of hand-rolling a
/// `concat!(include_str!(...))` list of individual migrations. A hand-rolled
/// list silently drifts out of date whenever a new migration lands — e.g.
/// `nd_block_tests` was missing `20260704000001_harvest_build_policy_ramp`, so
/// every workflow start there failed `column "target_build_id" does not exist`,
/// invisible because CI only *compiled* that suite, never *ran* it against a DB.
/// `full_migrations_sql()` can never drift: the bundle is regenerated by
/// `build.rs` from the `migrations/` directory on every build.
///
/// Intentionally unconditional (not `db`-feature-gated): it is a cheap
/// `&'static str` with no dependency on Diesel, so it is reachable from every
/// test context — including the plugin crate's integration tests and no-default
/// builds — without feature juggling.
///
/// `#[doc(hidden)]`: this is a test-support helper, not part of the engine's
/// semver-stable public surface. It stays `pub` so the plugin crate's
/// integration tests can call it across the crate boundary.
#[doc(hidden)]
#[must_use]
pub const fn full_migrations_sql() -> &'static str {
    include_str!(concat!(env!("OUT_DIR"), "/all_migrations_bundle.sql"))
}

/// Per-activity-type pause/resume for surgical outage containment (issue #807).
pub mod activity_pause;
/// Admission gate primitive for incident-response operators (issue #377).
pub mod admission_gate;
/// History analyzer and linter.
pub mod analyzer;
/// Pure token-secret helpers shared by the mint route and the CLI (issue #942).
pub mod api_token;
/// Audit trail for management API mutations (issue #158).
#[cfg(feature = "db")]
pub mod audit;
/// Open-awaitables diagnostic projection (issue #615).
pub mod awaitables;
/// Post-restore resumability verification for backup/PITR drills (issue #943).
pub mod backup_verify;
/// Batch operations for fleet-wide workflow cancel/terminate/signal (issue #102).
pub mod batch;
/// Batch workflow start types: caps and per-item request/result structs (issue #357).
pub mod batch_start;
/// Worker build-id routing for safe rolling deploys (issue #171).
#[cfg(feature = "db")]
pub mod build_routing;
pub mod builder;
pub mod cache;
/// Calendar-aware schedule filtering: named exclusion sets, skip policies, and
/// schedule preview generation (issue #337).
pub mod calendar;
/// Built-in synthetic liveness canary (issue #796).
///
/// Reserved names + predicates for the throwaway workflow that probes the live
/// execution path. Distinct from the #512 replay canary.
pub mod canary;
/// Deterministic chaos/fault-injection test harness (issue #940).
///
/// [`chaos::points`] is unconditional (a zero-cost const catalogue of named
/// injection points); the controller (`arm`, `hit`, `ChaosPlan`, ...) is
/// `#[cfg(feature = "chaos")]` and never part of a production binary.
#[doc(hidden)]
pub mod chaos;
/// Per-activity circuit breaker that fast-fails dispatch during downstream
/// outages (issue #369).
pub mod circuit_breaker;
/// Durable completion callbacks (issue #605).
///
/// Pushes a workflow's terminal result to an operator-registered URL,
/// HMAC-signed and SSRF-guarded.
pub mod completion_callback;
pub mod completion_trigger;
/// Per-key concurrency limits for tenant fair-share scheduling (issue #247).
pub mod concurrency;
pub mod context;
pub mod critical_path;
pub mod dag;
/// Export format types for Directed Acyclic Graphs (DAGs) representing workflows.
pub mod dag_export;
pub mod dag_linter;
#[cfg(any(test, feature = "testing"))]
pub mod dag_profiler;
#[cfg(any(test, feature = "testing"))]
pub mod dag_simulator;
/// Debounced workflow starts — collapse trigger bursts into one run (issue #499).
pub mod debounce;
/// Time-travel replay debugger for recorded workflow histories (issue #949).
///
/// Read-only by construction: no new [`WorkflowEvent`](crate::event::WorkflowEvent)
/// variant, no migration, no engine-runtime change. Gated behind the `debugger`
/// feature (which enables `testing`).
#[cfg(feature = "debugger")]
pub mod debugger;
/// Deterministic workflow guardrails: static source-level check for replay-breaking patterns.
pub mod det_check;
pub mod diagnostic;
/// Effective runtime-configuration introspection (issue #695).
///
/// [`effective_config::EffectiveConfigView`] is the serialisable, secret-free
/// snapshot served from `GET /api/harvest/admin/config`. The
/// [`effective_config::WorkerConfigView::from_worker_config`] mapping
/// destructures [`builder::WorkerConfig`] exhaustively (no `..`) so a new
/// tunable is a compile error until it is surfaced.
pub mod effective_config;
pub mod eligibility;
/// Targeted PII erasure for completed workflow executions (issue #495).
///
/// Provides [`erase::erase_workflow_payloads`] (DB-gated) plus the pure
/// helpers [`erase::tombstone_payload_fields`] and
/// [`erase::is_terminal_state`] that are unit-testable without a database.
pub mod erase;
pub mod error;
pub mod event;
/// Event-batched workflow starts — fold many triggers into one batched run (issue #518).
pub mod event_batch;
#[cfg(feature = "db")]
#[doc(hidden)]
pub mod execution;
pub mod executor;
#[cfg(feature = "db")]
pub mod external_task;
pub mod failure;
/// Deterministic workflow guardrail rule catalog (issue #173).
pub mod guardrail;
#[cfg(feature = "db")]
pub mod handle;
#[cfg(feature = "db")]
pub mod handle_typed;
pub mod history_export;
pub mod info;
/// Activity execution interceptors (issue #680): an ordered middleware chain
/// wrapping every activity execution on the worker (regular + local).
pub mod interceptor;
/// `cfg(loom)` synchronization-primitive shim (std under normal builds).
///
/// Contained to the modules that opt into loom model checking; see
/// `docs/testing/loom.md`. Internal — not part of the public API.
mod loom_sync;
/// `metrics` crate adapter for [`telemetry::MetricsRecorder`].
///
/// Bridges every `record_*` call to the global [`metrics`] registry so
/// applications using `metrics-exporter-prometheus` or another compatible
/// backend get harvest engine metrics without any extra glue code.
///
/// Enabled by the `metrics-rs` cargo feature.
#[cfg(feature = "metrics-rs")]
pub mod metrics_rs_adapter;
/// Durable mutual-exclusion locks for workflow code (`ctx.mutex`, issue #691).
pub mod mutex;
pub mod payload_codec;
pub mod payload_store;
pub mod poison_pill;
pub mod policy;
pub mod pool;
pub mod prelude;
/// Types and definitions for querying workflow state and metadata.
pub mod query;
#[doc(hidden)] // internal implementation detail; no stability guarantee
pub mod queue_fairness;
pub mod queue_pause;
/// Per-tenant resource quotas on executions, history, and DLQ (issue #946).
///
/// Pure types ([`quota::QuotaPolicy`], [`quota::QuotaResource`],
/// [`quota::resolve_quota_key`], [`quota::check_quota`]) compile without the
/// `db` feature; [`quota::load_quota_usage`]/[`quota::list_quota_usage`] are
/// DB-gated.
pub mod quota;
pub mod replay;
/// Stratified in-flight history sampling for the replay-drift gate (issue #798).
///
/// Carries the pure, database-free vocabulary shared by the sample export
/// (`GET /admin/history/export-sample`), the `harvest history export-sample`
/// CLI bundle writer, and [`testing::ReplayVerifier::replay_bundle`], so the
/// bundle wire shape cannot drift between producer and consumer.
pub mod replay_sample;
#[cfg(feature = "db")]
pub mod reset;
pub mod retention;
/// Continue-as-new run-chain assembly (issue #701).
pub mod run_chain;
pub mod saga;
/// Background control-loop liveness heartbeats (issue #797).
pub mod scanner_health;
/// Workflow payload-schema contract baseline and replay-compatibility diffing (issue #794).
///
/// Deliberately ungated: the CLI links `autumn-harvest` with
/// `default-features = false`, so the gate must be reachable without `db` or
/// `schema`.
pub mod schema_contract;
/// Worker session fleet-side registry and pure decision functions (issue #606).
pub mod sessions;
pub mod shard;
/// Signal handler registry for push-based reactive signal handling (issue #546).
pub mod signal_handler;
pub mod simulator;
/// Adaptive worker dispatch-slot tuner (issue #548).
pub mod slot_tuner;
/// Per-execution stall diagnosis — the root-cause classifier (issue #809).
pub mod stall_diagnosis;
/// Request-scoped idempotency keys for plain workflow starts (issue #808).
pub mod start_idempotency;
/// OpenTelemetry integration: trace-context propagation and metrics.
pub mod telemetry;
#[cfg(any(test, feature = "testing"))]
pub mod test_generator;
/// Replay test harness for verifying workflow determinism pre-deploy.
#[cfg(any(test, feature = "testing"))]
pub mod testing;
/// Workflow-start throttle — pace admissions, defer the excess (issue #607).
pub mod throttle;
/// Per-execution timeline read model (issue #739).
pub mod timeline;
#[cfg(any(test, feature = "testing"))]
pub mod trace_export;
pub mod types;
pub mod update;
/// Read-only per-tenant/per-workflow usage aggregation (issue #596).
///
/// Pure wire-format types compile without the `db` feature;
/// [`usage::load_usage_grouped`] is DB-gated.
pub mod usage;
#[cfg(feature = "db")]
pub mod version_gate_retirement;
#[cfg(feature = "db")]
pub mod version_usage;
/// Inbound HTTP webhook trigger descriptors (issue #344).
///
/// Pure, unconditional (not `db`-gated) — the `#[webhook]` macro's
/// companion function must always compile. See the module docs for the
/// autumn-web-owns-verification design.
pub mod webhook_trigger;

#[cfg(feature = "db")]
#[doc(hidden)]
pub mod dlq;
#[cfg(feature = "db")]
#[doc(hidden)]
pub mod heartbeat;
#[cfg(feature = "db")]
#[doc(hidden)]
pub mod models;
#[cfg(feature = "db")]
#[doc(hidden)]
pub mod notify;
#[cfg(feature = "db")]
#[doc(hidden)]
pub mod queue;
#[cfg(feature = "db")]
pub mod schedule_decision;
#[cfg(feature = "db")]
pub mod scheduler;
#[cfg(feature = "db")]
#[allow(clippy::wildcard_imports)]
#[doc(hidden)]
pub mod schema;
#[cfg(feature = "db")]
#[doc(hidden)]
pub mod signal;
#[cfg(feature = "db")]
#[doc(hidden)]
pub mod store;
#[cfg(feature = "db")]
#[doc(hidden)]
pub mod timeout;
#[cfg(feature = "wasm-activities")]
pub mod wasm_activities;
/// Postgres storage and dispatch resolution for WASM activities (issue #965).
#[cfg(feature = "wasm-activities")]
pub mod wasm_store;
#[cfg(feature = "db")]
#[doc(hidden)]
pub mod worker;
#[cfg(feature = "db")]
pub mod workers;

pub use admission_gate::{
    AdmissionGate, AdmissionGateCache, AdmissionGateId, AdmissionGateView, GateMode, GateScope,
    MAX_ACTIVE_GATES, ProducerContractEntry, ProducerGateStatus, StartProducer, check_admission,
    global_admission_gate_cache, producer_contract, set_global_admission_gate_cache,
};
pub use analyzer::{
    AnalyzerRule, AnalyzerWarning, ExcessiveRetriesRule, HistoryAnalyzer, LargePayloadRule,
    SuspiciousTimerRule,
};
pub use builder::{
    BuiltHarvest, HarvestBuilder, HarvestBuilderError, StickyRoutingConfig, WorkerConfig,
};
pub use cache::{CachedWorkflowState, WorkflowCache};
#[cfg(feature = "db")]
pub use calendar::{
    BackfillSlot, create_calendar, delete_calendar, get_calendar, list_calendars,
    load_exclusions_for_calendar, plan_backfill_with_calendar, preview_schedule_firings,
    replace_calendar_exclusions,
};
pub use calendar::{
    BusinessCalendars, BusinessDayRejection, BusinessDayResolution, Calendar, MAX_BUSINESS_DAYS,
    ScheduleFirePreview, add_business_days, add_business_days_bounded, apply_skip_policy,
    calendar_excludes_weekends, is_business_day, is_excluded_date, next_business_day_at_or_after,
};
pub use canary::{
    CANARY_ACTIVITY_NAME, CANARY_WORKFLOW_NAME_PREFIX, is_canary_workflow, is_reserved_canary_name,
};
pub use completion_trigger::{
    CompletionTrigger, ConditionGate, InputMapping, MAX_CONDITION_DEPTH, MAX_CONDITION_IN_VALUES,
    MAX_CONDITION_NODES, TerminalState, TriggerCondition, gate_stored_condition,
};
pub use context::{
    ActivityContext, ActivityExecutionInfo, ActivityIdentity, AutoHeartbeatGuard,
    DEFAULT_CONTINUE_AS_NEW_DEADLINE_FRACTION, DEFAULT_HISTORY_CONTINUE_AS_NEW_THRESHOLD,
    DEFAULT_SESSION_ACQUISITION_TIMEOUT, DEFAULT_WORKFLOW_LOG_MAX_LINES,
    DEFAULT_WORKFLOW_LOG_MAX_MESSAGE_BYTES, MutexGuard, MutexHandle, RaceBuilder, RaceWinner,
    Session, SessionOptions, TimerHandle, TimerOutcome, WorkflowCommand, WorkflowContext,
    WorkflowExecutionInfo, WorkflowHistoryPolicy, WorkflowLogLevel, WorkflowLogPolicy,
    WorkflowLogger, is_reserved_session_activity_name,
};
pub use critical_path::{CriticalPathAnalyzer, CriticalPathResult};
pub use dag::{
    DagBuildError, DagBuilder, DagCondition, DagDefinition, DagDispatchDecision, DagInputBinding,
    DagMapTaskRef, DagMergeSource, DagSignalGate, DagTask, DagTaskRef, GateTimeoutAction,
};
#[cfg(feature = "testing")]
pub use dag_export::export_profile_mermaid_gantt;
pub use dag_export::{export_dot, export_mermaid, export_mermaid_with_critical_path};
pub use dag_linter::{
    DagLinter, DagRule, DagWarning, ExcessiveParallelismRule, MissingRetryPolicyRule,
    MissingTimeoutRule,
};
#[cfg(any(test, feature = "testing"))]
pub use dag_profiler::{DagProfile, DagProfiler, ProfilerEvent, ProfilerEventKind};
#[cfg(any(test, feature = "testing"))]
pub use dag_simulator::{DagSimulator, DagSimulatorResult};
pub use det_check::{
    DetCheckReport, DetFinding, DetLocation, DetSeverity, DetSuppression, check_dir, check_file,
    check_paths, check_source,
};
pub use diagnostic::{DiagnosticReport, SimulatorResultExt};
pub use error::{CapabilityMissPhase, HarvestError, HarvestResult, TimeoutType};
pub use event::{SideEffectKind, WorkflowEvent};
#[cfg(feature = "db")]
pub use execution::{
    CancelledWorkflowExecution, IdempotentStartOutcome, ORIGIN_BACKFILL, ORIGIN_MANUAL_TRIGGER,
    ORIGIN_SCHEDULED, PausedWorkflowExecution, RETRY_CHAIN_MAX_DEPTH, RETRY_CHAIN_MAX_REDRIVES,
    ResolvedRun, ResumedWorkflowExecution, ScheduleRunQuery, ScheduleRunRow, ScheduleRunStateCount,
    SignalWithStartOutcome, SignalWithStartParams, StartWorkflowParams, StartedWorkflowExecution,
    TriageFieldChange, TriageOutcome, TriagePatch, UpdateWithStartOutcome, UpdateWithStartParams,
    WorkflowCountDimension, WorkflowCountQuery, WorkflowCountRow, WorkflowTypeNonTerminalCount,
    annotate_workflow_execution, auto_resume_expired_pauses, cancel_live_attempt,
    cancel_workflow_execution, count_workflow_executions_grouped, list_schedule_runs,
    non_terminal_counts_by_workflow_name, pause_live_attempt, pause_workflow_execution,
    redrive_target, resolve_execution_id_by_workflow_id, resolve_live_attempt,
    resolve_live_attempt_id, resume_live_attempt, resume_workflow_execution,
    schedule_run_state_summary, select_resolved_run, signal_with_start_workflow_execution,
    signal_with_start_workflow_execution_with_metrics, start_or_load_workflow_execution,
    start_or_load_workflow_execution_idempotent, start_or_load_workflow_execution_with_metrics,
    terminate_live_attempt, terminate_workflow_execution, update_with_start_workflow_execution,
    update_with_start_workflow_execution_with_metrics,
};
pub use executor::{WorkflowOutcome, run_workflow};
pub use guardrail::{
    GuardrailFinding, GuardrailSuppression, GuardrailSuppressionError, RuleCategory, RuleEntry,
    Severity, catalog as guardrail_catalog, rule_by_id as guardrail_rule_by_id,
};
#[cfg(feature = "db")]
pub use handle::{
    StartedWorkflowHandle, TransactionalStartOptions, TransactionalStartOutcome, WorkflowHandle,
    WorkflowHandleClient, WorkflowResult, WorkflowResultState,
    start_or_load_workflow_execution_with_handle,
};
#[cfg(feature = "db")]
pub use handle_typed::{
    TypedSignalWithStartOptions, TypedStartOptions, TypedUpdateWithStartOptions,
    TypedWorkflowHandle, TypedWorkflowResult,
};
pub use history_export::{
    DEFAULT_HISTORY_EXPORT_MAX_BYTES, HISTORY_EXPORT_SCHEMA, HISTORY_EXPORT_VERSION,
    HistoryExportDocument, HistoryExportError, HistoryExportRequest, HistoryExportSizeLimit,
    HistoryExportStatus, HistoryPayloadPolicy, export_history, export_mermaid_sequence,
};
pub use info::{
    ActivityHandlerFn, ActivityInfo, DagInfo, InterfaceHandlerRecord, QueryHandlerFn,
    QueryHandlerInfo, SignalHandlerInfo, UpdateHandlerFn, UpdateHandlerInfo, UpdateValidatorFn,
    WorkflowHandlerFn, WorkflowInfo, WorkflowInterfaceRecord,
};
pub use interceptor::{
    ActivityInterceptor, ActivityInterceptorFuture, ActivityInterceptorNext, ActivityInvocation,
};
pub use mutex::{
    DEFAULT_MUTEX_LEASE_TTL, MutexGrantOutcome, MutexWakeTarget, effective_mutex_lease_ttl,
    set_mutex_lease_ttl,
};
pub use payload_codec::{
    CodecError, IdentityCodec, LossyDecodeOutcome, PayloadCodec, PayloadCodecs,
    UNDECODABLE_MARKER_KEY, UNDECODABLE_REASON_CODEC_ERROR, UNDECODABLE_REASON_INVALID_BASE64,
    UNDECODABLE_REASON_INVALID_JSON, UNDECODABLE_REASON_UNKNOWN_CODEC, undecodable_marker,
};
pub use payload_store::{
    OffloadedRef, PayloadOffloader, PayloadStore, PayloadStoreError, PayloadStoreFuture,
};
pub use policy::validate_schedule;
pub use policy::{
    CatchupPolicy, MapFailurePolicy, OverlapPolicy, RetryPolicy, Schedule, SkipPolicy, TaskStatus,
    TriggerRule, WorkflowSchedule,
};
pub use pool::{HarvestPoolConfig, compute_pool_sizes};
pub use query::QueryRegistry;
pub use replay::{
    ChildOrTimerMatch, DEADLINE_PROBE_SIDE_EFFECT_NAME, HistoryMatch, HistoryMatcher,
    MutexGrantMatch, PatchMarkerMatch, SagaMarkerMatch, SideEffectNowMatch, SignalOrTimerMatch,
    TimerFireMatch,
};
#[cfg(feature = "db")]
pub use reset::{
    BatchResetItem, BatchResetOutcome, ResetInvalidPoint, ResetPlan, ResetPoint, ResetResult,
    ResetSignalReapplyPolicy, ResetSkipReason, ResetUnresolvedSideEffect, WorkflowResetError,
    WorkflowResetRequest, preview_workflow_reset, reset_workflow_execution,
    resolve_batch_reset_one, resolve_reset_point, validate_reset_point,
};
pub use retention::{
    ArchiverFuture, HistoryArchiver, LegalHoldOutcome, RetentionConfig, legal_hold_active,
};
#[cfg(feature = "db")]
pub use retention::{
    RetentionMonitor, RetentionRuntime, RetentionStatus, RetentionTickResult, release_legal_hold,
    set_legal_hold,
};
pub use run_chain::{
    RunChainRecord, RunChainResponse, RunChainRow, assemble_run_chain, outcome_for_state,
};
pub use saga::Saga;
#[cfg(feature = "db")]
pub use schedule_decision::record_decision_graceful;
#[cfg(feature = "db")]
pub use scheduler::{
    DagCatalog, RegisteredDag, SchedulerMonitor, SchedulerRuntime, compile_dag_catalog,
    register_schedules, register_workflow_schedules, tick_once, trigger_unified_dag,
};
pub use schema_contract::{
    AcknowledgedBreakingChange, ChangeKind, CompatibilityRules, DEFAULT_SCHEMA_CONTRACT_PATH,
    MAX_DELTAS, SCHEMA_CONTRACT_VERSION, SchemaContractDiff, SchemaContractError, SchemaCoverage,
    SchemaDelta, SchemaRole, Verdict, WorkflowSchemaContract, WorkflowSchemaEntry,
    canonicalize_schema, diff_schema_contracts, dropped_acknowledgements, unacknowledged_breaking,
};
#[cfg(feature = "db")]
pub use shard::ShardedDbPool;
pub use shard::{ShardPlacement, ShardPlacementError, ShardRouter, ShardRouterParts};
pub use signal_handler::SignalHandlerRegistry;
pub use simulator::{SimulatorResult, WorkflowSimulator};
pub use stall_diagnosis::{
    AwaitedSignalFacts, BlockedOn, BlockingCircuitPhase, DiagnosisInputs, ExecutionHealth,
    ExternalHandoffFacts, NdBlockFacts, PendingActivityFacts, PendingChildFacts, PendingTimerFacts,
    ReplayWaitFacts, TIMER_OVERDUE_GRACE_SECONDS, WorkflowTaskFacts, activity_precedence,
    classify_execution, classify_pending_activity, classify_workflow_task, summarize,
    workflow_task_hard_impediment, workflow_wake_was_missed,
};
#[cfg(feature = "db")]
pub use store::AwaitMode;
pub use telemetry::{
    ActivityStatus, MetricsRecorder, NoOpMetrics, NoOpPropagator, SCANNER_SHARD_LABEL_NONE,
    TelemetryConfig, TelemetryConfigBuilder, TraceContextCarrier, TraceContextPropagator,
    USER_METRIC_PREFIX, UserMetricError, UserMetrics, WebhookOutcome, WorkflowStatus,
    validate_user_metric,
};
#[cfg(any(test, feature = "testing"))]
pub use test_generator::TestHarnessGenerator;
#[cfg(feature = "testing")]
pub use testing::{
    BatchReplayReport, CiReport, FailOnMode, FixtureResult, FixtureStatus, HarnessErrorKind,
    ReplayBlocked, ReplayDrift, ReplayDriftReport, ReplayVerifier, ReportFormat, TestRunOutcome,
    WorkflowTestEnv,
};
#[cfg(all(feature = "db", any(test, feature = "testing")))]
pub use testing::{
    CanaryFailureDetail, CanaryTypeSummary, CanaryVerdict, ReplayCanaryOptions, ReplayCanaryReport,
};
#[cfg(any(test, feature = "testing"))]
pub use testing::{
    HistorySnapshot, NonDeterminismKind, ReplayReport, ReplayStatus, WorkflowReplayer,
};
pub use timeline::{
    SlowestStep, StepKind, StepOutcome, Timeline, TimelineEventRow, TimelineRollup, TimelineStep,
    derive_timeline,
};
#[cfg(any(test, feature = "testing"))]
pub use trace_export::export_chrome_trace;
pub use types::{
    ActivityExecId, BuildId, DeploymentName, ExecutionId, ExternalActivityToken, ExternalAwaitId,
    ExternalCancelId, ExternalSignalId, ExternalTarget, ParentClosePolicy, Priority, SessionId,
    ShardId, StartSource, TimerId, UpdateId, WorkerId, WorkflowId, WorkflowIdConflictPolicy,
    WorkflowIdReusePolicy,
};
pub use update::UpdateRegistry;
#[cfg(feature = "db")]
pub use version_usage::{
    VersionExecutionStateGroup, VersionUsageFilters, VersionUsageShardRow, load_version_usage,
};
pub use webhook_trigger::{
    WebhookCtx, WebhookHandlerError, WebhookHandlerFn, WebhookTarget, WebhookTriggerInfo,
    validate_webhook_triggers,
};

#[cfg(feature = "wasm-activities")]
pub use wasm_activities::{
    DEFAULT_FUEL, DEFAULT_MAX_WALL_CLOCK, DEFAULT_MEMORY_BYTES, EPOCH_TICK_INTERVAL,
    WASM_MAX_OUTPUT_BYTES, WasmCapabilities, WasmLimits, WasmModuleStore, deadline_ticks,
    invoke_wasm_activity,
};
#[cfg(feature = "wasm-activities")]
pub use wasm_store::{
    MAX_WASM_MODULE_BYTES, PreparedWasmActivity, WasmActivityRegistration, WasmBinding,
    WasmDispatch, WasmModuleRow, fetch_wasm_module_bytes, list_wasm_modules, publish_wasm_module,
    resolve_active_wasm_hash, resolve_active_wasm_module, resolve_wasm_dispatch,
    seed_registered_wasm_modules, seed_wasm_module,
};

#[cfg(feature = "db")]
pub use store::EventHistory;

#[cfg(feature = "db")]
pub use models::{AuditRecord, NewAuditRecord};

#[cfg(feature = "db")]
pub use diesel;
#[cfg(feature = "db")]
pub use diesel_async;

#[cfg(feature = "db")]
pub use dlq::parse_instant;

#[cfg(feature = "db")]
pub use queue::{ConcurrencyKeyStats, QueueScalingSignal, QueueTaskCounts, queue_task_counts};

// Allow macro-generated code to use ::autumn_harvest::serde_json
pub use serde_json;
// Allow macro-generated code to use ::autumn_harvest::serde
pub use serde;
// Allow macro-generated code to use ::autumn_harvest::chrono
pub use chrono;
// Allow macro-generated code to use ::autumn_harvest::uuid (e.g. update_with_start UUIDv5 derivation)
pub use uuid;
// Allow macro-generated code to use ::autumn_harvest::futures.
#[doc(hidden)]
pub use futures;

/// Parse a human-readable byte-size string like `"2MiB"`, `"256KiB"`, `"4MB"`.
///
/// Accepted suffixes: `KiB`, `KB`, `MiB`, `MB`, `GiB`, `GB`, or no suffix for
/// plain bytes. Returns `None` for empty strings or unrecognised suffixes.
///
/// ## Examples
///
/// ```rust
/// assert_eq!(autumn_harvest::parse_byte_size("2MiB"), Some(2 * 1024 * 1024));
/// assert_eq!(autumn_harvest::parse_byte_size("256KiB"), Some(256 * 1024));
/// assert_eq!(autumn_harvest::parse_byte_size("4MB"), Some(4_000_000));
/// assert_eq!(autumn_harvest::parse_byte_size("invalid"), None);
/// ```
#[must_use]
#[allow(clippy::option_if_let_else)]
pub fn parse_byte_size(s: &str) -> Option<u64> {
    let s = s.trim();
    if s.is_empty() {
        return None;
    }
    let (digits, multiplier): (&str, u64) = if let Some(n) = s.strip_suffix("GiB") {
        (n.trim(), 1024 * 1024 * 1024)
    } else if let Some(n) = s.strip_suffix("GB") {
        (n.trim(), 1_000_000_000)
    } else if let Some(n) = s.strip_suffix("MiB") {
        (n.trim(), 1024 * 1024)
    } else if let Some(n) = s.strip_suffix("MB") {
        (n.trim(), 1_000_000)
    } else if let Some(n) = s.strip_suffix("KiB") {
        (n.trim(), 1024)
    } else if let Some(n) = s.strip_suffix("KB") {
        (n.trim(), 1_000)
    } else {
        (s, 1)
    };
    let n: u64 = digits.parse().ok()?;
    n.checked_mul(multiplier)
}

/// Parse a human-readable duration string like `"5m"`, `"30s"`, `"1h"`.
///
/// Used by macro-generated code — not intended for direct use.
#[doc(hidden)]
#[must_use]
pub fn task_duration(s: &str) -> Option<std::time::Duration> {
    let mut total_secs = 0u64;
    let mut current_num = String::new();

    for ch in s.chars() {
        if ch.is_ascii_digit() {
            if current_num == "0" {
                current_num.clear();
            }
            if current_num.len() > 20 {
                return None;
            }
            current_num.push(ch);
        } else if ch.is_ascii_alphabetic() {
            let num: u64 = current_num.parse().ok()?;
            current_num.clear();
            match ch {
                's' => total_secs = total_secs.checked_add(num)?,
                'm' => total_secs = total_secs.checked_add(num.checked_mul(60)?)?,
                'h' => total_secs = total_secs.checked_add(num.checked_mul(3600)?)?,
                'd' => total_secs = total_secs.checked_add(num.checked_mul(86400)?)?,
                _ => return None,
            }
        } else if ch != ' ' {
            return None;
        }
    }

    if !current_num.is_empty() || total_secs == 0 {
        return None;
    }

    Some(std::time::Duration::from_secs(total_secs))
}

#[cfg(test)]
mod tests {
    use super::task_duration;
    use std::time::Duration;

    #[cfg(feature = "db")]
    #[test]
    fn embedded_migrations_include_one_harvest_initial() {
        use diesel::migration::MigrationSource;
        use diesel::pg::Pg;

        let migrations =
            <diesel_migrations::EmbeddedMigrations as MigrationSource<Pg>>::migrations(
                &super::MIGRATIONS,
            )
            .expect("embedded migrations should load");
        let harvest_initial_count = migrations
            .iter()
            .filter(|migration| migration.name().to_string().ends_with("_harvest_initial"))
            .count();

        assert_eq!(harvest_initial_count, 1);
    }

    #[test]
    fn task_duration_parses_compound_values() {
        assert_eq!(task_duration("1h 30m"), Some(Duration::from_secs(5_400)));
        assert_eq!(task_duration("5s"), Some(Duration::from_secs(5)));
        assert_eq!(task_duration("2d"), Some(Duration::from_secs(172_800)));
    }

    #[test]
    fn task_duration_rejects_invalid_values() {
        assert_eq!(task_duration(""), None);
        assert_eq!(task_duration("5"), None);
        assert_eq!(task_duration("5x"), None);
    }

    #[test]
    fn task_duration_rejects_overflow() {
        assert_eq!(task_duration("18446744073709551615d"), None); // u64::MAX
        assert_eq!(task_duration("18446744073709551615h"), None); // u64::MAX
        assert_eq!(task_duration("18446744073709551615m"), None); // u64::MAX
        assert_eq!(task_duration("18446744073709551614s 2s"), None); // Add overflow
    }

    #[test]
    fn havoc_task_duration_oom_prevention() {
        // Attack: Provide an excessively long string of digits.
        // The implementation rejects it early instead of boundedly growing `current_num`.
        let massive_input = "1".repeat(100);
        let result = task_duration(&massive_input);
        assert_eq!(result, None);
    }

    #[test]
    fn task_duration_allows_zero_padded_values() {
        let zero_padded = format!("{}1s", "0".repeat(50));
        assert_eq!(task_duration(&zero_padded), Some(Duration::from_secs(1)));
        // 0s is rejected globally by task_duration, so we test None
        assert_eq!(task_duration("000000000000s"), None);
        assert_eq!(task_duration("0000010m"), Some(Duration::from_secs(600)));
    }
}
