// autumn-harvest/src/schema.rs
// Hand-written to match migrations/20260409000000_harvest_initial/up.sql.
// Keep in sync with the migration. In production, regenerate via `diesel print-schema`.
//! Database schema definitions generated by Diesel.
//!
//! This module contains the `diesel::table!` macros mapping Rust types to the PostgreSQL
//! schema defined in the `migrations` directory. It acts as the bridge between the database
//! tables and Diesel's strongly-typed query builder.

diesel::table! {
    use diesel::sql_types::*;

    harvest_workflow_executions (id) {
        id -> Uuid,
        workflow_name -> Text,
        workflow_id -> Text,
        run_id -> Uuid,
        shard_id -> Int4,
        state -> Text,
        input -> Jsonb,
        output -> Nullable<Jsonb>,
        error -> Nullable<Text>,
        parent_id -> Nullable<Uuid>,
        sticky_worker_id -> Nullable<Text>,
        queue_name -> Text,
        started_at -> Timestamptz,
        completed_at -> Nullable<Timestamptz>,
        execution_timeout -> Nullable<Interval>,
        /// Absolute UTC deadline for execution-level timeout (issue #243).
        /// Computed at start as `started_at + execution_timeout`. NULL = no deadline.
        deadline_at -> Nullable<Timestamptz>,
        memo -> Nullable<Jsonb>,
        search_attrs -> Nullable<Jsonb>,
        created_at -> Timestamptz,
        /// Build ID assigned to this execution at start time (issue #171).
        assigned_build_id -> Nullable<Text>,
        /// Parent-close policy for detached children (issue #347). NULL for awaited children.
        parent_close_policy -> Nullable<Text>,
        owner -> Nullable<Text>,
        runbook_url -> Nullable<Text>,
        severity -> Nullable<Text>,
        /// Wall-clock instant the active pause was applied (issue #383). NULL = not paused.
        paused_at -> Nullable<Timestamptz>,
        /// Optional operator-supplied pause reason (issue #383).
        pause_reason -> Nullable<Text>,
        /// Identity that requested the active pause, from the audit trail (issue #383).
        pause_actor -> Nullable<Text>,
        /// Last-write-wins human-readable status string set by the workflow author
        /// via `ctx.set_current_details(...)` (issue #473). NULL = never set.
        current_details -> Nullable<Text>,
        /// Per-execution ambient context headers (issue #481). NULL = empty map.
        context_headers -> Nullable<Jsonb>,
        /// Optional declared SLA budget for soft breach signal (issue #487).
        /// Stored so continue-as-new / reset can re-anchor per run. NULL = no SLA.
        sla -> Nullable<Interval>,
        /// Absolute UTC deadline for soft SLA enforcement (issue #487).
        /// Computed at start as `started_at + sla`. NULL = no SLA declared.
        sla_deadline_at -> Nullable<Timestamptz>,
        /// Whether the soft SLA deadline has been breached (issue #487).
        /// Set exactly once by the scanner; never by the workflow engine.
        /// Leaves `harvest_events` untouched (zero replay footprint).
        sla_breached -> Bool,
        /// Wall-clock instant the SLA was first detected as breached (issue #487).
        /// `NULL` when `sla_breached = false`.
        sla_breached_at -> Nullable<Timestamptz>,
        /// Schedule that fired this execution (issue #488). NULL for manual starts.
        /// Used to resolve the last-completion-result carryover at workflow start time.
        schedule_id -> Nullable<Uuid>,
        /// The logical schedule slot this run fires for (issue #488). Carryover is
        /// ordered by this rather than `completed_at` so out-of-order completions can't
        /// roll an incremental cursor backward. NULL for non-scheduled executions.
        scheduled_for -> Nullable<Timestamptz>,
        /// Attempt number of this execution in its retry chain (issue #523). 1 = first attempt.
        /// Default 1 for pre-migration rows.
        workflow_attempt -> Int4,
        /// Frozen effective retry policy for this execution (issue #523). NULL = no auto-retry.
        workflow_retry_policy -> Nullable<Jsonb>,
        /// ID of the previous failed execution in this retry chain (issue #523). NULL for first attempt.
        retry_of_exec_id -> Nullable<Uuid>,
        /// Dispatch origin of this execution (issue #534): `scheduled` / `backfill` /
        /// `manual_trigger` for schedule-attributed runs, NULL for all non-scheduled runs
        /// (manual start, signal-with-start, child workflows, etc.). Metadata only —
        /// never affects replay or carryover.
        origin -> Nullable<Text>,
        /// Wall-clock of the most recent replay-non-determinism block observation
        /// (issue #603). NULL = not blocked. State stays RUNNING while blocked.
        nd_blocked_at -> Nullable<Timestamptz>,
        /// Divergence error string from the most recent blocked cycle (issue #603).
        nd_block_reason -> Nullable<Text>,
        /// Consecutive block entries for the current divergence incident (issue
        /// #603). Drives the re-dispatch backoff; reset to 0 on a clean cycle.
        nd_block_count -> Int4,
        /// Per-execution completion-callback targets (issue #605): a JSON array
        /// of `{url, filter}` objects. NULL = no per-execution targets; the
        /// effective set is still the union with any builder-wide defaults,
        /// resolved at enqueue time (not stored on this row).
        completion_callbacks -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_events (id) {
        id -> Int8,
        workflow_exec_id -> Uuid,
        event_id -> Int4,
        event_type -> Text,
        event_data -> Jsonb,
        timestamp -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_task_queue (id) {
        id -> Uuid,
        queue_name -> Text,
        task_type -> Text,
        workflow_exec_id -> Nullable<Uuid>,
        activity_name -> Nullable<Text>,
        activity_id -> Nullable<Uuid>,
        input -> Jsonb,
        state -> Text,
        priority -> Int4,
        worker_id -> Nullable<Text>,
        attempt -> Int4,
        max_attempts -> Int4,
        scheduled_at -> Timestamptz,
        started_at -> Nullable<Timestamptz>,
        completed_at -> Nullable<Timestamptz>,
        last_heartbeat_at -> Nullable<Timestamptz>,
        heartbeat_details -> Nullable<Jsonb>,
        heartbeat_timeout -> Nullable<Interval>,
        start_to_close -> Nullable<Interval>,
        schedule_to_start -> Nullable<Interval>,
        retry_policy -> Nullable<Jsonb>,
        output -> Nullable<Jsonb>,
        error -> Nullable<Text>,
        sticky_worker_id -> Nullable<Text>,
        sticky_until -> Nullable<Timestamptz>,
        sticky_timeout -> Nullable<Interval>,
        trace_context -> Nullable<Jsonb>,
        concurrency_key -> Nullable<Text>,
        concurrency_cap -> Nullable<Int4>,
        /// Build ID required to claim this task (issue #171). NULL = any worker.
        required_build_id -> Nullable<Text>,
        rate_limit_key -> Nullable<Text>,
        /// Number of times this task was reclaimed from a dead worker without
        /// completing (issue #367). Quarantined to the DLQ once it reaches the
        /// operator-configured poison-pill threshold. Distinct from `attempt`.
        crash_strikes -> Int4,
        /// Absolute UTC deadline for the entire activity lifecycle across all retry
        /// attempts (issue #378). Computed once at initial enqueue as
        /// `NOW() + schedule_to_close`. NULL = no total deadline enforced.
        schedule_to_close_at -> Nullable<Timestamptz>,
        /// Structured capability requirements JSONB payload (issue #382).
        required_capabilities -> Nullable<Jsonb>,
        /// Per-execution ambient context headers propagated from the parent workflow (issue #481).
        context_headers -> Nullable<Jsonb>,
        /// Row insert time (issue #501 review). Nullable: pre-upgrade rows are NULL
        /// and the schedule-to-start SLI falls back to `scheduled_at` via COALESCE.
        created_at -> Nullable<Timestamptz>,
        /// Durable "please wake this task" flag (dropped-wake fix, issue #601 CI
        /// hardening). Set by `wake_workflow_task` when its primary re-pend UPDATE
        /// matches zero rows because the row is currently claimed and mid-processing
        /// (`state = 'RUNNING'`, `worker_id IS NOT NULL`) -- the wake would otherwise
        /// be silently dropped. Read-and-cleared by `park_workflow_task` so a park
        /// racing a same-cycle wake immediately re-pends instead of parking.
        wake_requested -> Bool,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_calendars (id) {
        id -> Uuid,
        name -> Text,
        description -> Nullable<Text>,
        /// `true` for built-in calendars that operators cannot delete.
        built_in -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_calendar_exclusions (id) {
        id -> Uuid,
        calendar_name -> Text,
        excluded_date -> Date,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_schedules (id) {
        id -> Uuid,
        dag_name -> Nullable<Text>,
        schedule_expr -> Nullable<Text>,
        timezone -> Text,
        catchup -> Bool,
        max_active_runs -> Int4,
        is_paused -> Bool,
        last_run_at -> Nullable<Timestamptz>,
        next_run_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        workflow_name -> Nullable<Text>,
        workflow_input -> Nullable<Jsonb>,
        queue_name -> Nullable<Text>,
        paused_at -> Nullable<Timestamptz>,
        paused_by -> Nullable<Text>,
        pause_reason -> Nullable<Text>,
        jitter_secs -> Int8,
        /// Overlap policy variant for this schedule (issue #241).
        overlap_policy -> Text,
        /// Durable buffered fire times for `BufferOne`/`BufferAll` (issue #241).
        buffered_runs -> Jsonb,
        /// Maximum buffered slots under `BufferAll` (issue #241).
        buffer_all_max -> Int4,
        /// Optional named calendar for this schedule (issue #337). NULL = no filtering.
        calendar_name -> Nullable<Text>,
        /// What to do when the fire date is calendar-excluded (issue #337).
        skip_policy -> Text,
        /// Token held by the replica that claimed this slot for firing (issue #350).
        /// NULL means no replica currently holds a claim on this schedule row.
        fire_claim_token -> Nullable<Uuid>,
        /// Absolute UTC expiry of the current fire claim (issue #350).
        /// When `fire_claimed_until < NOW()` the claim is expired and any replica
        /// may re-claim the slot (crash-recovery path).
        fire_claimed_until -> Nullable<Timestamptz>,
        /// Number of consecutive failures required before the schedule auto-pauses
        /// (issue #360). NULL = auto-pause disabled (existing behaviour).
        consecutive_failure_limit -> Nullable<Int4>,
        /// Running count of consecutive schedule-triggered execution failures.
        /// Incremented by the worker completion path on `FAILED`/`TIMED_OUT`;
        /// reset to 0 on `COMPLETED` or on operator resume. Default 0.
        consecutive_failure_count -> Int4,
        /// Set to `NOW()` when `consecutive_failure_count` reaches `consecutive_failure_limit`.
        /// NULL = schedule is not auto-paused.
        auto_paused_at -> Nullable<Timestamptz>,
        /// Absolute UTC cutoff for this schedule (issue #478).
        /// When `next_run_at >= end_at`, no further runs are started and the
        /// schedule is transitioned to the exhausted state. NULL = no cutoff.
        end_at -> Nullable<Timestamptz>,
        /// Total run budget (issue #478). Once `runs_started` reaches this value
        /// the schedule is exhausted and stops firing. NULL = no budget limit.
        max_runs -> Nullable<Int4>,
        /// Monotonically-increasing count of executions actually started by this
        /// schedule (issue #478). Only incremented when a run is truly dispatched —
        /// skipped firings (overlap, calendar, pause) do NOT increment this counter.
        runs_started -> Int4,
        /// Set to `NOW()` when the schedule transitions to the exhausted state
        /// (issue #478). NULL = schedule is still active (not exhausted).
        exhausted_at -> Nullable<Timestamptz>,
        /// Machine-readable reason for exhaustion (issue #478).
        /// One of: `"end_at_reached"`, `"max_runs_exhausted"`. NULL when not exhausted.
        exhausted_reason -> Nullable<Text>,
        /// Catchup policy discriminator for missed fire slots (issue #484).
        /// One of: `"skip_all"`, `"most_recent"`, `"window"`, `"unbounded"`.
        /// NULL means the legacy `catchup` bool drives behaviour (zero backfill).
        catchup_policy -> Nullable<Text>,
        /// Window duration in seconds for the `"window"` catchup policy (issue #484).
        /// NULL for all other policies.
        catchup_window_secs -> Nullable<Int8>,
        /// Count of missed slots dropped on the most recent recovery tick (issue #484).
        /// 0 when no recovery has occurred or the policy is SkipAll/Unbounded.
        last_catchup_dropped -> Int4,
        /// Timestamp of the most recent recovery tick that produced drops (issue #484).
        /// NULL when `last_catchup_dropped` = 0.
        last_catchup_at -> Nullable<Timestamptz>,
        /// Default retry policy for runs started by this schedule (issue #523). NULL = no retry.
        retry_policy -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_signals (id) {
        id -> Uuid,
        workflow_exec_id -> Uuid,
        signal_name -> Text,
        payload -> Jsonb,
        received_at -> Timestamptz,
        consumed -> Bool,
        /// Optional dedup key for `SignalWithStart` (issue #244). When
        /// present, a partial unique index over
        /// (`workflow_exec_id`, `idempotency_key`) rejects duplicate inserts
        /// so upstream webhook retries land exactly one `SignalReceived` event.
        idempotency_key -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_timers (id) {
        id -> Uuid,
        workflow_exec_id -> Uuid,
        timer_id -> Text,
        fires_at -> Timestamptz,
        fired -> Bool,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_dead_letters (id) {
        id -> Uuid,
        original_task_id -> Uuid,
        queue_name -> Text,
        task_type -> Text,
        workflow_exec_id -> Nullable<Uuid>,
        activity_name -> Nullable<Text>,
        input -> Jsonb,
        error -> Text,
        attempts -> Int4,
        failed_at -> Timestamptz,
        owner -> Nullable<Text>,
        severity -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_external_tasks (id) {
        id -> Uuid,
        token -> Uuid,
        workflow_exec_id -> Uuid,
        activity_id -> Uuid,
        name -> Text,
        queue -> Text,
        state -> Text,
        schedule_to_close_at -> Timestamptz,
        schedule_to_close_secs -> Int8,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_workers (worker_id) {
        worker_id -> Text,
        started_at -> Timestamptz,
        last_heartbeat_at -> Timestamptz,
        queues -> Jsonb,
        shard_assignments -> Jsonb,
        max_concurrency -> Int4,
        in_flight_count -> Int4,
        host -> Text,
        version -> Nullable<Text>,
        status -> Text,
        drain_deadline_at -> Nullable<Timestamptz>,
        /// Immutable build identifier advertised by this worker (issue #171).
        build_id -> Text,
        /// Optional human-readable deployment name (issue #171).
        deployment_name -> Nullable<Text>,
        labels -> Jsonb,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_build_policies (id) {
        id -> Uuid,
        queue_name -> Text,
        build_id -> Text,
        deployment_name -> Nullable<Text>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        target_build_id -> Nullable<Text>,
        ramp_percent -> Nullable<Integer>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_build_compat (id) {
        id -> Uuid,
        build_id -> Text,
        compatible_with -> Text,
        declared_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_batch_jobs (id) {
        id -> Uuid,
        action -> Text,
        filter -> Jsonb,
        signal_name -> Nullable<Text>,
        signal_payload -> Nullable<Jsonb>,
        status -> Text,
        total -> Int8,
        completed -> Int8,
        failed -> Int8,
        errors -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        started_at -> Nullable<Timestamptz>,
        completed_at -> Nullable<Timestamptz>,
        idempotency_key -> Nullable<Text>,
        created_by -> Nullable<Text>,
        processed_ids -> Jsonb,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_audit_log (id) {
        id -> Uuid,
        occurred_at -> Timestamptz,
        actor -> Text,
        operation -> Text,
        target_type -> Text,
        target_id -> Nullable<Text>,
        route_or_command -> Text,
        request_id -> Nullable<Text>,
        idempotency_key -> Nullable<Text>,
        status -> Text,
        error_summary -> Nullable<Text>,
        shard_id -> Nullable<Int4>,
        source -> Text,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_backfill_log (id) {
        id -> Uuid,
        schedule_id -> Uuid,
        actor -> Text,
        source -> Text,
        from_ts -> Timestamptz,
        to_ts -> Timestamptz,
        dry_run -> Bool,
        total -> Int4,
        dispatched -> Int4,
        skipped -> Int4,
        failed -> Int4,
        status -> Text,
        error_summary -> Nullable<Text>,
        started_at -> Timestamptz,
        completed_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_schedule_decisions (id) {
        id -> Uuid,
        schedule_id -> Nullable<Uuid>,
        schedule_name -> Text,
        target_kind -> Text,
        decision -> Text,
        reason_code -> Text,
        detail -> Nullable<Jsonb>,
        occurred_at -> Timestamptz,
        next_fire_at -> Timestamptz,
        shard_id -> Int2,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_rate_limit_buckets (key) {
        key -> Text,
        refill_rate -> Double,
        burst -> Double,
        tokens -> Double,
        last_refilled_at -> Timestamptz,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_completion_triggers (id) {
        id -> Uuid,
        source_workflow_name -> Text,
        terminal_states -> Jsonb,
        target_workflow_name -> Text,
        input_mapping -> Jsonb,
        queue_name -> Nullable<Text>,
        is_static -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_completion_trigger_fires (source_exec_id, trigger_id) {
        source_exec_id -> Uuid,
        trigger_id -> Uuid,
        fired_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_completion_trigger_outbox (id) {
        id -> Uuid,
        source_exec_id -> Uuid,
        trigger_id -> Uuid,
        target_shard -> Integer,
        target_workflow_name -> Text,
        target_workflow_id -> Text,
        target_input -> Jsonb,
        queue_name -> Nullable<Text>,
        concurrency_key -> Nullable<Text>,
        concurrency_limit -> Nullable<Integer>,
        priority -> Jsonb,
        max_workflow_input_bytes -> BigInt,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Admission gates that halt new workflow starts for a scoped subset of work (issue #377).
    harvest_admission_gates (id) {
        id -> Uuid,
        /// Scope kind: `fleet` | `workflow_name` | `queue` | `shard_id` | `owner`
        scope_kind -> Text,
        /// Scope value: NULL for fleet; specific value for all other kinds.
        scope_value -> Nullable<Text>,
        reason -> Text,
        message -> Nullable<Text>,
        created_by -> Text,
        created_at -> Timestamptz,
        expires_at -> Nullable<Timestamptz>,
        lifted_at -> Nullable<Timestamptz>,
        lifted_by -> Nullable<Text>,
    }
}

diesel::joinable!(harvest_events -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_task_queue -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_signals -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_timers -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_external_tasks -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_schedule_decisions -> harvest_schedules (schedule_id));
// harvest_calendar_exclusions references harvest_calendars(name), not the PK(id),
// so diesel::joinable! cannot be used here. Queries use explicit filter conditions.

diesel::table! {
    use diesel::sql_types::*;

    /// Pending debounce records — one row per `(workflow_name, debounce_key)` (issue #499).
    harvest_debounce (id) {
        id                -> Uuid,
        workflow_name     -> Text,
        debounce_key      -> Text,
        workflow_id       -> Text,
        queue_name        -> Text,
        /// Most recent qualifying request's input (last-input-wins on each upsert).
        last_input        -> Jsonb,
        /// Serialised start options (`reuse_policy`, timeouts, memo, etc.) — opaque JSONB.
        start_options     -> Jsonb,
        /// Trailing-edge fire deadline: `LEAST(now + window, max_fire_at)`. Recomputed on each upsert.
        effective_fire_at -> Timestamptz,
        /// Absolute cap: `first_seen + max_wait`. Set once at insert; never updated.
        max_fire_at       -> Timestamptz,
        /// Count of qualifying start requests seen since the record was created.
        pending_count     -> Int4,
        /// Shard this record was routed to (for operator visibility).
        shard_id          -> Int4,
        created_at        -> Timestamptz,
        updated_at        -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Pending event batch records — one row per `(workflow_name, batch_key)` (issue #518).
    harvest_event_batches (id) {
        id                -> Uuid,
        workflow_name     -> Text,
        batch_key         -> Text,
        workflow_id       -> Text,
        queue_name        -> Text,
        buffered_payloads -> Jsonb,
        start_options     -> Jsonb,
        fire_at           -> Timestamptz,
        max_size          -> Int4,
        shard_id          -> Int4,
        created_at        -> Timestamptz,
        updated_at        -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Per-execution references to offloaded payload blobs (issue #524).
    ///
    /// One row per `(blob_key, workflow_exec_id)`. `ON DELETE CASCADE` ties the
    /// reference count to execution lifetime so the retention sweep can GC a
    /// blob exactly when its last referencing execution is collected.
    harvest_payload_refs (blob_key, workflow_exec_id) {
        blob_key         -> Text,
        workflow_exec_id -> Uuid,
        store_id         -> Text,
        byte_len         -> Int8,
        created_at       -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Durable completion-callback delivery rows (issue #605). One row per
    /// `(workflow_exec_id, callback_index)`, enqueued inside the terminal
    /// transaction and drained by `fire_due_completion_deliveries`.
    harvest_completion_deliveries (id) {
        id               -> Uuid,
        workflow_exec_id -> Uuid,
        shard_id         -> Int4,
        callback_index   -> Int4,
        workflow_name    -> Text,
        workflow_id      -> Text,
        target_url       -> Text,
        event_filter     -> Jsonb,
        terminal_state   -> Text,
        /// Frozen `CompletionEnvelope` JSON, signed and `POSTed` verbatim on
        /// every attempt (including redeliveries).
        payload          -> Jsonb,
        /// PENDING | INFLIGHT | DELIVERED | FAILED
        state            -> Text,
        attempt          -> Int4,
        max_attempts     -> Int4,
        /// Frozen `RetryPolicy` at enqueue time.
        retry_policy     -> Jsonb,
        next_attempt_at  -> Timestamptz,
        last_status      -> Nullable<Int4>,
        last_error       -> Nullable<Text>,
        created_at       -> Timestamptz,
        updated_at       -> Timestamptz,
        delivered_at     -> Nullable<Timestamptz>,
    }
}

diesel::joinable!(harvest_completion_deliveries -> harvest_workflow_executions (workflow_exec_id));

diesel::allow_tables_to_appear_in_same_query!(
    harvest_workflow_executions,
    harvest_events,
    harvest_task_queue,
    harvest_schedules,
    harvest_signals,
    harvest_timers,
    harvest_dead_letters,
    harvest_external_tasks,
    harvest_workers,
    harvest_batch_jobs,
    harvest_audit_log,
    harvest_build_policies,
    harvest_build_compat,
    harvest_backfill_log,
    harvest_calendars,
    harvest_calendar_exclusions,
    harvest_schedule_decisions,
    harvest_rate_limit_buckets,
    harvest_completion_triggers,
    harvest_completion_trigger_fires,
    harvest_completion_trigger_outbox,
    harvest_debounce,
    harvest_event_batches,
    harvest_payload_refs,
    harvest_completion_deliveries,
);
