// autumn-harvest/src/schema.rs
// Hand-written to match migrations/20260409000000_harvest_initial/up.sql.
// Keep in sync with the migration. In production, regenerate via `diesel print-schema`.
//! Database schema definitions generated by Diesel.
//!
//! This module contains the `diesel::table!` macros mapping Rust types to the PostgreSQL
//! schema defined in the `migrations` directory. It acts as the bridge between the database
//! tables and Diesel's strongly-typed query builder.

diesel::table! {
    use diesel::sql_types::*;

    harvest_workflow_executions (id) {
        id -> Uuid,
        workflow_name -> Text,
        workflow_id -> Text,
        run_id -> Uuid,
        shard_id -> Int4,
        state -> Text,
        input -> Jsonb,
        output -> Nullable<Jsonb>,
        error -> Nullable<Text>,
        parent_id -> Nullable<Uuid>,
        sticky_worker_id -> Nullable<Text>,
        queue_name -> Text,
        started_at -> Timestamptz,
        completed_at -> Nullable<Timestamptz>,
        execution_timeout -> Nullable<Interval>,
        /// Absolute UTC deadline for execution-level timeout (issue #243).
        /// Computed at start as `started_at + execution_timeout`. NULL = no deadline.
        deadline_at -> Nullable<Timestamptz>,
        memo -> Nullable<Jsonb>,
        search_attrs -> Nullable<Jsonb>,
        created_at -> Timestamptz,
        /// Build ID assigned to this execution at start time (issue #171).
        assigned_build_id -> Nullable<Text>,
        /// Parent-close policy for detached children (issue #347). NULL for awaited children.
        parent_close_policy -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_events (id) {
        id -> Int8,
        workflow_exec_id -> Uuid,
        event_id -> Int4,
        event_type -> Text,
        event_data -> Jsonb,
        timestamp -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_task_queue (id) {
        id -> Uuid,
        queue_name -> Text,
        task_type -> Text,
        workflow_exec_id -> Nullable<Uuid>,
        activity_name -> Nullable<Text>,
        activity_id -> Nullable<Uuid>,
        input -> Jsonb,
        state -> Text,
        priority -> Int4,
        worker_id -> Nullable<Text>,
        attempt -> Int4,
        max_attempts -> Int4,
        scheduled_at -> Timestamptz,
        started_at -> Nullable<Timestamptz>,
        completed_at -> Nullable<Timestamptz>,
        last_heartbeat_at -> Nullable<Timestamptz>,
        heartbeat_details -> Nullable<Jsonb>,
        heartbeat_timeout -> Nullable<Interval>,
        start_to_close -> Nullable<Interval>,
        schedule_to_start -> Nullable<Interval>,
        retry_policy -> Nullable<Jsonb>,
        output -> Nullable<Jsonb>,
        error -> Nullable<Text>,
        sticky_worker_id -> Nullable<Text>,
        sticky_until -> Nullable<Timestamptz>,
        sticky_timeout -> Nullable<Interval>,
        trace_context -> Nullable<Jsonb>,
        concurrency_key -> Nullable<Text>,
        concurrency_cap -> Nullable<Int4>,
        /// Build ID required to claim this task (issue #171). NULL = any worker.
        required_build_id -> Nullable<Text>,
        rate_limit_key -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_calendars (id) {
        id -> Uuid,
        name -> Text,
        description -> Nullable<Text>,
        /// `true` for built-in calendars that operators cannot delete.
        built_in -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_calendar_exclusions (id) {
        id -> Uuid,
        calendar_name -> Text,
        excluded_date -> Date,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_schedules (id) {
        id -> Uuid,
        dag_name -> Nullable<Text>,
        schedule_expr -> Nullable<Text>,
        timezone -> Text,
        catchup -> Bool,
        max_active_runs -> Int4,
        is_paused -> Bool,
        last_run_at -> Nullable<Timestamptz>,
        next_run_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        workflow_name -> Nullable<Text>,
        workflow_input -> Nullable<Jsonb>,
        queue_name -> Nullable<Text>,
        paused_at -> Nullable<Timestamptz>,
        paused_by -> Nullable<Text>,
        pause_reason -> Nullable<Text>,
        jitter_secs -> Int8,
        /// Overlap policy variant for this schedule (issue #241).
        overlap_policy -> Text,
        /// Durable buffered fire times for `BufferOne`/`BufferAll` (issue #241).
        buffered_runs -> Jsonb,
        /// Maximum buffered slots under `BufferAll` (issue #241).
        buffer_all_max -> Int4,
        /// Optional named calendar for this schedule (issue #337). NULL = no filtering.
        calendar_name -> Nullable<Text>,
        /// What to do when the fire date is calendar-excluded (issue #337).
        skip_policy -> Text,
        /// Token held by the replica that claimed this slot for firing (issue #350).
        /// NULL means no replica currently holds a claim on this schedule row.
        fire_claim_token -> Nullable<Uuid>,
        /// Absolute UTC expiry of the current fire claim (issue #350).
        /// When `fire_claimed_until < NOW()` the claim is expired and any replica
        /// may re-claim the slot (crash-recovery path).
        fire_claimed_until -> Nullable<Timestamptz>,
        /// Number of consecutive failures required before the schedule auto-pauses
        /// (issue #360). NULL = auto-pause disabled (existing behaviour).
        consecutive_failure_limit -> Nullable<Int4>,
        /// Running count of consecutive schedule-triggered execution failures.
        /// Incremented by the worker completion path on `FAILED`/`TIMED_OUT`;
        /// reset to 0 on `COMPLETED` or on operator resume. Default 0.
        consecutive_failure_count -> Int4,
        /// Set to `NOW()` when `consecutive_failure_count` reaches `consecutive_failure_limit`.
        /// NULL = schedule is not auto-paused.
        auto_paused_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_signals (id) {
        id -> Uuid,
        workflow_exec_id -> Uuid,
        signal_name -> Text,
        payload -> Jsonb,
        received_at -> Timestamptz,
        consumed -> Bool,
        /// Optional dedup key for `SignalWithStart` (issue #244). When
        /// present, a partial unique index over
        /// (`workflow_exec_id`, `idempotency_key`) rejects duplicate inserts
        /// so upstream webhook retries land exactly one `SignalReceived` event.
        idempotency_key -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_timers (id) {
        id -> Uuid,
        workflow_exec_id -> Uuid,
        timer_id -> Text,
        fires_at -> Timestamptz,
        fired -> Bool,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_dead_letters (id) {
        id -> Uuid,
        original_task_id -> Uuid,
        queue_name -> Text,
        task_type -> Text,
        workflow_exec_id -> Nullable<Uuid>,
        activity_name -> Nullable<Text>,
        input -> Jsonb,
        error -> Text,
        attempts -> Int4,
        failed_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_external_tasks (id) {
        id -> Uuid,
        token -> Uuid,
        workflow_exec_id -> Uuid,
        activity_id -> Uuid,
        name -> Text,
        queue -> Text,
        state -> Text,
        schedule_to_close_at -> Timestamptz,
        schedule_to_close_secs -> Int8,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_workers (worker_id) {
        worker_id -> Text,
        started_at -> Timestamptz,
        last_heartbeat_at -> Timestamptz,
        queues -> Jsonb,
        shard_assignments -> Jsonb,
        max_concurrency -> Int4,
        in_flight_count -> Int4,
        host -> Text,
        version -> Nullable<Text>,
        status -> Text,
        drain_deadline_at -> Nullable<Timestamptz>,
        /// Immutable build identifier advertised by this worker (issue #171).
        build_id -> Text,
        /// Optional human-readable deployment name (issue #171).
        deployment_name -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_build_policies (id) {
        id -> Uuid,
        queue_name -> Text,
        build_id -> Text,
        deployment_name -> Nullable<Text>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_build_compat (id) {
        id -> Uuid,
        build_id -> Text,
        compatible_with -> Text,
        declared_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_batch_jobs (id) {
        id -> Uuid,
        action -> Text,
        filter -> Jsonb,
        signal_name -> Nullable<Text>,
        signal_payload -> Nullable<Jsonb>,
        status -> Text,
        total -> Int8,
        completed -> Int8,
        failed -> Int8,
        errors -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        started_at -> Nullable<Timestamptz>,
        completed_at -> Nullable<Timestamptz>,
        idempotency_key -> Nullable<Text>,
        created_by -> Nullable<Text>,
        processed_ids -> Jsonb,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_audit_log (id) {
        id -> Uuid,
        occurred_at -> Timestamptz,
        actor -> Text,
        operation -> Text,
        target_type -> Text,
        target_id -> Nullable<Text>,
        route_or_command -> Text,
        request_id -> Nullable<Text>,
        idempotency_key -> Nullable<Text>,
        status -> Text,
        error_summary -> Nullable<Text>,
        shard_id -> Nullable<Int4>,
        source -> Text,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_backfill_log (id) {
        id -> Uuid,
        schedule_id -> Uuid,
        actor -> Text,
        source -> Text,
        from_ts -> Timestamptz,
        to_ts -> Timestamptz,
        dry_run -> Bool,
        total -> Int4,
        dispatched -> Int4,
        skipped -> Int4,
        failed -> Int4,
        status -> Text,
        error_summary -> Nullable<Text>,
        started_at -> Timestamptz,
        completed_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_schedule_decisions (id) {
        id -> Uuid,
        schedule_id -> Nullable<Uuid>,
        schedule_name -> Text,
        target_kind -> Text,
        decision -> Text,
        reason_code -> Text,
        detail -> Nullable<Jsonb>,
        occurred_at -> Timestamptz,
        next_fire_at -> Timestamptz,
        shard_id -> Int2,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    harvest_rate_limit_buckets (key) {
        key -> Text,
        refill_rate -> Double,
        burst -> Double,
        tokens -> Double,
        last_refilled_at -> Timestamptz,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(harvest_events -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_task_queue -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_signals -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_timers -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_external_tasks -> harvest_workflow_executions (workflow_exec_id));
diesel::joinable!(harvest_schedule_decisions -> harvest_schedules (schedule_id));
// harvest_calendar_exclusions references harvest_calendars(name), not the PK(id),
// so diesel::joinable! cannot be used here. Queries use explicit filter conditions.

diesel::allow_tables_to_appear_in_same_query!(
    harvest_workflow_executions,
    harvest_events,
    harvest_task_queue,
    harvest_schedules,
    harvest_signals,
    harvest_timers,
    harvest_dead_letters,
    harvest_external_tasks,
    harvest_workers,
    harvest_batch_jobs,
    harvest_audit_log,
    harvest_build_policies,
    harvest_build_compat,
    harvest_backfill_log,
    harvest_calendars,
    harvest_calendar_exclusions,
    harvest_schedule_decisions,
    harvest_rate_limit_buckets,
);
