//! Characterizes `WorkflowInfo::reject_if_admission_may_defer`: the typed-
//! client pre-check shared by `start_with_options`, `signal_with_start`
//! (both generated by `#[workflow]`), and `update_with_start_*` (generated
//! by `#[update]`).
//!
//! All three must reject a call against a throttled workflow with the same
//! `HarvestError::Config` the debounce/batch cases already got. Before the
//! shared check existed, `update_with_start_*` hand-carried its own copy of
//! this guard and that copy omitted the throttle case -- the same
//! missed-fix class as commit 896978eb (issue #617): a fix applied to some
//! copies of duplicated logic and missed in another. This file pins the now-
//! unified behavior so a future edit to the check cannot silently regress
//! one call site while fixing the others.
#![cfg(feature = "db")]
#![allow(clippy::all, clippy::pedantic, clippy::nursery)]

use serde::{Deserialize, Serialize};

use autumn_harvest::error::HarvestError;
use autumn_harvest::worker::DbPool;
use autumn_harvest::{
    TypedSignalWithStartOptions, TypedStartOptions, TypedUpdateWithStartOptions,
    WorkflowHandleClient,
};
use diesel_async::AsyncPgConnection;
use diesel_async::pooled_connection::AsyncDieselConnectionManager;
use testcontainers::ContainerAsync;
use testcontainers::ImageExt;
use testcontainers_modules::postgres::Postgres;
use testcontainers_modules::testcontainers::runners::AsyncRunner;

use autumn_harvest::prelude::*;

fn init_sql() -> Vec<u8> {
    autumn_harvest::test_init_sql().as_bytes().to_vec()
}

/// Prefer an operator-supplied database and fall back to testcontainers,
/// mirroring `scanner_tick_db_tests.rs`.
async fn setup_database_url() -> (String, Option<ContainerAsync<Postgres>>) {
    if let Ok(url) = std::env::var("HARVEST_TEST_DATABASE_URL") {
        use diesel_async::{AsyncConnection, SimpleAsyncConnection};
        let mut conn = AsyncPgConnection::establish(&url)
            .await
            .expect("HARVEST_TEST_DATABASE_URL must be reachable");
        let already_migrated = conn
            .batch_execute("SELECT 1 FROM harvest_workflow_executions LIMIT 0")
            .await
            .is_ok();
        if !already_migrated {
            let mut fresh = AsyncPgConnection::establish(&url)
                .await
                .expect("HARVEST_TEST_DATABASE_URL must be reachable");
            fresh
                .batch_execute(&autumn_harvest::test_init_sql())
                .await
                .expect("migrations should apply");
        }
        return (url, None);
    }

    let container = Postgres::default()
        .with_init_sql(init_sql())
        .with_tag("16")
        .start()
        .await
        .expect("failed to start Postgres container");
    let host = container.get_host().await.expect("container host");
    let port = container
        .get_host_port_ipv4(5432)
        .await
        .expect("container postgres port");
    (
        format!("postgres://postgres:postgres@{host}:{port}/postgres"),
        Some(container),
    )
}

fn build_pool(database_url: &str) -> DbPool {
    let manager = AsyncDieselConnectionManager::<AsyncPgConnection>::new(database_url);
    deadpool::managed::Pool::builder(manager)
        .max_size(4)
        .build()
        .expect("test pool should build")
}

// ── Test Workflow Declaration ───────────────────────────────────────────────
//
// An unkeyed (global) throttle always applies (issue #607's `key_expr:
// None` branch), so these tests need no JSON input shape to trigger the
// rejection -- unlike debounce/batch, already covered indirectly by every
// debounced/batched workflow's existing tests elsewhere in this suite.

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
struct ThrottledInput {
    tenant_id: i64,
}

#[workflow(throttle(rate = "5/s", burst = 2))]
async fn throttled_workflow(ctx: &WorkflowContext, input: ThrottledInput) -> Result<i64, String> {
    let _ = ctx.wait_for_signal("go").await;
    Ok(input.tenant_id)
}

#[update(workflow = "throttled_workflow")]
async fn bump(_ctx: &WorkflowContext, by: i64) -> Result<i64, String> {
    Ok(by)
}

#[allow(dead_code)]
#[signal(workflow = "throttled_workflow")]
fn go(_ctx: &WorkflowContext, _val: i64) {}

fn assert_rejects_as_throttled<T>(result: &Result<T, HarvestError>)
where
    T: std::fmt::Debug,
{
    let err = result.as_ref().expect_err("expected a rejection");
    assert!(
        matches!(err, HarvestError::Config(msg) if msg.contains("has a start-throttle policy")),
        "expected a start-throttle Config rejection, got: {err:?}"
    );
}

#[tokio::test]
async fn start_with_options_rejects_a_throttled_workflow() {
    let (db_url, _container) = setup_database_url().await;
    let pool = build_pool(&db_url);
    let mut conn = pool.get().await.unwrap();
    let client = WorkflowHandleClient::single(pool, db_url.clone());

    let input = ThrottledInput { tenant_id: 1 };
    let result = ThrottledWorkflowStub::start_with_options(
        &mut conn,
        &client,
        "throttled-swo-1",
        input,
        TypedStartOptions::default(),
    )
    .await
    .map(|_| ());

    assert_rejects_as_throttled(&result);
}

#[tokio::test]
async fn signal_with_start_rejects_a_throttled_workflow() {
    let (db_url, _container) = setup_database_url().await;
    let pool = build_pool(&db_url);
    let mut conn = pool.get().await.unwrap();
    let client = WorkflowHandleClient::single(pool, db_url.clone());

    let input = ThrottledInput { tenant_id: 2 };
    let result = ThrottledWorkflowStub::signal_with_start(
        &mut conn,
        &client,
        "throttled-sws-1",
        input,
        "go",
        7,
        TypedSignalWithStartOptions::default(),
    )
    .await
    .map(|_| ());

    assert_rejects_as_throttled(&result);
}

/// The regression test: before `reject_if_admission_may_defer` was shared,
/// `update_with_start_*`'s hand-copied guard checked debounce and batch but
/// not throttle, so this call was silently admitted instead of rejected.
#[tokio::test]
async fn update_with_start_rejects_a_throttled_workflow() {
    let (db_url, _container) = setup_database_url().await;
    let pool = build_pool(&db_url);
    let mut conn = pool.get().await.unwrap();
    let client = WorkflowHandleClient::single(pool, db_url.clone());

    let input = ThrottledInput { tenant_id: 3 };
    let start_input = serde_json::to_value(&input).unwrap();
    let result = ThrottledWorkflowStub::update_with_start_bump(
        &mut conn,
        &client,
        "throttled-uws-1",
        start_input,
        5,
        TypedUpdateWithStartOptions::default(),
    )
    .await
    .map(|_| ());

    assert_rejects_as_throttled(&result);
}
