//! Tests for worker-session enqueue pinning and the hard-pin claim gate
//! (issue #606, TDD step 9).
//!
//! **Pure-logic tests (no live database connection required):**
//! `EnqueueParams::with_session_id` builder behavior. These still require
//! the `db` Cargo feature to compile, since `queue::EnqueueParams` itself
//! lives entirely behind `#[cfg(feature = "db")]` -- hence `#![cfg(feature =
//! "db")]` gating the whole file below, not just the `db_tests` submodule.
//!
//! **DB integration tests (bottom of file, testcontainers):** the
//! `session_id` column round-trips through `enqueue`, and `claim_task`'s
//! hard-pin gate -- unlike ordinary sticky routing, a session-tagged row is
//! claimable *only* by its pinned worker even after the (bookkeeping) sticky
//! lease has elapsed. Written RED-first; pass GREEN against the
//! implementation in `queue.rs`.
//!
//! Compile-checked only in this sandbox (no Docker/testcontainers available),
//! matching the #543/#544/#601 precedent documented in CLAUDE.md.
#![cfg(feature = "db")]

use autumn_harvest::queue::{EnqueueParams, TaskType};

// ---------------------------------------------------------------------------
// EnqueueParams::with_session_id (no DB required)
// ---------------------------------------------------------------------------

#[test]
fn enqueue_params_default_session_id_is_none() {
    let params = EnqueueParams::new("default", TaskType::Activity, serde_json::json!(null));
    assert_eq!(params.session_id, None);
}

#[test]
fn with_session_id_sets_the_field() {
    let session_id = uuid::Uuid::new_v4();
    let params = EnqueueParams::new("default", TaskType::Activity, serde_json::json!(null))
        .with_session_id(session_id);
    assert_eq!(params.session_id, Some(session_id));
}

#[test]
fn with_session_id_composes_with_with_sticky() {
    let session_id = uuid::Uuid::new_v4();
    let params = EnqueueParams::new("gpu-workers", TaskType::Activity, serde_json::json!(null))
        .with_session_id(session_id)
        .with_sticky("worker-42", std::time::Duration::from_secs(3600));
    assert_eq!(params.session_id, Some(session_id));
    assert_eq!(params.sticky_worker_id.as_deref(), Some("worker-42"));
}

// ---------------------------------------------------------------------------
// DB integration tests
// ---------------------------------------------------------------------------

#[cfg(feature = "db")]
mod db_tests {
    use autumn_harvest::models::NewWorkflowExecution;
    use autumn_harvest::queue::{self, EnqueueParams, TaskType};
    use autumn_harvest::schema::harvest_workflow_executions;
    use autumn_harvest::types::ExecutionId;
    use diesel::sql_types::{Nullable, Text, Timestamptz, Uuid as SqlUuid};
    use diesel_async::{AsyncConnection, AsyncPgConnection, RunQueryDsl};
    use std::time::Duration;
    use testcontainers::ContainerAsync;
    use testcontainers::ImageExt;
    use testcontainers_modules::postgres::Postgres;
    use testcontainers_modules::testcontainers::runners::AsyncRunner;
    use uuid::Uuid;

    // Same base schema as sticky_routing_tests.rs, plus the worker-sessions
    // migration under test.
    // Migration bundle: the paved-path helper `full_migrations_sql()`,
    // regenerated by build.rs from the whole `migrations/` directory.
    // Replaced a hand-rolled `concat!(include_str!(...))` list that had
    // drifted (missing `harvest_external_task_updated_at`, causing a
    // background-scanner `column ... does not exist` error) — invisible
    // because this suite was never run against a DB in CI (test-infra
    // hardening). The bundle can never drift again.
    fn init_sql() -> Vec<u8> {
        autumn_harvest::full_migrations_sql().as_bytes().to_vec()
    }

    async fn setup() -> (AsyncPgConnection, ContainerAsync<Postgres>) {
        let container = Postgres::default()
            .with_init_sql(init_sql())
            .with_tag("16")
            .start()
            .await
            .expect("failed to start Postgres container");
        let host = container.get_host().await.expect("host");
        let port = container.get_host_port_ipv4(5432).await.expect("port");
        let url = format!("postgres://postgres:postgres@{host}:{port}/postgres");
        let conn = AsyncPgConnection::establish(&url).await.expect("connect");
        (conn, container)
    }

    async fn insert_execution(conn: &mut AsyncPgConnection) -> ExecutionId {
        let exec_id = ExecutionId::new();
        let row = NewWorkflowExecution {
            continued_from_exec_id: None,
            first_exec_id: None,
            id: exec_id.as_uuid(),
            workflow_name: "session_test_wf",
            workflow_id: &Uuid::new_v4().to_string(),
            run_id: Uuid::new_v4(),
            shard_id: 0,
            input: serde_json::json!({}),
            parent_id: None,
            queue_name: "default",
            execution_timeout: None,
            deadline_at: None,
            memo: None,
            search_attrs: None,
            assigned_build_id: None,
            parent_close_policy: None,
            owner: None,
            runbook_url: None,
            severity: None,
            context_headers: None,
            sla: None,
            sla_deadline_at: None,
            schedule_id: None,
            scheduled_for: None,
            workflow_attempt: 1,
            workflow_retry_policy: None,
            retry_of_exec_id: None,
            origin: None,
            completion_callbacks: None,
            start_source: None,
            start_source_ref: None,
            started_by: None,
        };
        diesel::insert_into(harvest_workflow_executions::table)
            .values(&row)
            .execute(conn)
            .await
            .expect("insert execution");
        exec_id
    }

    #[derive(diesel::QueryableByName, Debug)]
    struct SessionColumns {
        #[diesel(sql_type = Nullable<SqlUuid>)]
        session_id: Option<Uuid>,
        #[diesel(sql_type = Nullable<Text>)]
        sticky_worker_id: Option<String>,
        #[diesel(sql_type = Nullable<Timestamptz>)]
        sticky_until: Option<chrono::DateTime<chrono::Utc>>,
    }

    async fn read_session_columns(conn: &mut AsyncPgConnection, task_id: Uuid) -> SessionColumns {
        diesel::sql_query(
            "SELECT session_id, sticky_worker_id, sticky_until \
             FROM harvest_task_queue WHERE id = $1",
        )
        .bind::<diesel::sql_types::Uuid, _>(task_id)
        .get_result(conn)
        .await
        .expect("read session columns")
    }

    /// Enqueueing with `with_session_id` + `with_sticky` writes both the
    /// `session_id` column and the ordinary sticky pin columns to the DB row.
    #[tokio::test]
    async fn enqueue_with_session_id_writes_column_to_db() {
        let (mut conn, _c) = setup().await;
        let exec_id = insert_execution(&mut conn).await;
        let session_id = Uuid::new_v4();

        let mut params =
            EnqueueParams::new("gpu-workers", TaskType::Activity, serde_json::json!(null));
        params.workflow_exec_id = Some(exec_id.as_uuid());
        let params = params
            .with_session_id(session_id)
            .with_sticky("worker-a", Duration::from_secs(3600));

        let task_id = queue::enqueue(&mut conn, &params).await.expect("enqueue");
        let cols = read_session_columns(&mut conn, task_id).await;

        assert_eq!(cols.session_id, Some(session_id));
        assert_eq!(cols.sticky_worker_id.as_deref(), Some("worker-a"));
    }

    /// A non-session task's `session_id` column is NULL -- the default,
    /// zero-behavior-change case (AC2).
    #[tokio::test]
    async fn enqueue_without_session_id_leaves_column_null() {
        let (mut conn, _c) = setup().await;
        let exec_id = insert_execution(&mut conn).await;

        let mut params = EnqueueParams::new("default", TaskType::Activity, serde_json::json!(null));
        params.workflow_exec_id = Some(exec_id.as_uuid());

        let task_id = queue::enqueue(&mut conn, &params).await.expect("enqueue");
        let cols = read_session_columns(&mut conn, task_id).await;

        assert_eq!(cols.session_id, None);
    }

    /// The hard-pin gate: the pinned worker can claim a session-tagged task.
    #[tokio::test]
    async fn session_worker_can_claim_its_pinned_task() {
        let (mut conn, _c) = setup().await;
        let exec_id = insert_execution(&mut conn).await;
        let session_id = Uuid::new_v4();

        let mut params =
            EnqueueParams::new("gpu-workers", TaskType::Activity, serde_json::json!(null));
        params.workflow_exec_id = Some(exec_id.as_uuid());
        params.activity_name = Some("transcode_chunk".to_string());
        let params = params
            .with_session_id(session_id)
            .with_sticky("worker-host", Duration::from_secs(3600));

        let task_id = queue::enqueue(&mut conn, &params).await.expect("enqueue");

        let claimed = queue::claim_task(
            &mut conn,
            &["gpu-workers".to_string()],
            "worker-host",
            "",
            None,
            &[],
            &[],
        )
        .await
        .expect("claim_task");

        assert!(
            claimed.is_some(),
            "the session's host worker must be able to claim its pinned task"
        );
        assert_eq!(claimed.unwrap().id, task_id);
    }

    /// The hard-pin gate: a non-pinned worker cannot claim a session-tagged
    /// task, even though it is otherwise eligible (same queue, no build
    /// restriction).
    #[tokio::test]
    async fn non_session_worker_cannot_claim_session_task() {
        let (mut conn, _c) = setup().await;
        let exec_id = insert_execution(&mut conn).await;
        let session_id = Uuid::new_v4();

        let mut params =
            EnqueueParams::new("gpu-workers", TaskType::Activity, serde_json::json!(null));
        params.workflow_exec_id = Some(exec_id.as_uuid());
        params.activity_name = Some("transcode_chunk".to_string());
        let params = params
            .with_session_id(session_id)
            .with_sticky("worker-host", Duration::from_secs(3600));

        queue::enqueue(&mut conn, &params).await.expect("enqueue");

        let claimed = queue::claim_task(
            &mut conn,
            &["gpu-workers".to_string()],
            "worker-imposter",
            "",
            None,
            &[],
            &[],
        )
        .await
        .expect("claim_task");

        assert!(
            claimed.is_none(),
            "a non-pinned worker must never claim a session-tagged task"
        );
    }

    /// THE headline hard-pin guarantee (distinguishing session pinning from
    /// ordinary sticky routing, issue #606): even after the sticky lease has
    /// elapsed, a session-tagged task still does NOT fail over to a
    /// different worker -- unlike plain sticky routing, where an expired
    /// lease makes the row claimable by anyone.
    #[tokio::test]
    async fn session_task_does_not_fail_over_after_sticky_lease_expires() {
        let (mut conn, _c) = setup().await;
        let exec_id = insert_execution(&mut conn).await;
        let session_id = Uuid::new_v4();

        let mut params =
            EnqueueParams::new("gpu-workers", TaskType::Activity, serde_json::json!(null));
        params.workflow_exec_id = Some(exec_id.as_uuid());
        params.activity_name = Some("transcode_chunk".to_string());
        // A sticky_timeout in the past: the lease has already "expired" by
        // the time we try to claim.
        let params = params
            .with_session_id(session_id)
            .with_sticky("worker-host", Duration::from_millis(1));

        queue::enqueue(&mut conn, &params).await.expect("enqueue");
        tokio::time::sleep(Duration::from_millis(50)).await;

        // A plain sticky (non-session) task with the same expired lease WOULD
        // be claimable by any worker at this point -- but this task carries
        // session_id, so the hard-pin gate must still exclude the imposter.
        let claimed_by_imposter = queue::claim_task(
            &mut conn,
            &["gpu-workers".to_string()],
            "worker-imposter",
            "",
            None,
            &[],
            &[],
        )
        .await
        .expect("claim_task");
        assert!(
            claimed_by_imposter.is_none(),
            "a session task must never fail over to a different worker, even \
             after its sticky lease has elapsed"
        );

        // The genuine host can still claim it.
        let claimed_by_host = queue::claim_task(
            &mut conn,
            &["gpu-workers".to_string()],
            "worker-host",
            "",
            None,
            &[],
            &[],
        )
        .await
        .expect("claim_task");
        assert!(
            claimed_by_host.is_some(),
            "the session's host worker must still be able to claim its task \
             after the (bookkeeping-only) sticky lease elapses"
        );
    }

    /// Sanity: an ordinary (non-session) sticky task DOES fail over after its
    /// lease expires -- confirms the test's premise and that the new gate
    /// doesn't accidentally change existing sticky-routing behavior.
    #[tokio::test]
    async fn non_session_sticky_task_does_fail_over_after_lease_expires() {
        let (mut conn, _c) = setup().await;
        let exec_id = insert_execution(&mut conn).await;

        let mut params =
            EnqueueParams::new("gpu-workers", TaskType::Activity, serde_json::json!(null));
        params.workflow_exec_id = Some(exec_id.as_uuid());
        params.activity_name = Some("transcode_chunk".to_string());
        let params = params.with_sticky("worker-host", Duration::from_millis(1));

        queue::enqueue(&mut conn, &params).await.expect("enqueue");
        tokio::time::sleep(Duration::from_millis(50)).await;

        let claimed = queue::claim_task(
            &mut conn,
            &["gpu-workers".to_string()],
            "worker-imposter",
            "",
            None,
            &[],
            &[],
        )
        .await
        .expect("claim_task");
        assert!(
            claimed.is_some(),
            "an ordinary sticky (non-session) task must fail over to any \
             worker once its lease expires"
        );
    }

    // -----------------------------------------------------------------------
    // Broken-session scanner (issue #606, TDD step 11)
    // -----------------------------------------------------------------------

    use autumn_harvest::event::WorkflowEvent;
    use autumn_harvest::sessions;
    use autumn_harvest::store;
    use autumn_harvest::types::ActivityExecId;

    async fn insert_worker(
        conn: &mut AsyncPgConnection,
        worker_id: &str,
        last_heartbeat_at: chrono::DateTime<chrono::Utc>,
        status: &str,
    ) {
        diesel::sql_query(
            "INSERT INTO harvest_workers \
             (worker_id, started_at, last_heartbeat_at, queues, shard_assignments, \
              max_concurrency, host, status, build_id, labels, max_concurrent_sessions) \
             VALUES ($1, NOW(), $2, '[]'::jsonb, '[]'::jsonb, 10, 'localhost', $3, '', \
                     '{}'::jsonb, 1)",
        )
        .bind::<Text, _>(worker_id)
        .bind::<Timestamptz, _>(last_heartbeat_at)
        .bind::<Text, _>(status)
        .execute(conn)
        .await
        .expect("insert worker");
    }

    /// Sets up one execution with a `WorkflowStarted` + `ActivityScheduled`
    /// history, a `PENDING` session-pinned task queue row, and an `ACTIVE`
    /// `harvest_sessions` row hosted by `host_worker_id`. Returns
    /// `(exec_id, session_id, activity_id, task_id)`.
    async fn setup_active_session(
        conn: &mut AsyncPgConnection,
        host_worker_id: &str,
        session_expires_at: chrono::DateTime<chrono::Utc>,
    ) -> (ExecutionId, Uuid, ActivityExecId, Uuid) {
        let exec_id = insert_execution(conn).await;
        let activity_id = ActivityExecId::new();
        let session_id = Uuid::new_v4();

        store::append_events(
            conn,
            exec_id,
            &[WorkflowEvent::WorkflowStarted {
                input: serde_json::Value::Null,
                timestamp: chrono::Utc::now(),
                last_completion_result: None,
                last_error: None,
                scheduled_time: None,
            }],
            0,
        )
        .await
        .expect("append WorkflowStarted");
        store::append_events(
            conn,
            exec_id,
            &[WorkflowEvent::ActivityScheduled {
                activity_id,
                name: "transcode_chunk".to_string(),
                input: serde_json::Value::Null,
                queue: "gpu-workers".to_string(),
            }],
            1,
        )
        .await
        .expect("append ActivityScheduled");

        let mut params =
            EnqueueParams::new("gpu-workers", TaskType::Activity, serde_json::json!(null));
        params.workflow_exec_id = Some(exec_id.as_uuid());
        params.activity_name = Some("transcode_chunk".to_string());
        params.activity_id = Some(activity_id.as_uuid());
        let params = params
            .with_session_id(session_id)
            .with_sticky(host_worker_id, Duration::from_secs(24 * 3600));
        let task_id = queue::enqueue(conn, &params).await.expect("enqueue");

        sessions::record_session_acquired(
            conn,
            autumn_harvest::types::SessionId::from_uuid(session_id),
            exec_id,
            host_worker_id,
            "gpu-workers",
            session_expires_at,
        )
        .await
        .expect("record_session_acquired");

        (exec_id, session_id, activity_id, task_id)
    }

    async fn session_state(conn: &mut AsyncPgConnection, session_id: Uuid) -> String {
        #[derive(diesel::QueryableByName)]
        struct StateRow {
            #[diesel(sql_type = Text)]
            state: String,
        }
        diesel::sql_query("SELECT state FROM harvest_sessions WHERE id = $1")
            .bind::<SqlUuid, _>(session_id)
            .get_result::<StateRow>(conn)
            .await
            .expect("read session state")
            .state
    }

    async fn task_state(conn: &mut AsyncPgConnection, task_id: Uuid) -> String {
        #[derive(diesel::QueryableByName)]
        struct StateRow {
            #[diesel(sql_type = Text)]
            state: String,
        }
        diesel::sql_query("SELECT state FROM harvest_task_queue WHERE id = $1")
            .bind::<SqlUuid, _>(task_id)
            .get_result::<StateRow>(conn)
            .await
            .expect("read task state")
            .state
    }

    /// AC5: a session whose host has no `harvest_workers` row at all (never
    /// registered, or GC'd) is reclaimed as broken -- the member task fails
    /// with a distinct, non-retryable `SessionBroken` error, never silently
    /// retried onto a different worker.
    #[tokio::test]
    async fn broken_session_scanner_reclaims_session_with_no_worker_row() {
        let (mut conn, _c) = setup().await;
        let far_future = chrono::Utc::now() + chrono::Duration::hours(1);
        let (exec_id, session_id, activity_id, task_id) =
            setup_active_session(&mut conn, "worker-ghost", far_future).await;

        let failed = sessions::enforce_broken_sessions(&mut conn, 60)
            .await
            .expect("enforce_broken_sessions");
        assert_eq!(failed, 1, "exactly one member task should be failed");

        assert_eq!(session_state(&mut conn, session_id).await, "BROKEN");
        assert_eq!(task_state(&mut conn, task_id).await, "FAILED");

        let history = store::load_history(&mut conn, exec_id)
            .await
            .expect("load history");
        let found = history.events.iter().any(|e| {
            matches!(
                e,
                WorkflowEvent::ActivityFailed {
                    activity_id: id,
                    error_type,
                    non_retryable: true,
                    ..
                } if *id == activity_id && error_type == "SessionBroken"
            )
        });
        assert!(
            found,
            "expected a non-retryable ActivityFailed{{error_type=SessionBroken}} event"
        );
    }

    /// A session hosted by a live, healthy worker with an unexpired lease is
    /// left entirely alone -- the scanner is a no-op.
    #[tokio::test]
    async fn broken_session_scanner_leaves_healthy_session_untouched() {
        let (mut conn, _c) = setup().await;
        insert_worker(&mut conn, "worker-alive", chrono::Utc::now(), "Active").await;
        let far_future = chrono::Utc::now() + chrono::Duration::hours(1);
        let (_exec_id, session_id, _activity_id, task_id) =
            setup_active_session(&mut conn, "worker-alive", far_future).await;

        let failed = sessions::enforce_broken_sessions(&mut conn, 60)
            .await
            .expect("enforce_broken_sessions");
        assert_eq!(failed, 0, "a healthy session must not be touched");

        assert_eq!(session_state(&mut conn, session_id).await, "ACTIVE");
        assert_eq!(task_state(&mut conn, task_id).await, "PENDING");
    }

    /// AC5 (lease path): a session hosted by a live, healthy worker but whose
    /// lease has elapsed is still reclaimed as broken -- guards against a
    /// wedged workflow that never called `Session::complete()`.
    #[tokio::test]
    async fn broken_session_scanner_reclaims_session_with_expired_lease_even_if_host_alive() {
        let (mut conn, _c) = setup().await;
        insert_worker(&mut conn, "worker-alive", chrono::Utc::now(), "Active").await;
        let already_expired = chrono::Utc::now() - chrono::Duration::seconds(5);
        let (_exec_id, session_id, _activity_id, task_id) =
            setup_active_session(&mut conn, "worker-alive", already_expired).await;

        let failed = sessions::enforce_broken_sessions(&mut conn, 60)
            .await
            .expect("enforce_broken_sessions");
        assert_eq!(failed, 1);

        assert_eq!(session_state(&mut conn, session_id).await, "BROKEN");
        assert_eq!(task_state(&mut conn, task_id).await, "FAILED");
    }

    /// A worker whose status is `Draining` (still heartbeating) is treated as
    /// broken -- a graceful drain must not leave a session hard-pinned to a
    /// worker that will soon stop processing tasks.
    #[tokio::test]
    async fn broken_session_scanner_reclaims_session_hosted_by_draining_worker() {
        let (mut conn, _c) = setup().await;
        insert_worker(&mut conn, "worker-draining", chrono::Utc::now(), "Draining").await;
        let far_future = chrono::Utc::now() + chrono::Duration::hours(1);
        let (_exec_id, session_id, _activity_id, task_id) =
            setup_active_session(&mut conn, "worker-draining", far_future).await;

        let failed = sessions::enforce_broken_sessions(&mut conn, 60)
            .await
            .expect("enforce_broken_sessions");
        assert_eq!(failed, 1);

        assert_eq!(session_state(&mut conn, session_id).await, "BROKEN");
        assert_eq!(task_state(&mut conn, task_id).await, "FAILED");
    }

    /// Already-`BROKEN`/`COMPLETED` sessions are ignored -- the scanner only
    /// ever transitions `ACTIVE` rows, so a concurrent scan (or a late
    /// `Session::complete()` racing a prior sweep) is idempotent.
    #[tokio::test]
    async fn broken_session_scanner_ignores_already_completed_session() {
        let (mut conn, _c) = setup().await;
        let far_future = chrono::Utc::now() + chrono::Duration::hours(1);
        let (_exec_id, session_id, _activity_id, task_id) =
            setup_active_session(&mut conn, "worker-ghost", far_future).await;
        sessions::record_session_completed(
            &mut conn,
            autumn_harvest::types::SessionId::from_uuid(session_id),
        )
        .await
        .expect("record_session_completed");

        let failed = sessions::enforce_broken_sessions(&mut conn, 60)
            .await
            .expect("enforce_broken_sessions");
        assert_eq!(failed, 0);
        assert_eq!(session_state(&mut conn, session_id).await, "COMPLETED");
        // The task row is untouched by the scanner; it may still be PENDING
        // since this test never actually completed the underlying activity.
        assert_eq!(task_state(&mut conn, task_id).await, "PENDING");
    }

    // -----------------------------------------------------------------------
    // Co-location (AC4, issue #606) -- full worker-loop integration
    // -----------------------------------------------------------------------

    use autumn_harvest::info::{ActivityInfo, WorkflowInfo};
    use autumn_harvest::models::WorkflowExecution;
    use autumn_harvest::worker::{DbPool, HandlerRegistry, Worker};
    use autumn_harvest::{ActivityContext, WorkflowContext};
    use diesel::{ExpressionMethods, QueryDsl};
    use diesel_async::pooled_connection::AsyncDieselConnectionManager;
    use std::pin::Pin;

    async fn setup_with_url() -> (String, ContainerAsync<Postgres>) {
        let container = Postgres::default()
            .with_init_sql(init_sql())
            .with_tag("16")
            .start()
            .await
            .expect("failed to start Postgres container");
        let host = container.get_host().await.expect("host");
        let port = container.get_host_port_ipv4(5432).await.expect("port");
        let url = format!("postgres://postgres:postgres@{host}:{port}/postgres");
        (url, container)
    }

    fn build_pool(database_url: &str) -> DbPool {
        let manager = AsyncDieselConnectionManager::<AsyncPgConnection>::new(database_url);
        deadpool::managed::Pool::builder(manager)
            .max_size(10)
            .build()
            .expect("failed to build test pool")
    }

    /// A three-step pipeline: opens a worker session, dispatches three
    /// activities through it, releases the session, and returns their
    /// outputs.
    fn session_pipeline_workflow<'a>(
        ctx: &'a WorkflowContext,
        _input: serde_json::Value,
    ) -> Pin<Box<dyn std::future::Future<Output = Result<serde_json::Value, String>> + Send + 'a>>
    {
        Box::pin(async move {
            let session = ctx
                .create_session(sessions_options())
                .await
                .map_err(|e| e.to_string())?;
            let mut outputs = Vec::new();
            for step in 0..3i64 {
                let out = session
                    .execute_activity_raw("pipeline_step", serde_json::json!(step), "default")
                    .await
                    .map_err(|e| e.to_string())?;
                outputs.push(out);
            }
            session.complete().await.map_err(|e| e.to_string())?;
            Ok(serde_json::json!(outputs))
        })
    }

    fn sessions_options() -> autumn_harvest::context::SessionOptions {
        autumn_harvest::context::SessionOptions::new("default")
    }

    fn pipeline_step_activity<'a>(
        _ctx: &'a ActivityContext,
        input: serde_json::Value,
    ) -> Pin<Box<dyn std::future::Future<Output = Result<serde_json::Value, String>> + Send + 'a>>
    {
        Box::pin(async move { Ok(input) })
    }

    async fn load_execution(
        conn: &mut AsyncPgConnection,
        exec_id: ExecutionId,
    ) -> WorkflowExecution {
        use diesel::SelectableHelper;
        harvest_workflow_executions::table
            .find(exec_id.as_uuid())
            .select(WorkflowExecution::as_select())
            .first(conn)
            .await
            .expect("load execution")
    }

    async fn pipeline_task_worker_ids(
        conn: &mut AsyncPgConnection,
        exec_id: ExecutionId,
    ) -> Vec<Option<String>> {
        use autumn_harvest::schema::harvest_task_queue::dsl as q;
        q::harvest_task_queue
            .filter(q::workflow_exec_id.eq(Some(exec_id.as_uuid())))
            .filter(q::activity_name.eq(Some("pipeline_step")))
            .select(q::worker_id)
            .load::<Option<String>>(conn)
            .await
            .expect("load pipeline task worker_ids")
    }

    /// AC4: across one successful session, every member activity's recorded
    /// task row attributes the SAME `worker_id` -- even with two workers in
    /// the fleet racing to claim the session-acquire task, only one wins and
    /// hosts the entire pipeline; the hard-pin claim gate (issue #606, step
    /// 9) prevents the other worker from ever picking up a member activity.
    #[tokio::test]
    #[allow(clippy::too_many_lines)]
    async fn co_location_all_member_activities_share_one_worker_id() {
        let (database_url, _container) = setup_with_url().await;
        let mut conn = AsyncPgConnection::establish(&database_url)
            .await
            .expect("connect");

        let exec_id = insert_execution(&mut conn).await;
        store::append_events(
            &mut conn,
            exec_id,
            &[WorkflowEvent::WorkflowStarted {
                input: serde_json::Value::Null,
                timestamp: chrono::Utc::now(),
                last_completion_result: None,
                last_error: None,
                scheduled_time: None,
            }],
            0,
        )
        .await
        .expect("append WorkflowStarted");

        let mut params = EnqueueParams::new("default", TaskType::Workflow, serde_json::Value::Null);
        params.workflow_exec_id = Some(exec_id.as_uuid());
        params.scheduled_at = chrono::Utc::now() - chrono::Duration::seconds(5);
        queue::enqueue(&mut conn, &params)
            .await
            .expect("enqueue workflow task");

        let registry = std::sync::Arc::new(HandlerRegistry::new(
            vec![WorkflowInfo {
                mcp: false,
                name: "session_test_wf",
                module: "worker_session_tests",
                handler: session_pipeline_workflow,
                execution_timeout: None,
                sla: None,
                concurrency: None,
                debounce: None,
                batch: None,
                throttle: None,
                max_input_bytes: None,
                owner: None,
                runbook_url: None,
                severity: None,
                description: None,
                input_schema: None,
                output_schema: None,
                error_schema: None,
                retry_policy: None,
            }],
            vec![ActivityInfo {
                name: "pipeline_step",
                module: "worker_session_tests",
                default_retry_policy: None,
                default_start_to_close: None,
                default_heartbeat_timeout: None,
                default_schedule_to_start: None,
                default_schedule_to_close: None,
                default_queue: Some("default"),
                max_concurrent: None,
                concurrency_key: None,
                rate_limit_rps: None,
                rate_limit_burst: None,
                rate_limit_key: None,
                circuit_breaker: None,
                is_local: false,
                max_input_bytes: None,
                max_result_bytes: None,
                requires: None,
                handler: pipeline_step_activity,
            }],
        ));

        let pool = build_pool(&database_url);
        let make_worker = |worker_id: &str| {
            std::sync::Arc::new(
                Worker::new(
                    autumn_harvest::worker::WorkerRuntimeConfig {
                        worker_id: worker_id.to_string(),
                        queues: vec!["default".to_string()],
                        notification_database_url: None,
                        max_concurrent_workflows: 2,
                        max_concurrent_activities: 2,
                        poll_interval: Duration::from_millis(25),
                        shutdown_timeout: Duration::from_secs(1),
                        cancellation_grace_period: Duration::from_secs(1),
                        sticky_timeout: Duration::from_secs(5),
                        max_local_activity_start_to_close: Duration::from_secs(60),
                        shard_assignments: vec![autumn_harvest::types::ShardId::new(0)],
                        worker_heartbeat_interval: Duration::from_secs(5),
                        build_id: String::new(),
                        deployment_name: None,
                        workflow_cache_size: 1000,
                        priority_aging_secs: None,
                        unknown_target_grace_window: Duration::from_secs(5),
                        poison_pill_threshold: 3,
                        workflow_task_timeout: Duration::from_secs(20),
                        workflow_panic_max_attempts: 3,
                        labels: std::collections::HashMap::new(),
                        queue_weights: std::collections::HashMap::new(),
                        max_workflow_pause_duration: Duration::from_secs(24 * 3600),
                        max_workflow_history_events: None,
                        shard_notification_database_urls: Vec::new(),
                        sharded_pool: None,
                        slot_tuner: None,
                        // Both workers advertise session capacity so either
                        // one could win the acquire race -- the point of
                        // this test is that whichever wins hosts *all* of
                        // the pipeline's member activities.
                        max_concurrent_sessions: 1,
                    },
                    registry.clone(),
                )
                .expect("worker should build"),
            )
        };

        let worker_a = make_worker("worker-a");
        let worker_b = make_worker("worker-b");
        let pool_a = pool.clone();
        let pool_b = pool.clone();
        let runner_a = worker_a.clone();
        let runner_b = worker_b.clone();
        let handle_a = tokio::spawn(async move { runner_a.run(&pool_a).await });
        let handle_b = tokio::spawn(async move { runner_b.run(&pool_b).await });

        let completed = tokio::time::timeout(Duration::from_secs(30), async {
            loop {
                let execution = load_execution(&mut conn, exec_id).await;
                if execution.state == "COMPLETED" || execution.state == "FAILED" {
                    break execution;
                }
                tokio::time::sleep(Duration::from_millis(50)).await;
            }
        })
        .await
        .expect("pipeline should complete within timeout");

        worker_a.shutdown();
        worker_b.shutdown();
        handle_a.await.expect("worker a should join");
        handle_b.await.expect("worker b should join");

        assert_eq!(
            completed.state, "COMPLETED",
            "session pipeline workflow should complete successfully"
        );

        let worker_ids = pipeline_task_worker_ids(&mut conn, exec_id).await;
        assert_eq!(worker_ids.len(), 3, "expected all 3 pipeline steps to run");
        let first = worker_ids[0].clone();
        assert!(first.is_some(), "every member task must record a worker_id");
        assert!(
            worker_ids.iter().all(|w| *w == first),
            "every session member activity must share the same worker_id, got {worker_ids:?}"
        );
    }
}
