[package]
name = "standalone-runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
autumn-harvest = { version = "0.4.0", path = "../../autumn-harvest", features = ["db", "testing"] }
autumn-harvest-plugin = { version = "0.4.0", path = "../../autumn-harvest-plugin" }
autumn-web = "0.5"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
