//! Wire format for tasks stored in Redis.
//!
//! The Postgres adapter persists task fields as columns. Redis Streams have no
//! schema, so we serialize one [`TaskEnvelope`] per task as JSON in the `payload`
//! field of an XADD call. The envelope is intentionally a flat record so that
//! it round-trips through `serde_json` without losing precision and so that
//! adding a new field is backwards compatible (deserializers tolerate unknown
//! fields when using `#[serde(default)]`).
//!
//! [`TaskEnvelope`] is also the shape that workers receive from
//! [`crate::TaskQueueAdapter::claim`], and it carries enough information to
//! drive the same execution paths that `autumn-harvest`'s Postgres-backed
//! `worker.rs` uses today.

use std::time::Duration;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::error::{RedisAdapterError, RedisAdapterResult};

/// Discriminator mirroring `autumn_harvest::queue::TaskType`.
///
/// Using a string-valued enum keeps the wire format readable in `redis-cli`
/// while preserving the same `'workflow' | 'activity'` invariants the engine
/// already enforces in Postgres via a `CHECK` constraint.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskType {
    /// A top-level workflow execution.
    Workflow,
    /// A single activity invocation within a workflow.
    Activity,
}

impl TaskType {
    /// String representation used on the wire and in DLQ records.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Workflow => "workflow",
            Self::Activity => "activity",
        }
    }
}

impl std::fmt::Display for TaskType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Parameters for enqueuing a new task.
///
/// Mirrors the field set on `autumn_harvest::queue::EnqueueParams` so that
/// callers who already build the Postgres params can produce the Redis params
/// without restructuring their code paths. The `From` impl below makes the
/// translation explicit and lossless for fields that are common to both
/// backends.
#[derive(Debug, Clone)]
pub struct EnqueueParams {
    /// Logical queue name. The adapter maps it onto a Redis stream key via
    /// [`crate::naming::stream_key`].
    pub queue_name: String,
    /// Whether this task represents a workflow run or an activity invocation.
    pub task_type: TaskType,
    /// Owning workflow execution, if any.
    pub workflow_exec_id: Option<Uuid>,
    /// Activity name (only set when `task_type` is `Activity`).
    pub activity_name: Option<String>,
    /// JSON-encoded input payload handed to the workflow or activity handler.
    pub input: serde_json::Value,
    /// Higher values claim before lower values when multiple tasks are due.
    pub priority: i32,
    /// Hard ceiling on retry attempts before the task is moved to the DLQ.
    pub max_attempts: i32,
    /// Earliest time at which this task may be claimed.
    pub scheduled_at: DateTime<Utc>,
    /// Heartbeat timeout copied through to the worker for activity-side use.
    pub heartbeat_timeout: Option<Duration>,
    /// Start-to-close timeout copied through to the worker.
    pub start_to_close: Option<Duration>,
    /// Schedule-to-start timeout copied through to the worker.
    pub schedule_to_start: Option<Duration>,
    /// Optional retry policy serialized as JSON.
    pub retry_policy: Option<serde_json::Value>,
    /// Sticky worker affinity hint.
    pub sticky_worker_id: Option<String>,
    /// Sticky timeout used to refresh `sticky_until` on each requeue.
    pub sticky_timeout: Option<Duration>,
    /// W3C tracecontext propagated across the queue boundary.
    pub trace_context: Option<serde_json::Value>,
}

impl EnqueueParams {
    /// Construct a new params object with sensible defaults.
    #[must_use]
    pub fn new(
        queue_name: impl Into<String>,
        task_type: TaskType,
        input: serde_json::Value,
    ) -> Self {
        Self {
            queue_name: queue_name.into(),
            task_type,
            workflow_exec_id: None,
            activity_name: None,
            input,
            priority: 0,
            max_attempts: 3,
            scheduled_at: Utc::now(),
            heartbeat_timeout: None,
            start_to_close: None,
            schedule_to_start: None,
            retry_policy: None,
            sticky_worker_id: None,
            sticky_timeout: None,
            trace_context: None,
        }
    }
}

/// A serialized task as it lives on a Redis stream.
///
/// Workers receive this envelope back from [`crate::TaskQueueAdapter::claim`].
/// The `task_id` is a stable UUID generated by the producer at enqueue time so
/// that retries and DLQ records share the same identity across the task's
/// lifetime, regardless of how many Redis stream entries it occupies.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TaskEnvelope {
    /// Stable producer-assigned UUID for this task.
    pub task_id: Uuid,
    /// Logical queue name.
    pub queue_name: String,
    /// Workflow vs. activity discriminator.
    pub task_type: TaskType,
    /// Owning workflow execution, if any.
    #[serde(default)]
    pub workflow_exec_id: Option<Uuid>,
    /// Activity name (only set when `task_type` is `Activity`).
    #[serde(default)]
    pub activity_name: Option<String>,
    /// JSON-encoded input payload.
    pub input: serde_json::Value,
    /// Static priority preserved from `EnqueueParams`.
    #[serde(default)]
    pub priority: i32,
    /// Hard ceiling on retry attempts.
    #[serde(default)]
    pub max_attempts: i32,
    /// Current attempt number (1-based). Incremented by the adapter on each
    /// successful claim.
    #[serde(default)]
    pub attempt: i32,
    /// Earliest time at which this task became claimable.
    pub scheduled_at: DateTime<Utc>,
    /// Heartbeat timeout in seconds (preserved as integer for portability).
    #[serde(default)]
    pub heartbeat_timeout_secs: Option<i64>,
    /// Start-to-close timeout in seconds.
    #[serde(default)]
    pub start_to_close_secs: Option<i64>,
    /// Schedule-to-start timeout in seconds.
    #[serde(default)]
    pub schedule_to_start_secs: Option<i64>,
    /// Retry policy preserved as JSON.
    #[serde(default)]
    pub retry_policy: Option<serde_json::Value>,
    /// Sticky worker affinity hint.
    #[serde(default)]
    pub sticky_worker_id: Option<String>,
    /// Sticky deadline as ISO-8601 timestamp.
    #[serde(default)]
    pub sticky_until: Option<DateTime<Utc>>,
    /// Sticky timeout in milliseconds.
    #[serde(default)]
    pub sticky_timeout_ms: Option<u64>,
    /// W3C tracecontext propagated from the producer.
    #[serde(default)]
    pub trace_context: Option<serde_json::Value>,
}

impl TaskEnvelope {
    /// Build an envelope from `EnqueueParams`, generating a new `task_id`.
    pub(crate) fn from_params(params: EnqueueParams, task_id: Uuid) -> RedisAdapterResult<Self> {
        let sticky_until = match (params.sticky_worker_id.as_ref(), params.sticky_timeout) {
            (Some(_), Some(timeout)) => {
                let chrono_timeout = chrono::Duration::from_std(timeout).map_err(|e| {
                    RedisAdapterError::DurationOutOfRange(format!("sticky_timeout: {e}"))
                })?;
                Some(Utc::now() + chrono_timeout)
            }
            _ => None,
        };

        Ok(Self {
            task_id,
            queue_name: params.queue_name,
            task_type: params.task_type,
            workflow_exec_id: params.workflow_exec_id,
            activity_name: params.activity_name,
            input: params.input,
            priority: params.priority,
            max_attempts: params.max_attempts,
            attempt: 0,
            scheduled_at: params.scheduled_at,
            heartbeat_timeout_secs: params
                .heartbeat_timeout
                .map(|d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX)),
            start_to_close_secs: params
                .start_to_close
                .map(|d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX)),
            schedule_to_start_secs: params
                .schedule_to_start
                .map(|d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX)),
            retry_policy: params.retry_policy,
            sticky_worker_id: params.sticky_worker_id,
            sticky_until,
            sticky_timeout_ms: params
                .sticky_timeout
                .map(|d| u64::try_from(d.as_millis()).unwrap_or(u64::MAX)),
            trace_context: params.trace_context,
        })
    }

    /// Serialize to the JSON string stored under the `payload` stream field.
    pub(crate) fn to_payload(&self) -> RedisAdapterResult<String> {
        Ok(serde_json::to_string(self)?)
    }

    /// Deserialize from the `payload` stream field.
    pub(crate) fn from_payload(payload: &str, entry_id: &str) -> RedisAdapterResult<Self> {
        serde_json::from_str(payload).map_err(|e| RedisAdapterError::MalformedEntry {
            entry_id: entry_id.to_string(),
            reason: e.to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_type_round_trips_through_json() {
        let json = serde_json::to_string(&TaskType::Workflow).unwrap();
        assert_eq!(json, "\"workflow\"");
        let parsed: TaskType = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, TaskType::Workflow);
    }

    #[test]
    fn envelope_round_trips_through_payload() {
        let params = EnqueueParams::new(
            "default",
            TaskType::Activity,
            serde_json::json!({"to": "alice"}),
        );
        let envelope = TaskEnvelope::from_params(params, Uuid::new_v4()).unwrap();
        let payload = envelope.to_payload().unwrap();
        let decoded = TaskEnvelope::from_payload(&payload, "0-0").unwrap();
        assert_eq!(envelope, decoded);
    }

    #[test]
    fn malformed_payload_reports_entry_id() {
        let err = TaskEnvelope::from_payload("not json", "1-2").unwrap_err();
        match err {
            RedisAdapterError::MalformedEntry { entry_id, .. } => assert_eq!(entry_id, "1-2"),
            other => panic!("expected MalformedEntry, got {other:?}"),
        }
    }

    #[test]
    fn unknown_envelope_fields_round_trip_via_defaults() {
        // Producer-side struct only sets the required fields; consumer side
        // fills the rest from `#[serde(default)]`.
        let payload = r#"{
            "task_id": "00000000-0000-0000-0000-000000000001",
            "queue_name": "default",
            "task_type": "workflow",
            "input": null,
            "scheduled_at": "2025-01-01T00:00:00Z"
        }"#;
        let env = TaskEnvelope::from_payload(payload, "0-0").unwrap();
        assert_eq!(env.attempt, 0);
        assert_eq!(env.max_attempts, 0);
        assert!(env.workflow_exec_id.is_none());
    }

    #[test]
    fn sticky_until_is_set_only_when_both_fields_are_present() {
        let mut p = EnqueueParams::new("q", TaskType::Workflow, serde_json::Value::Null);
        p.sticky_worker_id = Some("w".into());
        let env = TaskEnvelope::from_params(p, Uuid::new_v4()).unwrap();
        // No timeout -> no sticky_until.
        assert!(env.sticky_until.is_none());
    }
}
