#!/usr/bin/env bash
# Fails if docs/getting-started/04-signals.md's "Clean Declarative
# await_condition" example (`collect_approvals_clean`) regresses into either
# of two compile failures a newcomer hit copying it verbatim: HVG010
# hard-blocking the bare `futures::future::select` race, or a borrow-check
# error (E0506) from capturing a plain counter across the whole loop. See
# autumn-harvest/examples/collect_approvals.rs for the real, CI-compiled
# equivalent this example is meant to match.
#
# This actually compiles the pinned block with `cargo check`, rather than
# grepping for stand-in text patterns (PR #1700 review): E0506 is a
# borrow-checker property, not a syntax shape, so a text heuristic checking
# for "a plain `let mut approvals = 0`" or "a `Mutex::new(` somewhere
# nearby" is exactly as gameable as it sounds -- rename the counter, give
# it a type annotation, or leave an unrelated Mutex in scope after a
# refactor, and the real bug can return while a substring check still
# passes. `docs/audits/doc-snippet-syntax.py` deliberately does not do this
# for the whole corpus (see its own docstring: it would need a scratch
# crate per chapter-local import/feature combination, which is a real
# compile-time and dependency cost for 93 blocks across 16 files). That
# tradeoff does not apply to checking ONE pinned, previously-broken block
# against the crate this repository already builds in the same `lint` job
# (see the `cargo clippy -p autumn-harvest` step below this one) -- the
# marginal cost here is one more `cargo check --example`, not a new
# category of cost.
#
# Usage: ./scripts/check-signals-clean-approval-example-determinism.sh

set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

doc="docs/getting-started/04-signals.md"
example_name="_onramp_doc_check_signals_clean_approval"
example_path="autumn-harvest/examples/${example_name}.rs"

cleanup() {
  rm -f "$example_path"
}
trap cleanup EXIT
cleanup # self-heal if a previous run was killed before its own trap ran

if [ ! -f "$doc" ]; then
  echo "$doc: not found" >&2
  exit 1
fi

# The example runs from its own attribute line to the fenced block's own
# close (exclusive) -- a generous window that survives the body growing or
# shrinking, since it stops at the next "```" line rather than a fixed line
# count.
code="$(awk '
  /^#\[workflow\(allow_nondeterministic_apis\)\]$/ { p = 1 }
  p && /^```$/ { exit }
  p { print }
' "$doc")"

if [ -z "$code" ]; then
  echo "$doc: could not find the collect_approvals_clean example (looked" \
    "for its #[workflow(allow_nondeterministic_apis)] attribute line);" \
    "has the chapter been restructured, or has the fix in this example" \
    "been reverted? Update this guard to match." >&2
  exit 1
fi

cat >"$example_path" <<RUST_EOF
#![allow(clippy::all, clippy::pedantic, clippy::nursery, dead_code)]
// Generated by scripts/check-signals-clean-approval-example-determinism.sh
// from docs/getting-started/04-signals.md -- not checked in, not a real
// example. Edit the markdown, not this file.
use autumn_harvest::prelude::*;
use serde_json::{Value, json};

${code}

fn main() {
    let _wfs = workflows![collect_approvals_clean];
}
RUST_EOF

if ! output="$(cargo check --quiet -p autumn-harvest --example "$example_name" 2>&1)"; then
  echo "$doc: collect_approvals_clean does not compile against the real" \
    "autumn-harvest crate. A newcomer who copies this exact block hits" \
    "this error:" >&2
  echo >&2
  echo "$output" >&2
  echo >&2
  echo "See autumn-harvest/examples/collect_approvals.rs for the real," \
    "compiling equivalent this example is meant to match (the" \
    "allow_nondeterministic_apis opt-out and a Mutex-backed counter)." >&2
  exit 1
fi

echo "OK: collect_approvals_clean compiles against the real autumn-harvest crate."
