//! Integration tests for the build-routing percentage ramp management API
//! (issue #604): `POST /admin/build-routing/ramp`, `GET /admin/build-routing`,
//! `DELETE /admin/build-routing/ramp/{queue_name}`.
//!
//! TDD structure:
//!   RED  – these tests drove the handler/route design
//!   GREEN – handlers in `autumn-harvest-plugin/src/api.rs`
//!
//! Docker/testcontainers is not available in this sandbox, so these tests are
//! compile-checked only here (`cargo test --no-run` / `cargo check --tests`);
//! they exercise a real Postgres instance in CI.

use autumn_harvest::build_routing::{set_build_policy, set_build_ramp};
use autumn_harvest::worker::DbPool;
use autumn_harvest_plugin::HarvestDbPool;
use autumn_harvest_plugin::api::{HarvestApiState, harvest_api_router};
use autumn_web::reexports::axum;
use axum::body::Body;
use axum::http::{Request, StatusCode};
use diesel_async::AsyncPgConnection;
use serde_json::{Value, json};
use testcontainers::ContainerAsync;
use testcontainers::ImageExt;
use testcontainers_modules::postgres::Postgres;
use testcontainers_modules::testcontainers::runners::AsyncRunner;
use tower::ServiceExt;

// The migration bundle is the paved-path helper `test_init_sql()`,
// regenerated by build.rs from the whole `migrations/` directory. This
// replaced a hand-rolled `concat!(include_str!(...))` list (plus inline
// legal_hold ADD COLUMN patches) that had silently drifted: it was missing
// `20260506000000_harvest_audit_log`, so any code path touching
// `harvest_audit_log` failed `relation "harvest_audit_log" does not exist` —
// invisible because CI only compiled this suite, never ran it against a DB
// (issue #604 test-infra hardening). The bundle can never drift again.
fn init_sql() -> Vec<u8> {
    autumn_harvest::test_init_sql().as_bytes().to_vec()
}

type HarvestApiApp = axum::Router;

async fn setup_test_database_url() -> (String, ContainerAsync<Postgres>) {
    let container = Postgres::default()
        .with_init_sql(init_sql())
        .with_tag("16")
        .start()
        .await
        .expect("failed to start Postgres container");
    let host = container.get_host().await.expect("host");
    let port = container.get_host_port_ipv4(5432).await.expect("port");
    let url = format!("postgres://postgres:postgres@{host}:{port}/postgres");
    (url, container)
}

fn build_test_pool(database_url: &str) -> DbPool {
    let manager =
        diesel_async::pooled_connection::AsyncDieselConnectionManager::<AsyncPgConnection>::new(
            database_url,
        );
    deadpool::managed::Pool::builder(manager)
        .max_size(4)
        .build()
        .expect("failed to build test pool")
}

fn build_ramp_app(pool: DbPool) -> HarvestApiApp {
    let api_state = HarvestApiState::new();
    api_state.set_admin_auth_boundary(true);
    api_state.install_storage_pool(HarvestDbPool::from(pool));
    harvest_api_router(api_state)
}

async fn read_json_response(response: axum::response::Response) -> Value {
    let body = axum::body::to_bytes(response.into_body(), usize::MAX)
        .await
        .expect("failed to read response body");
    serde_json::from_slice(&body).expect("response must be JSON")
}

async fn get_json(app: &HarvestApiApp, uri: impl Into<String>) -> (StatusCode, Value) {
    let uri = uri.into();
    let response = app
        .clone()
        .oneshot(
            Request::builder()
                .method("GET")
                .uri(&uri)
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .expect("GET request failed");
    let status = response.status();
    let json = read_json_response(response).await;
    (status, json)
}

async fn post_json(app: &HarvestApiApp, uri: &str, body: Value) -> (StatusCode, Value) {
    let response = app
        .clone()
        .oneshot(
            Request::builder()
                .method("POST")
                .uri(uri)
                .header("content-type", "application/json")
                .body(Body::from(body.to_string()))
                .unwrap(),
        )
        .await
        .expect("POST request failed");
    let status = response.status();
    let json = read_json_response(response).await;
    (status, json)
}

/// POST `body` with an optional `Idempotency-Key` header.
async fn post_json_with_key(
    app: &HarvestApiApp,
    uri: &str,
    body: Value,
    key: Option<&str>,
) -> (StatusCode, Value) {
    let mut request = Request::builder()
        .method("POST")
        .uri(uri)
        .header("content-type", "application/json");
    if let Some(key) = key {
        request = request.header("Idempotency-Key", key);
    }
    let response = app
        .clone()
        .oneshot(request.body(Body::from(body.to_string())).unwrap())
        .await
        .expect("POST request failed");
    let status = response.status();
    let json = read_json_response(response).await;
    (status, json)
}

async fn delete_json(app: &HarvestApiApp, uri: &str) -> (StatusCode, Value) {
    let response = app
        .clone()
        .oneshot(
            Request::builder()
                .method("DELETE")
                .uri(uri)
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .expect("DELETE request failed");
    let status = response.status();
    let json = read_json_response(response).await;
    (status, json)
}

#[tokio::test]
async fn set_ramp_then_get_shows_base_target_and_percent() {
    let (db_url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&db_url);
    let mut conn = pool.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    drop(conn);

    let app = build_ramp_app(pool);

    let (status, body) = post_json(
        &app,
        "/admin/build-routing/ramp",
        json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": 25 }),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "body: {body}");
    assert_eq!(body["target_build_id"], "canary-v2");
    assert_eq!(body["ramp_percent"], 25);

    let (status, body) = get_json(&app, "/admin/build-routing").await;
    assert_eq!(status, StatusCode::OK, "body: {body}");
    let policies = body["policies"].as_array().expect("policies array");
    let default_policy = policies
        .iter()
        .find(|p| p["queue_name"] == "default")
        .expect("default policy present");
    assert_eq!(default_policy["build_id"], "base-v1");
    assert_eq!(default_policy["target_build_id"], "canary-v2");
    assert_eq!(default_policy["ramp_percent"], 25);
}

#[tokio::test]
async fn set_ramp_without_base_policy_returns_conflict() {
    let (db_url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&db_url);
    let app = build_ramp_app(pool);

    let (status, _body) = post_json(
        &app,
        "/admin/build-routing/ramp",
        json!({ "queue_name": "no-base-policy", "target_build_id": "canary-v2", "ramp_percent": 25 }),
    )
    .await;
    assert_eq!(status, StatusCode::CONFLICT);
}

#[tokio::test]
async fn set_ramp_rejects_percent_out_of_range() {
    let (db_url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&db_url);
    let mut conn = pool.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    drop(conn);
    let app = build_ramp_app(pool);

    let (status, _body) = post_json(
        &app,
        "/admin/build-routing/ramp",
        json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": 101 }),
    )
    .await;
    assert_eq!(status, StatusCode::BAD_REQUEST);
}

#[tokio::test]
async fn clear_ramp_removes_target_and_percent() {
    let (db_url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&db_url);
    let mut conn = pool.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    drop(conn);
    let app = build_ramp_app(pool);

    post_json(
        &app,
        "/admin/build-routing/ramp",
        json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": 50 }),
    )
    .await;

    let (status, body) = delete_json(&app, "/admin/build-routing/ramp/default").await;
    assert_eq!(status, StatusCode::OK, "body: {body}");
    assert_eq!(body["ramp_percent"], Value::Null);

    let (_status, body) = get_json(&app, "/admin/build-routing").await;
    let policies = body["policies"].as_array().expect("policies array");
    let default_policy = policies
        .iter()
        .find(|p| p["queue_name"] == "default")
        .expect("default policy present");
    assert_eq!(default_policy["ramp_percent"], Value::Null);
    assert_eq!(default_policy["target_build_id"], Value::Null);
}

#[tokio::test]
async fn clear_ramp_on_unknown_queue_returns_not_found() {
    let (db_url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&db_url);
    let app = build_ramp_app(pool);

    let (status, _body) = delete_json(&app, "/admin/build-routing/ramp/no-such-queue").await;
    assert_eq!(status, StatusCode::NOT_FOUND);
}

#[tokio::test]
async fn set_ramp_records_audit_row() {
    let (db_url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&db_url);
    let mut conn = pool.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    drop(conn);
    let app = build_ramp_app(pool.clone());

    post_json(
        &app,
        "/admin/build-routing/ramp",
        json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": 25 }),
    )
    .await;

    let (status, body) = get_json(&app, "/admin/audit?operation=build_routing.ramp.set").await;
    assert_eq!(status, StatusCode::OK, "body: {body}");
    let records = body.as_array().expect("audit response is a raw array");
    assert!(
        !records.is_empty(),
        "expected an audit record for build_routing.ramp.set"
    );
}

/// The `ramp_id` stored for the `default` queue.
async fn stored_ramp_id(pool: &DbPool) -> Option<uuid::Uuid> {
    use diesel_async::RunQueryDsl;

    #[derive(diesel::QueryableByName)]
    struct Row {
        #[diesel(sql_type = diesel::sql_types::Nullable<diesel::sql_types::Uuid>)]
        ramp_id: Option<uuid::Uuid>,
    }
    let mut conn = pool.get().await.expect("get conn");
    diesel::sql_query("SELECT ramp_id FROM harvest_build_policies WHERE queue_name = 'default'")
        .get_result::<Row>(&mut conn)
        .await
        .expect("read ramp_id")
        .ramp_id
}

/// A client retries a ramp after a partial fan-out with the same
/// `Idempotency-Key`. Every shard then stores the same `ramp_id`, so the ramp
/// guard sees one ramp generation (issue #1814). Two databases stand in for
/// the shard of the first request and the shard of the retry.
#[tokio::test]
async fn a_retried_ramp_with_one_idempotency_key_gets_one_ramp_id_on_every_shard() {
    let (url_a, _container_a) = setup_test_database_url().await;
    let (url_b, _container_b) = setup_test_database_url().await;
    let mut apps = Vec::new();
    let mut pools = Vec::new();
    for url in [&url_a, &url_b] {
        let pool = build_test_pool(url);
        let mut conn = pool.get().await.expect("get conn");
        set_build_policy(&mut conn, "default", "base-v1", None)
            .await
            .expect("seed base policy");
        drop(conn);
        pools.push(pool.clone());
        apps.push(build_ramp_app(pool));
    }
    let ramp = |percent: i32| json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": percent });

    let mut keyed = Vec::new();
    for (app, pool) in apps.iter().zip(&pools) {
        let (status, body) = post_json_with_key(
            app,
            "/admin/build-routing/ramp",
            ramp(25),
            Some("ramp-1814"),
        )
        .await;
        assert_eq!(status, StatusCode::OK, "body: {body}");
        keyed.push(stored_ramp_id(pool).await);
    }
    assert!(keyed[0].is_some(), "a ramp has an id: {keyed:?}");
    assert_eq!(keyed[0], keyed[1], "one key gives one ramp id");

    // With no key, each request is a new operation with its own id.
    let mut unkeyed = Vec::new();
    for (app, pool) in apps.iter().zip(&pools) {
        let (status, body) =
            post_json_with_key(app, "/admin/build-routing/ramp", ramp(50), None).await;
        assert_eq!(status, StatusCode::OK, "body: {body}");
        unkeyed.push(stored_ramp_id(pool).await);
    }
    assert!(unkeyed[0].is_some(), "a ramp has an id: {unkeyed:?}");
    assert_ne!(unkeyed[0], unkeyed[1], "no key gives a new id per request");
}

/// A policy update keeps an active ramp. A retry of a partial policy fan-out
/// with the same `Idempotency-Key` gives that ramp one `ramp_id` on every
/// shard (issue #1814).
#[tokio::test]
async fn a_retried_policy_update_with_one_idempotency_key_keeps_one_ramp_id() {
    let (url_a, _container_a) = setup_test_database_url().await;
    let (url_b, _container_b) = setup_test_database_url().await;
    let mut apps = Vec::new();
    let mut pools = Vec::new();
    for url in [&url_a, &url_b] {
        let pool = build_test_pool(url);
        let mut conn = pool.get().await.expect("get conn");
        set_build_policy(&mut conn, "default", "base-v1", None)
            .await
            .expect("seed base policy");
        set_build_ramp(&mut conn, "default", "canary-v2", 25)
            .await
            .expect("seed ramp");
        drop(conn);
        pools.push(pool.clone());
        apps.push(build_ramp_app(pool));
    }
    let policy = json!({ "queue_name": "default", "build_id": "base-v3" });

    let mut ids = Vec::new();
    for (app, pool) in apps.iter().zip(&pools) {
        let (status, body) = post_json_with_key(
            app,
            "/admin/build-routing/policies",
            policy.clone(),
            Some("policy-1814"),
        )
        .await;
        assert_eq!(status, StatusCode::OK, "body: {body}");
        assert_eq!(body["target_build_id"], "canary-v2", "the ramp stays");
        ids.push(stored_ramp_id(pool).await);
    }
    assert!(ids[0].is_some(), "a retained ramp has an id: {ids:?}");
    assert_eq!(ids[0], ids[1], "one key gives one ramp id");
}

/// A later keyed policy write supersedes an earlier one that kept the same
/// ramp. A late retry of the earlier write gets `409` and leaves the newer
/// ramp (issue #1814).
#[tokio::test]
async fn a_stale_keyed_policy_retry_is_refused_and_keeps_the_newer_ramp() {
    let (url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&url);
    let mut conn = pool.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    set_build_ramp(&mut conn, "default", "canary-v2", 25)
        .await
        .expect("seed ramp");
    drop(conn);
    let app = build_ramp_app(pool.clone());
    let policy = |deployment: &str| json!({ "queue_name": "default", "build_id": "base-v1", "deployment_name": deployment });
    for (deployment, key) in [("one", "policy-a"), ("two", "policy-b")] {
        let (status, body) = post_json_with_key(
            &app,
            "/admin/build-routing/policies",
            policy(deployment),
            Some(key),
        )
        .await;
        assert_eq!(status, StatusCode::OK, "body: {body}");
    }

    let (status, body) = post_json_with_key(
        &app,
        "/admin/build-routing/policies",
        policy("one"),
        Some("policy-a"),
    )
    .await;
    assert_eq!(status, StatusCode::CONFLICT, "body: {body}");
    assert!(ramp_is_active(&pool).await, "the newer ramp stays");
}

/// A client reuses an `Idempotency-Key` with a changed ramp. The first
/// request reached shard A only. The retry with a new percentage reaches
/// both shards. Both must store one `ramp_id` (issue #1814). With the old
/// id, shard A rewrote its ramp under an unchanged id, and the reset trigger
/// cleared it.
#[tokio::test]
async fn a_reused_key_with_a_changed_ramp_keeps_one_ramp_id_on_every_shard() {
    let (url_a, _container_a) = setup_test_database_url().await;
    let (url_b, _container_b) = setup_test_database_url().await;
    let mut apps = Vec::new();
    let mut pools = Vec::new();
    for url in [&url_a, &url_b] {
        let pool = build_test_pool(url);
        let mut conn = pool.get().await.expect("get conn");
        set_build_policy(&mut conn, "default", "base-v1", None)
            .await
            .expect("seed base policy");
        drop(conn);
        pools.push(pool.clone());
        apps.push(build_ramp_app(pool));
    }
    let ramp = |percent: i32| json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": percent });
    // The first request reached shard A only.
    let (status, body) = post_json_with_key(
        &apps[0],
        "/admin/build-routing/ramp",
        ramp(25),
        Some("k-1814"),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "body: {body}");

    // The retry changes the percentage and reaches both shards.
    let mut ids = Vec::new();
    for (app, pool) in apps.iter().zip(&pools) {
        let (status, body) =
            post_json_with_key(app, "/admin/build-routing/ramp", ramp(50), Some("k-1814")).await;
        assert_eq!(status, StatusCode::OK, "body: {body}");
        ids.push(stored_ramp_id(pool).await);
    }
    assert!(ids[0].is_some(), "shard A keeps an id: {ids:?}");
    assert_eq!(ids[0], ids[1], "both shards hold one generation");
}

/// Abort the ramp on `pool` the way the ramp guard does, and return the
/// marker id: the stored `ramp_id`.
async fn auto_abort(pool: &DbPool, target: &str) -> uuid::Uuid {
    use autumn_harvest::build_routing::get_build_policy;

    let mut conn = pool.get().await.expect("get conn");
    let policy = get_build_policy(&mut conn, "default")
        .await
        .expect("read policy")
        .expect("policy exists");
    autumn_harvest::ramp_guard::abort_ramp(
        &mut conn,
        "default",
        &policy.build_id,
        target,
        policy.updated_at,
        std::time::Duration::from_secs(5),
    )
    .await
    .expect("abort")
    .expect("the abort cleared the ramp")
}

async fn ramp_is_active(pool: &DbPool) -> bool {
    use autumn_harvest::build_routing::get_build_policy;

    let mut conn = pool.get().await.expect("get conn");
    get_build_policy(&mut conn, "default")
        .await
        .expect("read policy")
        .expect("policy exists")
        .target_build_id
        .is_some()
}

/// A client retries a keyed ramp after the ramp guard aborted it, for
/// example because the first response was lost. The retry must not bring
/// the aborted ramp back (issue #1814). The abort marker records it.
#[tokio::test]
async fn a_keyed_retry_does_not_restore_an_aborted_ramp() {
    let (url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&url);
    let mut conn = pool.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    drop(conn);
    let app = build_ramp_app(pool.clone());
    let ramp =
        json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": 10 });

    let (status, body) = post_json_with_key(
        &app,
        "/admin/build-routing/ramp",
        ramp.clone(),
        Some("k-abort"),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "body: {body}");
    auto_abort(&pool, "canary-v2").await;

    let (status, body) = post_json_with_key(
        &app,
        "/admin/build-routing/ramp",
        ramp.clone(),
        Some("k-abort"),
    )
    .await;
    assert_eq!(status, StatusCode::CONFLICT, "body: {body}");
    assert!(!ramp_is_active(&pool).await, "the aborted ramp stays off");

    // A new key is a new ramp.
    let (status, body) =
        post_json_with_key(&app, "/admin/build-routing/ramp", ramp, Some("k-new")).await;
    assert_eq!(status, StatusCode::OK, "body: {body}");
    assert!(ramp_is_active(&pool).await);
}

/// The guard prunes abort markers after a while. The report ledger keeps
/// the aborted id, so a late keyed retry is still refused (issue #1814).
#[tokio::test]
async fn a_keyed_retry_after_marker_pruning_does_not_restore_an_aborted_ramp() {
    use diesel_async::RunQueryDsl;

    let (url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&url);
    let mut conn = pool.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    drop(conn);
    let app = build_ramp_app(pool.clone());
    let ramp =
        json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": 10 });

    let (status, body) = post_json_with_key(
        &app,
        "/admin/build-routing/ramp",
        ramp.clone(),
        Some("k-late"),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "body: {body}");
    let aborted = auto_abort(&pool, "canary-v2").await;
    // The guard reported the abort and later pruned its markers.
    let mut conn = pool.get().await.expect("get conn");
    diesel::sql_query(
        "INSERT INTO harvest_ramp_abort_reports (ramp_id, queue_name) VALUES ($1, 'default')",
    )
    .bind::<diesel::sql_types::Uuid, _>(aborted)
    .execute(&mut conn)
    .await
    .expect("ledger row");
    diesel::sql_query(
        "UPDATE harvest_build_policies SET ramp_aborted = '[]'::jsonb WHERE queue_name = 'default'",
    )
    .execute(&mut conn)
    .await
    .expect("prune markers");
    drop(conn);

    let (status, body) =
        post_json_with_key(&app, "/admin/build-routing/ramp", ramp, Some("k-late")).await;
    assert_eq!(status, StatusCode::CONFLICT, "body: {body}");
    assert!(!ramp_is_active(&pool).await, "the aborted ramp stays off");
}

/// The aborted-ramp check of a keyed ramp fails closed (issue #1814). A
/// shard that it cannot read could hold an aborted generation with pruned
/// markers. So the request writes no shard and answers `503`.
#[tokio::test]
async fn a_keyed_ramp_writes_nothing_when_a_shard_cannot_be_checked() {
    use autumn_harvest::ShardId;
    use autumn_harvest::shard::ShardedDbPool;

    let (url, _container) = setup_test_database_url().await;
    let live = build_test_pool(&url);
    let mut conn = live.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    drop(conn);
    // No server listens on port 1, so shard 1 cannot be read.
    let dead = build_test_pool("postgres://postgres:postgres@127.0.0.1:1/none");
    let mut pools = std::collections::BTreeMap::new();
    pools.insert(ShardId::new(0), live.clone());
    pools.insert(ShardId::new(1), dead);
    let api_state = HarvestApiState::new();
    api_state.set_admin_auth_boundary(true);
    api_state.install_storage_pool(HarvestDbPool::sharded(ShardedDbPool::from_map(
        pools,
        ShardId::new(0),
    )));
    let app = harvest_api_router(api_state);
    let ramp =
        json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": 10 });

    let (status, body) =
        post_json_with_key(&app, "/admin/build-routing/ramp", ramp, Some("k-dead")).await;
    assert_eq!(status, StatusCode::SERVICE_UNAVAILABLE, "body: {body}");
    assert!(!ramp_is_active(&live).await, "no shard gets the ramp");
}

/// A shard that refuses the ramp with a conflict while another shard takes
/// it leaves the fan-out divergent. The response says so with `207` and
/// names the refusing shard (issue #1814).
#[tokio::test]
async fn a_conflict_on_one_shard_is_reported_when_another_shard_takes_the_ramp() {
    use autumn_harvest::ShardId;
    use autumn_harvest::shard::ShardedDbPool;

    let (url_a, _container_a) = setup_test_database_url().await;
    let (url_b, _container_b) = setup_test_database_url().await;
    let with_base = build_test_pool(&url_a);
    let mut conn = with_base.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    drop(conn);
    // Shard 1 has no base policy, so its write is a conflict.
    let mut pools = std::collections::BTreeMap::new();
    pools.insert(ShardId::new(0), with_base);
    pools.insert(ShardId::new(1), build_test_pool(&url_b));
    let api_state = HarvestApiState::new();
    api_state.set_admin_auth_boundary(true);
    api_state.install_storage_pool(HarvestDbPool::sharded(ShardedDbPool::from_map(
        pools,
        ShardId::new(0),
    )));
    let app = harvest_api_router(api_state);
    let ramp =
        json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": 10 });

    let (status, body) = post_json(&app, "/admin/build-routing/ramp", ramp).await;
    assert_eq!(status, StatusCode::MULTI_STATUS, "body: {body}");
    let errors = body["shard_errors"].to_string();
    assert!(errors.contains("shard 1"), "body: {body}");
}

/// A late keyed retry does not undo an operator's clear (issue #1814).
#[tokio::test]
async fn a_keyed_retry_does_not_undo_a_manual_clear() {
    let (url, _container) = setup_test_database_url().await;
    let pool = build_test_pool(&url);
    let mut conn = pool.get().await.expect("get conn");
    set_build_policy(&mut conn, "default", "base-v1", None)
        .await
        .expect("seed base policy");
    drop(conn);
    let app = build_ramp_app(pool.clone());
    let ramp =
        json!({ "queue_name": "default", "target_build_id": "canary-v2", "ramp_percent": 10 });

    let (status, body) = post_json_with_key(
        &app,
        "/admin/build-routing/ramp",
        ramp.clone(),
        Some("k-manual"),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "body: {body}");
    let (status, body) = delete_json(&app, "/admin/build-routing/ramp/default").await;
    assert!(status.is_success(), "clear: {status} {body}");

    let (status, body) =
        post_json_with_key(&app, "/admin/build-routing/ramp", ramp, Some("k-manual")).await;
    assert_eq!(status, StatusCode::CONFLICT, "body: {body}");
    assert!(!ramp_is_active(&pool).await, "the cleared ramp stays off");
}
